# Embryo Data Query

This notebook queries embryo-related data from multiple databases for a given prontuario/PIN.

## Tables Queried:
- **Clinisys Silver Layer** (clinisys_all.duckdb):
  - view_micromanipulacao
  - view_micromanipulacao_oocitos
  - view_tratamentos
  - view_congelamentos_embrioes
  - view_descongelamentos_embrioes
  - view_embrioes_congelados
- **Huntington Data Lake** (huntington_data_lake.duckdb):
  - gold.clinisys_embrioes
  - gold.embryoscope_embrioes
  - gold.embryoscope_clinisys_combined
  - gold.embryoscope_treatment (from embryoscope_embrioes)
  - silver.planilha_embriologia
  - gold.planilha_embryoscope_combined

In [1]:
import duckdb
import pandas as pd
import os
from datetime import datetime

# Set pandas display options
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)

## Database Connections

In [2]:
def get_clinisys_connection():
    """Get connection to clinisys_all database"""
    clinisys_db_path = os.path.join('..', '..', 'database', 'clinisys_all.duckdb')
    return duckdb.connect(clinisys_db_path, read_only=True)

def get_huntington_connection():
    """Get connection to huntington_data_lake database"""
    huntington_db_path = os.path.join('..', '..', 'database', 'huntington_data_lake.duckdb')
    return duckdb.connect(huntington_db_path, read_only=True)

## Query Functions - Clinisys Tables

In [3]:
def query_micromanipulacao(conn, prontuario):
    """Query view_micromanipulacao for a specific prontuario"""
    print(f"\n=== VIEW_MICROMANIPULACAO ===")
    query = f"""
    SELECT * FROM silver.view_micromanipulacao 
    WHERE prontuario = {prontuario}
    ORDER BY codigo_ficha DESC
    """
    
    df = conn.execute(query).df()
    print(f"Found {len(df)} records in view_micromanipulacao")
    return df

def query_micromanipulacao_oocitos(conn, prontuario):
    """Query view_micromanipulacao_oocitos for a specific prontuario"""
    print(f"\n=== VIEW_MICROMANIPULACAO_OOCITOS ===")
    
    # First get codigo_ficha from view_micromanipulacao for this prontuario
    codigos_query = f"""
    SELECT codigo_ficha FROM silver.view_micromanipulacao 
    WHERE prontuario = {prontuario}
    """
    
    codigos_df = conn.execute(codigos_query).df()
    if not codigos_df.empty:
        codigo_list = codigos_df['codigo_ficha'].tolist()
        placeholders = ','.join(['?'] * len(codigo_list))
        
        oocitos_query = f"""
        SELECT * FROM silver.view_micromanipulacao_oocitos
        WHERE id_micromanipulacao IN ({placeholders})
        ORDER BY id_micromanipulacao, id
        """
        
        df = conn.execute(oocitos_query, codigo_list).df()
        print(f"Found {len(df)} records in view_micromanipulacao_oocitos")
    else:
        print("No codigo_ficha found for this prontuario in view_micromanipulacao.")
        df = pd.DataFrame()
    
    return df

In [4]:
def query_tratamentos(conn, prontuario):
    """Query view_tratamentos for a specific prontuario"""
    print(f"\n=== VIEW_TRATAMENTOS ===")
    query = f"""
    SELECT * FROM silver.view_tratamentos 
    WHERE prontuario = {prontuario}
    ORDER BY id DESC
    """
    
    df = conn.execute(query).df()
    print(f"Found {len(df)} records in view_tratamentos")
    return df

def query_congelamentos_embrioes(conn, prontuario):
    """Query view_congelamentos_embrioes for a specific prontuario"""
    print(f"\n=== VIEW_CONGELAMENTOS_EMBRIOES ===")
    query = f"""
    SELECT * FROM silver.view_congelamentos_embrioes 
    WHERE prontuario = {prontuario}
    ORDER BY id DESC
    """
    
    df = conn.execute(query).df()
    print(f"Found {len(df)} records in view_congelamentos_embrioes")
    return df

def query_descongelamentos_embrioes(conn, prontuario):
    """Query view_descongelamentos_embrioes for a specific prontuario"""
    print(f"\n=== VIEW_DESCONGELAMENTOS_EMBRIOES ===")
    query = f"""
    SELECT * FROM silver.view_descongelamentos_embrioes 
    WHERE prontuario = {prontuario}
    ORDER BY id DESC
    """
    
    df = conn.execute(query).df()
    print(f"Found {len(df)} records in view_descongelamentos_embrioes")
    return df

def query_embrioes_congelados(conn, prontuario):
    """Query view_embrioes_congelados for a specific prontuario"""
    print(f"\n=== VIEW_EMBRIOES_CONGELADOS ===")
    query = f"""
    SELECT * FROM silver.view_embrioes_congelados 
    WHERE prontuario = {prontuario}
    ORDER BY id DESC
    """
    
    df = conn.execute(query).df()
    print(f"Found {len(df)} records in view_embrioes_congelados")
    return df

def query_congelamentos_ovulos(conn, prontuario):
    """Query view_congelamentos_ovulos for a specific prontuario"""
    print(f"\n=== VIEW_CONGELAMENTOS_OVULOS ===")
    query = f"""
    SELECT * FROM silver.view_congelamentos_ovulos 
    WHERE prontuario = {prontuario}
    ORDER BY id DESC
    """
    
    df = conn.execute(query).df()
    print(f"Found {len(df)} records in view_congelamentos_ovulos")
    return df

def query_descongelamentos_ovulos(conn, prontuario):
    """Query view_descongelamentos_ovulos for a specific prontuario"""
    print(f"\n=== VIEW_DESCONGELAMENTOS_OVULOS ===")
    query = f"""
    SELECT * FROM silver.view_descongelamentos_ovulos 
    WHERE prontuario = {prontuario}
    ORDER BY id DESC
    """
    
    df = conn.execute(query).df()
    print(f"Found {len(df)} records in view_descongelamentos_ovulos")
    return df

def query_ovulos_congelados(conn, prontuario):
    """Query view_ovulos_congelados for a specific prontuario"""
    print(f"\n=== VIEW_OVULOS_CONGELADOS ===")
    query = f"""
    SELECT * FROM silver.view_ovulos_congelados 
    WHERE prontuario = {prontuario}
    ORDER BY id DESC
    """
    
    df = conn.execute(query).df()
    print(f"Found {len(df)} records in view_ovulos_congelados")
    return df

## Query Functions - Huntington Data Lake Tables

In [5]:
def query_clinisys_embrioes(conn, prontuario):
    """Query gold.clinisys_embrioes for a specific prontuario"""
    print(f"\n=== GOLD.CLINISYS_EMBRIOES ===")
    query = f"""
    SELECT * FROM gold.clinisys_embrioes 
    WHERE micro_prontuario = {prontuario}
    ORDER BY micro_Data_DL DESC, oocito_id_micromanipulacao DESC
    """
    
    df = conn.execute(query).df()
    print(f"Found {len(df)} records in gold.clinisys_embrioes")
    return df

def query_embryoscope_embrioes(conn, prontuario):
    """Query gold.embryoscope_embrioes for a specific prontuario"""
    print(f"\n=== GOLD.EMBRYOSCOPE_EMBRIOES ===")
    query = f"""
    SELECT * FROM gold.embryoscope_embrioes 
    WHERE prontuario = {prontuario}
    ORDER BY embryo_KIDDate DESC, treatment_TreatmentName DESC
    """
    
    df = conn.execute(query).df()
    print(f"Found {len(df)} records in gold.embryoscope_embrioes")
    return df

def query_embryoscope_clinisys_combined(conn, prontuario):
    """Query gold.embryoscope_clinisys_combined for a specific prontuario"""
    print(f"\n=== GOLD.EMBRYOSCOPE_CLINISYS_COMBINED ===")
    query = f"""
    SELECT * FROM gold.embryoscope_clinisys_combined 
    WHERE micro_prontuario = {prontuario}
    ORDER BY micro_Data_DL DESC, oocito_id_micromanipulacao DESC
    """
    
    df = conn.execute(query).df()
    print(f"Found {len(df)} records in gold.embryoscope_clinisys_combined")
    return df

In [6]:
def query_planilha_embriologia_fresh(conn, prontuario):
    """Query silver.planilha_embriologia for a specific prontuario"""
    print(f"\n=== SILVER.PLANILHA_EMBRIOLOGIA_FRESH ===")
    query = f"""
    SELECT * FROM silver.planilha_embriologia_fresh 
    WHERE prontuario = {prontuario}
    -- ORDER BY "DATA DA PUNÇÃO" DESC
    """
    
    df = conn.execute(query).df()
    print(f"Found {len(df)} records in silver.planilha_embriologia_fresh")
    return df

def query_planilha_embriologia_fet(conn, prontuario):
    """Query silver.planilha_embriologia for a specific prontuario"""
    print(f"\n=== SILVER.PLANILHA_EMBRIOLOGIA_FET ===")
    query = f"""
    SELECT * FROM silver.planilha_embriologia_fet 
    WHERE prontuario = {prontuario}
    -- ORDER BY "DATA DA FET" DESC
    """
    
    df = conn.execute(query).df()
    print(f"Found {len(df)} records in silver.planilha_embriologia_fresh")
    return df

def query_planilha_embriologia_combined(conn, prontuario):
    """Query silver.planilha_embriologia for a specific prontuario"""
    print(f"\n=== SILVER.PLANILHA_EMBRIOLOGIA_COMBINED  ===")
    query = f"""
    SELECT * FROM silver.planilha_embriologia_combined 
    WHERE prontuario = {prontuario}
    -- ORDER BY "DATA DA FET" DESC
    """
    
    df = conn.execute(query).df()
    print(f"Found {len(df)} records in silver.planilha_embriologia_fresh")
    return df

def query_planilha_embryoscope_combined(conn, prontuario):
    """Query gold.planilha_embryoscope_combined for a specific prontuario"""
    print(f"\n=== GOLD.PLANILHA_EMBRYOSCOPE_COMBINED ===")
    query = f"""
    SELECT * FROM gold.planilha_embryoscope_combined 
    WHERE "micro_prontuario" = {prontuario}
    ORDER BY "oocito_id" DESC
    """
    
    df = conn.execute(query).df()
    print(f"Found {len(df)} records in gold.planilha_embryoscope_combined")
    return df

In [7]:
def query_redlara_unified(conn, prontuario):
    """Query silver.redlara_unified for a specific prontuario"""
    print(f"\n=== silver.redlara_unified ===")
    query = f"""
    SELECT * FROM silver.redlara_unified
    where prontuario = {prontuario}
    """
    
    df = conn.execute(query).df()
    print(f"Found {len(df)} records in silver.redlara_unified")
    return df


def query_redlara_planilha_combined(conn, prontuario):
    """Query gold.redlara_planilha_combined for a specific prontuario"""
    print(f"\n=== gold.redlara_planilha_combined ===")
    query = f"""
    SELECT * FROM gold.redlara_planilha_combined
    where prontuario = {prontuario}
    """
    
    df = conn.execute(query).df()
    print(f"Found {len(df)} records in gold.redlara_planilha_combined")
    return df

## Main Query Function

In [8]:
def query_embryo_data(prontuario):
    """
    Query all embryo-related data for a given prontuario/PIN.
    
    Args:
        prontuario (str or int): The patient prontuario number
        
    Returns:
        dict: Dictionary containing all DataFrames with results
    """
    print(f"\n{'='*80}")
    print(f"QUERYING EMBRYO DATA FOR PRONTUARIO: {prontuario}")
    print(f"Query executed at: {datetime.now()}")
    print(f"{'='*80}")
    
    # Connect to databases
    clinisys_con = get_clinisys_connection()
    huntington_con = get_huntington_connection()
    
    try:
        # Query clinisys tables
        df_micromanipulacao = query_micromanipulacao(clinisys_con, prontuario)
        df_oocitos = query_micromanipulacao_oocitos(clinisys_con, prontuario)
        df_tratamentos = query_tratamentos(clinisys_con, prontuario)
        df_congelamentos_embrioes = query_congelamentos_embrioes(clinisys_con, prontuario)
        df_descongelamentos_embrioes = query_descongelamentos_embrioes(clinisys_con, prontuario)
        df_embrioes_congelados = query_embrioes_congelados(clinisys_con, prontuario)
        df_congelamentos_ovulos = query_congelamentos_ovulos(clinisys_con, prontuario)
        df_descongelamentos_ovulos = query_descongelamentos_ovulos(clinisys_con, prontuario)
        df_ovulos_congelados = query_ovulos_congelados(clinisys_con, prontuario)
        
        # Query huntington data lake tables
        df_clinisys_embrioes = query_clinisys_embrioes(huntington_con, prontuario)
        df_embryoscope_embrioes = query_embryoscope_embrioes(huntington_con, prontuario)
        df_embryoscope_clinisys_combined = query_embryoscope_clinisys_combined(huntington_con, prontuario)
        # df_embryoscope_treatment = query_embryoscope_treatment(huntington_con, prontuario)
        df_planilha_embriologia_fet = query_planilha_embriologia_fet(huntington_con, prontuario)
        df_planilha_embriologia_fresh = query_planilha_embriologia_fresh(huntington_con, prontuario)
        df_planilha_embriologia_combined = query_planilha_embriologia_combined(huntington_con, prontuario)
        df_planilha_embryoscope_combined = query_planilha_embryoscope_combined(huntington_con, prontuario)
        df_redlara_unified = query_redlara_unified(huntington_con, prontuario)
        df_redlara_planilha_combined = query_redlara_planilha_combined(huntington_con, prontuario)

        # Summary
        print(f"\n{'='*80}")
        print(f"QUERY SUMMARY FOR PRONTUARIO {prontuario}")
        print(f"{'='*80}")
        print(f"- view_micromanipulacao: {len(df_micromanipulacao)} records")
        print(f"- view_micromanipulacao_oocitos: {len(df_oocitos)} records")
        print(f"- view_tratamentos: {len(df_tratamentos)} records")
        print(f"- view_congelamentos_embrioes: {len(df_congelamentos_embrioes)} records")
        print(f"- view_descongelamentos_embrioes: {len(df_descongelamentos_embrioes)} records")
        print(f"- view_embrioes_congelados: {len(df_embrioes_congelados)} records")
        print(f"- view_congelamentos_ovulos: {len(df_congelamentos_ovulos)} records")
        print(f"- view_descongelamentos_ovulos: {len(df_descongelamentos_ovulos)} records")
        print(f"- view_ovulos_congelados: {len(df_ovulos_congelados)} records")
        print(f"- gold.clinisys_embrioes: {len(df_clinisys_embrioes)} records")
        print(f"- gold.embryoscope_embrioes: {len(df_embryoscope_embrioes)} records")
        print(f"- gold.embryoscope_clinisys_combined: {len(df_embryoscope_clinisys_combined)} records")
        print(f"- silver.planilha_embriologia_fet: {len(df_planilha_embriologia_fet)} records")
        print(f"- silver.planilha_embriologia_fresh: {len(df_planilha_embriologia_fresh)} records")
        print(f"- silver.planilha_embriologia_combined: {len(df_planilha_embriologia_combined)} records")
        print(f"- gold.planilha_embryoscope_combined: {len(df_planilha_embryoscope_combined)} records")
        print(f"- silver.redlara_unified: {len(df_redlara_unified)} records")
        print(f"- gold.redlara_planilha_combined: {len(df_redlara_planilha_combined)} records")

        print(f"{'='*80}")
        
        # Return results as dictionary
        results = {
            'micromanipulacao': df_micromanipulacao,
            'micromanipulacao_oocitos': df_oocitos,
            'tratamentos': df_tratamentos,
            'congelamentos_embrioes': df_congelamentos_embrioes,
            'descongelamentos_embrioes': df_descongelamentos_embrioes,
            'embrioes_congelados': df_embrioes_congelados,
            'congelamentos_ovulos': df_congelamentos_ovulos,
            'descongelamentos_ovulos': df_descongelamentos_ovulos,
            'ovulos_congelados': df_ovulos_congelados,
            'clinisys_embrioes': df_clinisys_embrioes,
            'embryoscope_embrioes': df_embryoscope_embrioes,
            'embryoscope_clinisys_combined': df_embryoscope_clinisys_combined,
            'planilha_embriologia_fet': df_planilha_embriologia_fet,
            'planilha_embriologia_fresh': df_planilha_embriologia_fresh,
            'planilha_embriologia_combined': df_planilha_embriologia_combined,
            'planilha_embryoscope_combined': df_planilha_embryoscope_combined,
            'redlara_unified': df_redlara_unified,
            'redlara_planilha_combined': df_redlara_planilha_combined,
        }
        
        return results
        
    finally:
        # Close connections
        clinisys_con.close()
        huntington_con.close()
        print("\nDatabase connections closed.")

## Example Usage

In [33]:
# Example usage
prontuario = 516203

# Query all embryo data
results = query_embryo_data(prontuario)

================================================================================
QUERYING EMBRYO DATA FOR PRONTUARIO: 516203
Query executed at: 2026-04-09 10:52:31.401813
================================================================================

=== VIEW_MICROMANIPULACAO ===
Found 7 records in view_micromanipulacao

=== VIEW_MICROMANIPULACAO_OOCITOS ===
Found 48 records in view_micromanipulacao_oocitos

=== VIEW_TRATAMENTOS ===
Found 10 records in view_tratamentos

=== VIEW_CONGELAMENTOS_EMBRIOES ===
Found 6 records in view_congelamentos_embrioes

=== VIEW_DESCONGELAMENTOS_EMBRIOES ===
Found 2 records in view_descongelamentos_embrioes

=== VIEW_EMBRIOES_CONGELADOS ===
Found 18 records in view_embrioes_congelados

=== VIEW_CONGELAMENTOS_OVULOS ===
Found 1 records in view_congelamentos_ovulos

=== VIEW_DESCONGELAMENTOS_OVULOS ===
Found 1 records in view_descongelamentos_ovulos

=== VIEW_OVULOS_CONGELADOS ===
Found 8 records in view_ovulos_congelados

=== GOLD.CLINISYS_EMBRIOES ===
Found 48 records in gold.clinisys_embrioes

=== GOLD.EMBRYOSCOPE_EMBRIOES ===
Found 36 records in gold.embryoscope_embrioes

=== GOLD.EMBRYOSCOPE_CLINISYS_COMBINED ===
Found 48 records in gold.embryoscope_clinisys_combined

=== SILVER.PLANILHA_EMBRIOLOGIA_FET ===
Found 0 records in silver.planilha_embriologia_fresh

=== SILVER.PLANILHA_EMBRIOLOGIA_FRESH ===
Found 0 records in silver.planilha_embriologia_fresh

=== SILVER.PLANILHA_EMBRIOLOGIA_COMBINED  ===
Found 0 records in silver.planilha_embriologia_fresh

=== GOLD.PLANILHA_EMBRYOSCOPE_COMBINED ===
Found 48 records in gold.planilha_embryoscope_combined

=== silver.redlara_unified ===
Found 0 records in silver.redlara_unified

=== gold.redlara_planilha_combined ===
Found 0 records in gold.redlara_planilha_combined

================================================================================
QUERY SUMMARY FOR PRONTUARIO 516203
================================================================================
- view_micromanipulacao: 7 records
- view_micromanipulacao_oocitos: 48 records
- view_tratamentos: 10 records
- view_congelamentos_embrioes: 6 records
- view_descongelamentos_embrioes: 2 records
- view_embrioes_congelados: 18 records
- view_congelamentos_ovulos: 1 records
- view_descongelamentos_ovulos: 1 records
- view_ovulos_congelados: 8 records
- gold.clinisys_embrioes: 48 records
- gold.embryoscope_embrioes: 36 records
- gold.embryoscope_clinisys_combined: 48 records
- silver.planilha_embriologia_fet: 0 records
- silver.planilha_embriologia_fresh: 0 records
- silver.planilha_embriologia_combined: 0 records
- gold.planilha_embryoscope_combined: 48 records
- silver.redlara_unified: 0 records
- gold.redlara_planilha_combined: 0 records
================================================================================

Database connections closed.

## Display Results

### 1. Micromanipulacao

In [34]:
print("=== MICROMANIPULACAO DATA ===")
micromanipulacao_data = results['micromanipulacao']
print(f"Records: {len(micromanipulacao_data)}")
if not micromanipulacao_data.empty:
    display(micromanipulacao_data)
else:
    print("No micromanipulacao data found.")

=== MICROMANIPULACAO DATA ===
Records: 7

,codigo_ficha,numero_caso,prontuario,IdadeEsposa_DG,IdadeMarido_DG,Data_DL,codigo_congelamento_semen,horario_inicial_fert,horario_final_fert,Aspiracao_DL,medico_id,responsavel_puncao_id,abstinencia_recomendada,recepcao_ovulos,CicloDoadora,IdadeDoadora,checagem_d4,Denud_DL,checagem_fertilizacao,checagem_d2,checagem_d3,checagem_d5,checagem_d6,checagem_d7,foliculos,oocitos,sangue_cateter_interno,dificuldade_transf,retorno_embrioes,vezes_retorno,sangue_cateter_externo,ICSIDescongelados,CicloDescongelamento,pgd_oocito,pgd_d3,pgd_d5,data_procedimento,tecnica_injetados,motilidade,morfologia_injetados,gradiente_descontinuo,mini_gradiente,data_procedimento_2,tecnica_injetados_2,motilidade_2,morfologia_injetados_2,unidade_id,data_microtese,data_microtese_2,validade7,responsavel_denud_id,profissional_fertilizacao_id,profissional_d2_id,profissional_d3_id,profissional_d5_id,profissional_d6_id,profissional_d7_id,validade11,materiais_insumos,local_coleta,fonte_outros,gradiente_descontinuo_2,viscosidade,volume_amostra_utilizada,morfologia_pre,morfologia_pos,zymot,mini_gradiente_2,local_coleta_2,fonte_outros_2,observacoes_resumo_ciclos,viscosidade_2,volume_amostra_utilizada_2,morfologia_pre_2,morfologia_pos_2,zymot_2,validade20,gradiente,lote21,validade21,agulha_icsi,lote_agulha_icsi,validade_agulha_icsi,agulha_aspir,lote_agulha_aspir,validade_agulha_aspir,incubadora,abstinencia_dias,meios,responsavel_oocitos_id,fonte,inicio_ps,termino_ps,volume_ps1,CongelamentoOvulos,concentracao_progressivos_pre,c_ps1,d_ps1,conc_ps1,diametro_minimo_pse,diametro_medio_pse,diametro_maximo_pse,tubulos_avaliados_pse,peso_total_pse,peso_microtese_pse,peso_biopsia_pse,diametro_minimo_psd,diametro_medio_psd,diametro_maximo_psd,tubulos_avaliados_psd,peso_total_psd,peso_microtese_psd,peso_biopsia_psd,responsavel_transfer_id,MorfologiaAlterada,EstadoSptz,CongelamentoSemenHom,VialsDescongeladasHom,CongelamentoSemenHet,VialsDescongeladasHet,check_gradiente_ps,concentrado,check_swimup,check_lavagem,volume_ps2,MotivoCongelamentoOvulos,concentracao_progressivos_pos,c_ps2,d_ps2,conc_ps2,comentarios_ps,responsavel_ps,fonte2,inicio_ps2,termino_ps2,volume_ps3,concentracao_progressivos_pre_2,c_ps3,d_ps3,conc_ps3,diametro_minimo_pse2,diametro_medio_pse2,diametro_maximo_pse2,tubulos_avaliados_pse2,peso_total_pse2,peso_microtese_pse2,peso_biopsia_pse2,diametro_minimo_psd2,diametro_medio_psd2,diametro_maximo_psd2,tubulos_avaliados_psd2,peso_total_psd2,peso_microtese_psd2,peso_biopsia_psd2,timelapse,EstadoSptz2,codigo_congelamento_semen_2,CongelamentoSemenHom2,VialsDescongeladasHom2,CongelamentoSemenHet2,VialsDescongeladasHet2,check_gradiente_ps2,concentrado_2,check_swimup2,check_lavagem2,volume_ps4,concentracao_progressivos_pos_2,c_ps4,d_ps4,conc_ps4,comentarios_ps2,responsavel_ps2,transferidos,cateter,lote_cateter,validade_cateter,motivo_nao_transferencia,Transfer_D5,medico_responsavel_id,azoospermia,cod1_crio,cod2_crio,tanque,cane,tecnica,Observacoes,responsavel_labfiv,responsavel_labfiv_data,tipo_paciente,responsavel_biopsia,alteracoes_oocitarias_normal,alteracoes_oocitarias_granulacao,alteracoes_oocitarias_pelucida,alteracoes_oocitarias_oval,alteracoes_oocitarias_inclusoes,alteracoes_oocitarias_pervitelineo_aumentado,alteracoes_oocitarias_irregular,alteracoes_oocitarias_necrotica,alteracoes_oocitarias_pervitelineo_granular,alteracoes_oocitarias_ser,alteracoes_oocitarias_corpusculo_frag,alteracoes_oocitarias_vacuolos,alteracoes_oocitarias_corpusculo_aum,alteracoes_oocitarias_membrana,alteracoes_oocitarias_corpusculo_peq,alteracoes_oocitarias_citoplasma,alteracoes_oocitarias_corpusculo_deg,controle_anual,maia,hash,extraction_timestamp
0,10309,ED4/22,516203,44,48,2022-02-16,None,10:45,10:56,None,209,None,None,Sim,BOSP,None,None,None,07:30,None,07:30,07:30,07:30,07:30,None,8,None,None,None,None,None,Sim,DO4/22,None,None,1,NaT,None,None,None,None,None,None,None,None,None,0000000007,<NA>,<NA>,<NA>,None,None,None,None,None,None,None,<NA>,None,None,None,None,None,None,None,None,None,None,None,<NA>,None,None,None,None,None,None,<NA>,<NA>,1249,<NA>,ICSI,None,None,WALLACE,7100,14/06/2026,08,2,|0000000481|0000000472|0000000475|0000000477|,2962,Ejaculado,08:15,08:58,"2,3",Não,74,7,19,"70,5",None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,Fresco,None,None,None,None,1,Isolate,None,None,"0,5",None,96,1,3,"11,2",None,1238,None,None,None,None,None,None,None,None,None,None,None,<NA>,<NA>,<NA>,<NA>,None,None,None,<NA>,<NA>,<NA>,<NA>,Sim,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,0,None,None,None,<NA>,Sim,209,Nenhum,<NA>,<NA>,<NA>,<NA>,<NA>,Placa Punção BD\tLot: 1152010\tval: indeterminada\r\nPlaca Mini GPS\tLot: 1264660\tval: 28/10/2024\r\nPlaca ICSI falcon\tLot: 10643\tval: 10/02/2022\r\nPlaca PICSI\tLot: 90042P\tval: 01/04/2022\r\nPlaca 4 poços\tLot: 21030199\tval: 06/04/2026\r\nPlaca Duplo Poço Vitrolife\tLot: 21040323\tval: 30/04/2026\r\nPlaca Duplo Poço Ingámed\tLot: 21070486\tval: 08/07/2026\r\nPlaca Pequena IVF GEN\tLot: 1067001\tval: indeterminada\r\nPlaca Embrio Slide\tLot: PP81904-1\tval: 01/04/2023\r\nTubo fundo redondo BD 15 ml\tLot: 11120030\tval: indeterminada\r\nTubo fundo redondo BD 5 ml\tLot: 24420039\tval: indeterminada\r\nTubo cônico 15 Falcon \tLot: 15920021\tval: indeterminada\r\nPipetex\tLot: 20201125\tval: 01/10/2023\r\nStripper 275 Vitromed\tLot: 21576VD27\tval: 20/09/2024\r\nStripper 175 Ingámed\tLot: 21411VD75\tval: 20/02/2024\r\nStripper 135 Vitromed\tLot: 44200203\tval:01/04/2023\r\nHolding\tLot: 5990\tval: 01/04/2024\r\nInjection\tLote: 6781\tval: 04/05/2024\r\nFrasco coletor - Prolab\tLot: 92821\tval: 23/02/2024\r\nAgulha Biópsia\tLot: 6801\tva: 29/04/2024\r\nPipeta Pasteur Vidro\tLot: 292213\tval: 13/07/2023\r\n,None,None,esposa,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,722e0289884aaa58b1eae1d9c2f1607f,2025-07-21 21:39:47
1,10163,745/21,516203,44,48,2021-11-30,None,10:50,11:00,08:00,209,1249,None,Não,None,None,None,10:40,07:30,None,07:30,10:00,07:30,07:30,7,10,None,None,None,None,None,Não,None,None,None,1,NaT,None,None,None,None,None,None,None,None,None,0000000007,<NA>,<NA>,<NA>,None,None,None,None,None,None,None,<NA>,None,None,None,None,None,None,None,None,None,None,None,<NA>,None,None,None,None,None,None,<NA>,<NA>,1075,<NA>,Cook,N180683,30/06/2024,WALLACE,6210,02/12/2026,08,2,|0000000463|0000000465|0000000459|0000000466|,2962,Ejaculado,09:15,10:09,"3,0",Não,61,1,38,"27,0",None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,Fresco,None,None,None,None,1,ISOLATE,None,None,"0,5",None,80,1,19,"7,8",None,2611,None,None,None,None,None,None,None,None,None,None,None,<NA>,<NA>,<NA>,<NA>,None,None,None,<NA>,<NA>,<NA>,<NA>,Sim,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,0,None,None,None,<NA>,Sim,209,Nenhum,<NA>,<NA>,<NA>,<NA>,<NA>,Placa Punção BD\tLot: 1152010\tval: indeterminada\r\nPlaca Mini GPS\tLot: 1292129\tval: 19/10/2025\r\nPlaca ICSI falcon\tLot: 1038002\tval: 01/2024\r\nPlaca PICSI\tLot: 90042P\tval: 01/04/2022\r\nPlaca 4 poços\tLot: 21030199\tval: 06/04/2026\r\nPlaca Duplo Poço Vitrolife\tLot: 21040323\tval: 30/04/2026\r\nPlaca Duplo Poço Ingámed\tLot: 21040323\tval: 30/04/2026\r\nPlaca Pequena IVF GEN\tLot: 1067001\tval: indeterminada\r\nPlaca Embrio Slide\tLot: PP81904-1\tval: 01/04/2023\r\nTubo fundo redondo BD 15 ml\tLot: 11120030\tval: indeterminada\r\nTubo fundo redondo BD 5 ml\tLot: 24420039\tval: indeterminada\r\nTubo cônico 15 Falcon \tLot: 15920021\tval: indeterminada\r\nPipetex\tLot: 20201125\tval: 01/10/2023\r\nStripper 275 Vitromed\tLot: 21496VD27\tval: 06/09/2024\r\nStripper 175 Ingámed\tLot: 21411VD75\tval: 20/02/2024\r\nStripper 135 Vitromed\tLot: 44200203\tval:01/04/2023\r\nHolding COOK\tLot: N175563\tval: 31/10/2023\r\nInjection COOK\tN180683\tval: 30/06/2024\r\nFrasco coletor - Prolab\tLot: 92821\tval: 23/02/2024\r\nAgulha Biópsia\tLot: 6632\tva: 08/04/2024\r\nPipeta Pasteur Vidro\tLot: 292213\tval: 13/07/2023\r\n,2962,15/12/2021,esposa,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,fea289326930b3973e6139e7c367c10a,2025-07-21 21:39:47
2,10116,704/21,516203,44,48,2021-11-12,None,10:50,11:00,08:00,209,2962,None,Não,None,None,None,10:40,07:30,None,08:30,07:30,07:30,07:30,4,5,None,None,None,None,None,Não,None,None,None,None,NaT,None,None,None,None,None,None,None,None,None,0000000007,<NA>,<NA>,<NA>,None,None,None,None,None,None,None,<NA>,None,None,None,None,None,None,None,None,None,None,None,<NA>,None,None,None,None,None,None,<NA>,<NA>,None,<NA>,Cook,N180683,30/06/2024,Wallace,6210,02/12/2026,08,2,|0000000463|0000000465|0000000459|0000000456|0000000462|,2962,Ejaculado,09:10,10:02,"3,0",Não,74,4,22,"40,0",None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,Fresco,None,None,None,None,1,ISOLATE,None,None,"0,5",None,95,3,2,"17,5",None,2611,None,None,None,None,None,None,None,None,None,None,None,<NA>,<NA>,<NA>,<NA>,None,None,None,<NA>,<NA>,<NA>,<NA>,Sim,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,0,None,None,None,<NA>,Sim,209,Nenhum,<NA>,<NA>,<NA>,<NA>,<NA>,Placa Punção BD\tLot: 1152010\tval: indeterminada\r\nPlaca Mini GPS\tLot: 1292129\tval: 19/10/2025\r\nPlaca ICSI falcon\tLot: 1038002\tval: 01/2024\r\nPlaca PICSI\tLot: 90042P\tval: 01/04/2022\r\nPlaca 4 poços\tLot: 21030199\tval: 06/04/2026\r\nPlaca Duplo Poço Vitrolife\tLot: 21040323\tval: 30/04/2026\r\nPlaca Duplo Poço Ingámed\tLot: 21040323\tval: 30/04/2026\r\nPlaca Pequena IVF GEN\tLot: 1067001\tval: indeterminada\r\nPlaca Embrio Slide\tLot: PP81904-1\tval: 01/04/2023\r\nTubo fundo redondo BD 15 ml\tLot: 11120030\tval: indeterminada\r\nTubo fundo redondo BD 5 ml\tLot: 24420039\tval: indeterminada\r\nTubo cônico 15 Falcon \tLot: 15920021\tval: indeterminada\r\nPipetex\tLot: 20201125\tval: 01/10/2023\r\nStripper 275 Vitromed\tLot: 21496VD27\tval: 06/09/2024\r\nStripper 175 Ingámed\tLot: 21411VD75\tval: 20/02/2024\r\nStripper 135 Vitromed\tLot: 44200203\tval:01/04/2023\r\nHolding COOK\tLot: N175563\tval: 31/10/2023\r\nInjection COOK\tN180683\tval: 30/06/2024\r\nFrasco coletor - Prolab\tLot: 92821\tval: 23/02/2024\r\nAgulha Biópsia\tLot: 6632\tva: 08/04/2024\r\nPipeta Pasteur Vidro\tLot: 292213\tval: 13/07/2023\r\n,2962,15/12/2021,esposa,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,df7cbfb9e9bc12c5b651797de893ad3a,2025-07-21 21:39:47
3,8088,156/21,516203,44,47,2021-03-29,None,12:20,12:30,09:20,209,1237,None,Não,None,None,None,12:20,07:30,None,07:30,08:00,07:30,07:30,4,5,None,None,None,None,None,Não,None,None,None,None,NaT,None,None,None,None,None,None,None,None,None,0000000007,<NA>,<NA>,<NA>,None,None,None,None,None,None,None,<NA>,None,None,None,None,None,None,None,None,None,None,None,<NA>,None,None,None,None,None,None,<NA>,<NA>,None,<NA>,Cook,N175742,31/10/2023,WALLACE,5311,22/06/2025,08,"2,5",|0000000402|0000000398|0000000409|0000000411|0000000408|0000000405|,1237,Ejaculado,08:49,09:33,"3,5",Não,75,6,19,"58,5",None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,Fresco,None,None,None,None,1,Isolate,None,None,"0,5",None,87,3,10,"3,6",None,2611,None,None,None,None,None,None,None,None,None,None,None,<NA>,<NA>,<NA>,<NA>,None,None,None,<NA>,<NA>,<NA>,<NA>,Sim,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,0,None,None,None,<NA>,Sim,209,Nenhum,<NA>,<NA>,<NA>,<NA>,<NA>,Placa Punção BD\tLot: 9297008\tval: indeterminada\r\nPlaca Mini GPS\tLot: 1264660\tval: 28/10/2024\r\nPlaca ICSI Vitrolife\tLot: 10643\tval: 15/02/2022\r\nPlaca PICSI\tLot: 90028P\tval: 01/03/2022\r\nPlaca 4 poços\tLot: 2010726\tval: 20/11/2025\r\nPlaca Duplo Poço Vitrolife\tLot: -\tval: -\r\nPlaca Duplo Poço Ingámed\tLot: 20080597\tval: 03/09/2025\r\nPlaca Pequena IVF GEN\tLot: 0377001\tval: 29/09/2022\r\nPlaca Embrio Slide\tLot: PP81811-1\tval: 01/11/2022\r\nTubo fundo redondo BD 15 ml\tLot: 11120030\tval: indeterminada\r\nTubo fundo redondo BD 5 ml\tLot: 24420039\tval: indeterminada\r\nTubo cônico 15 Falcon \tLot: 15920021\tval: indeterminada\r\nPipetex\tLot: 20052381\tval: indeterminada\r\nStripper 275 Ingámed\tLot: 20070431\tval: 01/04/2023\r\nStripper 175 Ingámed\tLot: 20070506\tval: 01/04/2024\r\nStripper 135 Ingámed\tLot: 20070499\tval: 01/04/2023\r\nHolding \tLot: N175804\tval: 31/10/2023\r\nFrasco coletor - Prolab\tLot: 88322\tval: 27/03/2023\r\nAgulha Biópsia\tLot: 5342\tva: 30/06/2023\r\nPipeta Pasteur Vidro\tLot: 292213\tval: 13/07/2023\r\n,1237,15/04/2021,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,988a61ffbee3e31dfb7a63b052fb8ae1,2025-07-21 21:39:47
4,8048,119/21,516203,44,47,2021-03-11,None,11:40,11:50,08:40,209,1075,None,Não,None,None,None,11:30,07:30,None,08:50,08:00,07:30,07:30,6,6,None,None,None,None,None,Não,None,None,None,1,NaT,None,None,None,None,None,None,None,None,None,0000000007,<NA>,<NA>,<NA>,None,None,None,None,None,None,None,<NA>,None,None,None,None,None,None,None,None,None,None,None,<NA>,None,None,None,None,None,None,<NA>,<NA>,1249,<NA>,Cook,N172364,31/05/2023,WALLACE,5311,22/06/2025,08,"2,5",|0000000402|0000000398|0000000400|0000000397|0000000405|,1393,Ejaculado,08:55,09:56,"3,0",Não,53,10,37,"20,6",None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,Fresco,None,None,None,None,1,Isolate,None,None,"0,5",None,92,1,7,"5,0",None,2611,None,None,None,None,None,None,None,None,None,None,None,<NA>,<NA>,<NA>,<NA>,None,None,None,<NA>,<NA>,<NA>,<NA>,Sim,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,0,None,None,None,<NA>,Sim,209,Nenhum,<NA>,<NA>,<NA>,<NA>,<NA>,Placa Punção BD\tLot: 9297008\tval: indeterminada\r\nPlaca Mini GPS\tLot: 1264660\tval: 28/10/2024\r\nPlaca ICSI Vitrolife\tLot: 10643\tval: 15/02/2022\r\nPlaca PICSI\tLot: 90028P\tval: 01/03/2022\r\nPlaca 4 poços\tLot: 2010726\tval: 20/11/2025\r\nPlaca Duplo Poço Vitrolife\tLot: -\tval: -\r\nPlaca Duplo Poço Ingámed\tLot: 20080597\tval: 03/09/2025\r\nPlaca Pequena IVF GEN\tLot: 280917\tval: 28/09/2022\r\nPlaca Embrio Slide\tLot: PP81811-1\tval: 01/11/2022\r\nTubo fundo redondo BD 15 ml\tLot: 11120030\tval: indeterminada\r\nTubo fundo redondo BD 5 ml\tLot: 24420039\tval: indeterminada\r\nTubo cônico 15 Falcon \tLot: 15920021\tval: indeterminada\r\nPipetex\tLot: 20052381\tval: indeterminada\r\nStripper 275 Ingámed\tLot: 20070431\tval: 01/04/2023\r\nStripper 175 Ingámed\tLot: 20070506\tval: 01/04/2024\r\nStripper 135 Ingámed\tLot: 20070499\tval: 01/04/2023\r\nHolding \tLot: 4942\tval: 08/05/2023\r\nFrasco coletor - Prolab\tLot: 88322\tval: 27/03/2023\r\nAgulha Biópsia\tLot: 5342\tva: 30/06/2023\r\nPipeta Pasteur Vidro\tLot: 292213\tval: 13/07/2023\r\n,1075,01/04/2021,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,ce727872a00b72fc7565008aae51db6b,2025-07-21 21:39:47
5,7507,295/20,516203,43,47,2020-07-22,None,12:05,12:15,09:00,214,1249,None,Não,None,None,None,12:00,07:30,None,07:30,07:30,07:30,07:30,6,6,None,None,None,None,None,Não,None,None,None,1,NaT,None,None,None,None,None,None,None,None,None,0000000007,<NA>,<NA>,<NA>,None,None,None,None,None,None,None,<NA>,None,None,None,None,None,None,None,None,None,None,None,<NA>,None,None,None,None,None,None,<NA>,<NA>,None,<NA>,Cook,N164870,None,WALLACE,3690,04/11/2024,08,2,|0000000301|0000000319|0000000316|0000000318|0000000307|,1288,Ejaculado,08:35,09:20,"2,0",Não,79,8,13,"70,5",None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,Fresco,None,None,None,None,1,Isolate,None,None,"0,5",None,93,2,5,"3,3",Morfologia Pré = 4%\r\nMorfologia Pós = 5%,1238,None,None,None,None,None,None,None,None,None,None,None,<NA>,<NA>,<NA>,<NA>,None,None,None,<NA>,<NA>,<NA>,<NA>,Sim,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,0,None,None,None,<NA>,Sim,214,Nenhum,<NA>,<NA>,<NA>,<NA>,<NA>,Placa Punção BD\tLot: 9189019\tval: indeterminada\r\nPlaca Mini GPS\tLot: 1210605\tval: 28/04/2023\r\nPlaca ICSI Vitrolife\tLot: 9961\tval: 08/03/2021\r\nPlaca 4 poços\tLot: 19110772\tval: 22/11/2024\r\nPlaca Duplo Poço Vitrolife\tLot: 11010\tval: 26/08/2022\r\nPlaca Duplo Poço Ingámed\tLot: 19070445\tval: 25/07/2024\r\nPlaca Pequena BD\tLot: 9099006\tval: indeterminada\r\nPlaca Embrio Slide\tLot: PP818021\tval: 01/02/2022\r\nTubo fundo redondo BD 15 ml\tLot: 21019030\tval: indeterminada\r\nTubo fundo redondo BD 5 ml\tLot: 13619044\tval: indeterminada\r\nTubo cônico 15 Falcon \tLot: 15419162\tval: indeterminada\r\nPipetex\tLot: 19370205\tval: indeterminada\r\nStripper 300 Cook\tLot: N166950\tval: 30/09/2021\r\nStripper 170 Cook\tLot: N162817\tval: 28/02/2021\r\nStripper 140 Cook\tLot: N164401\tval: 31/05/2021\r\nIngase\tLot: 20050310\tval: 17/08/2020\r\nSSS\tLot: 99193190502\tval: 31/05/2021\r\nPBS Ingamed\tLot: 19110833\tval: 28/11/2020\r\nFrasco coletor - Prolab\tLot: 85611\tval: 08/10/2022\r\n,1249,28/09/2020,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,420c51fb4216f9a64b5bc30e9ca86105,2025-07-21 21:39:47
6,7469,259/20,516203,43,120,2020-07-04,None,11:30,11:45,09:30,229,1393,None,Não,None,None,None,11:30,07:30,None,07:30,07:30,07:30,07:30,4,8,None,None,None,None,None,Não,None,None,None,None,NaT,None,None,None,None,None,None,None,None,None,0000000007,<NA>,<NA>,<NA>,None,None,None,None,None,None,None,<NA>,None,None,None,None,None,None,None,None,None,None,None,<NA>,None,None,None,None,None,None,<NA>,<NA>,None,<NA>,Cook,N165601,31/07/2022,WALLACE,3692,04/11/2024,08,2,|0000000301|0000000309|0000000310|0000000311|0000000307|,1237,Ejaculado,09:05,09:43,"2,5",Não,74,5,21,"59,0",None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,Fresco,None,None,None,None,1,Isolate,None,None,"0,5",None,96,2,2,"5,7",Morfologia Pré - 4%\r\nMorfologia Pós - 6%,1238,None,None,None,None,None,None,None,None,None,None,None,<NA>,<NA>,<NA>,<NA>,None,None,None,<NA>,<NA>,<NA>,<NA>,Sim,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,0,None,None,None,<NA>,Sim,214,Nenhum,<NA>,<NA>,<NA>,<NA>,<NA>,Placa Punção BD\tLot: 9189019\tval: indeterminada\r\nPlaca Mini GPS\tLot: 1210605\tval: 28/04/2023\r\nPlaca ICSI Vitrolife\tLot: 9961\tval: 08/03/2021\r\nPlaca 4 poços\tLot: 19110772\tval: 22/11/2024\r\nPlaca Duplo Poço Vitrolife\tLot: 11010\tval: 26/08/2022\r\nPlaca Duplo Poço Ingámed\tLot: 19070445\tval: 25/07/2024\r\nPlaca Pequena BD\tLot: 9099006\tval: indeterminada\r\nPlaca Embrio Slide\tLot: PP818021\tval: 01/02/2022\r\nTubo fundo redondo BD 15 ml\tLot: 21019030\tval: indeterminada\r\nTubo fundo redondo BD 5 ml\tLot: 13619044\tval: indeterminada\r\nTubo cônico 15 Falcon \tLot: 15419162\tval: indeterminada\r\nPipetex\tLot: 19370205\tval: indeterminada\r\nStripper 300 Cook\tLot: N166950\tval: 30/09/2021\r\nStripper 170 Cook\tLot: N162817\tval: 28/02/2021\r\nStripper 140 Cook\tLot: N164401\tval: 31/05/2021\r\nIngase\tLot: 20020100\tval: 18/05/2020\r\nSSS\tLot: 99193190502\tval: 31/05/2021\r\nPBS Ingamed\tLot: 19110833\tval: 28/11/2020\r\nFrasco coletor - Prolab\tLot: 85611\tval: 08/10/2022\r\n,1393,04/08/2020,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,5a00441b9eb511af6529d98490edf009,2025-07-21 21:39:47

### 2. Micromanipulacao Oocitos

In [35]:
print("=== MICROMANIPULACAO OOCITOS DATA ===")
oocitos_data = results['micromanipulacao_oocitos']
print(f"Records: {len(oocitos_data)}")
if not oocitos_data.empty:
    display(oocitos_data)
else:
    print("No micromanipulacao oocitos data found.")

=== MICROMANIPULACAO OOCITOS DATA ===
Records: 48

,id,id_micromanipulacao,diaseguinte,Maturidade,RC,ComentariosAntes,Embriologista,PI,TCD,AH,PGD,ResultadoPGD,IdentificacaoPGD,Fertilizacao,CorpusculoPolar,ComentariosDepois,GD1,OocitoDoado,ICSI,OrigemOocito,InseminacaoOocito,NClivou_D2,NCelulas_D2,Frag_D2,Blastomero_D2,NClivou_D3,NCelulas_D3,Frag_D3,Blastomero_D3,GD2,NClivou_D4,NCelulas_D4,Compactando_D4,MassaInterna_D4,Trofoblasto_D4,NClivou_D5,NCelulas_D5,Compactando_D5,MassaInterna_D5,Trofoblasto_D5,NClivou_D6,NCelulas_D6,Compactando_D6,MassaInterna_D6,Trofoblasto_D6,NClivou_D7,NCelulas_D7,Compactando_D7,MassaInterna_D7,Trofoblasto_D7,score_maia,relatorio_ia,hash,extraction_timestamp,ResultadoPGDDetalhes,embryo_number
0,68711,7469,Não,MII,1,None,1237,None,Criopreservado,Sim,Sim,None,PGT-A,2PN,None,None,None,Não,None,Fresco,ICSI,None,None,None,None,Sim,8,1,Simétricos,None,None,None,None,None,None,Sim,None,Blastocisto Grau 5,A,A,None,None,None,None,None,None,None,None,None,None,None,None,625db2393581738918526aaf349da8f4,2026-02-05 21:00:42,None,1
1,68712,7469,Não,MII,2,None,1237,None,Descartado,None,None,None,None,NF,None,None,None,Não,None,Fresco,ICSI,None,None,None,None,Não,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,b074af2d2586431a8a3ad4a8bdfafde0,2026-02-05 21:00:42,None,2
2,68713,7469,Não,MII,3,None,1237,None,Criopreservado,None,None,None,None,2PN,None,None,None,Não,None,Fresco,ICSI,None,None,None,None,Sim,7,1,Simétricos,None,None,None,None,None,None,Sim,None,Mórula,None,None,Sim,None,Blastocisto Grau 5,A,B,None,None,None,None,None,None,None,5374b4f342685ca1575f191b49aef15a,2026-02-05 21:00:42,None,3
3,68714,7469,Não,MII,4,None,1237,None,Criopreservado,Sim,Sim,None,PGT-A,2PN,None,None,None,Não,None,Fresco,ICSI,None,None,None,None,Sim,8,1,Compactando,None,None,None,None,None,None,Sim,None,Blastocisto Grau 5,A,A,None,None,None,None,None,None,None,None,None,None,None,None,0c56aa6d27919fc8c428c96865d41396,2026-02-05 21:00:42,None,4
4,68715,7469,Não,MII,5,None,1237,None,Descartado,None,None,None,None,NF,None,None,None,Não,None,Fresco,ICSI,None,None,None,None,Não,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,c1242d18068c385d9775d6d04b2b6aee,2026-02-05 21:00:42,None,5
5,68716,7469,Não,MII,6,None,1237,None,Descartado,None,None,None,None,2PN,None,None,None,Não,None,Fresco,ICSI,None,None,None,None,Sim,6,1,Simétricos,None,None,None,None,None,None,Não,None,None,None,None,Não,None,None,None,None,Não,None,None,None,None,None,None,8ca618d19e1c35afcd6918e87c99e2c3,2026-02-05 21:00:42,None,6
6,68717,7469,Não,MII,7,None,1237,None,Descartado,None,None,None,None,NF,None,None,None,Não,None,Fresco,ICSI,None,None,None,None,Não,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,a1d096d6122bd7be39c5ef95ef432d8d,2026-02-05 21:00:42,None,7
7,68718,7469,Não,MI,None,None,None,None,Descartado,None,None,None,None,None,None,None,None,Não,None,Fresco,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,4b75bcad2ebe778606e64312114f7004,2026-02-05 21:00:42,None,8
8,69101,7507,Não,MII,None,None,1249,None,Descartado,None,None,None,None,2PN,None,None,None,Não,None,Fresco,ICSI,None,None,None,None,Sim,5,2,Simétricos,None,None,None,None,None,None,Não,None,None,None,None,Não,None,None,None,None,Não,None,None,None,None,None,None,c56dcc2b680cd34655270cb53bbe8496,2026-02-05 21:00:42,None,1
9,69102,7507,Não,MII,None,None,1249,None,Descartado,None,None,None,None,NF,None,None,None,Não,None,Fresco,ICSI,None,None,None,None,Não,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,77df602e04b11d9449d5dfb681a34697,2026-02-05 21:00:42,None,2
10,69103,7507,Não,MII,None,None,1249,None,Descartado,None,None,None,None,2PN,None,None,None,Não,None,Fresco,ICSI,None,None,None,None,Sim,7,2,Simétricos,None,None,None,None,None,None,Não,None,None,None,None,Não,None,None,None,None,Não,None,None,None,None,None,None,eae8bf50003889fc0e77c8c8a4cd347c,2026-02-05 21:00:42,None,3
11,69104,7507,Não,MII,None,None,1249,None,Descartado,None,None,None,None,NF,None,None,None,Não,None,Fresco,ICSI,None,None,None,None,Não,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,295e06e6093110fd48c04ee79ad8298c,2026-02-05 21:00:42,None,4
12,69105,7507,Não,MII,None,None,1249,None,Criopreservado,None,Sim,None,None,2PN,None,None,None,Não,None,Fresco,ICSI,None,None,None,None,Sim,10,1,Simétricos,None,None,None,None,None,None,Sim,None,Blastocisto Grau 5,A,A,None,None,None,None,None,None,None,None,None,None,None,None,54e8c3f51bdda0d2074f219ef8636f42,2026-02-05 21:00:42,None,5
13,69106,7507,Não,MI,None,None,None,None,Descartado,None,None,None,None,None,None,None,None,Não,None,Fresco,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,25a9e68134c1cf7188c990bfcae00824,2026-02-05 21:00:42,None,6
14,74458,8048,Não,MII,1,None,1393,None,Criopreservado,None,None,None,None,2PN,None,None,None,Não,None,Fresco,ICSI,None,None,None,None,Sim,6,1,Simétricos,None,None,None,None,None,None,Sim,None,Blastocisto Grau 2,None,None,Sim,None,Blastocisto Grau 5,B,C,None,None,None,None,None,None,None,013faab7d49496e9f4519ae9273b834a,2026-02-05 21:00:42,None,1
15,74459,8048,Não,MII,2,None,1393,None,Descartado,None,None,None,None,NF,None,None,None,Não,None,Fresco,ICSI,None,None,None,None,Não,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,ac64d1c0831649d11b09de7219f4435b,2026-02-05 21:00:42,None,2
16,74460,8048,Não,MII,3,None,1393,None,Descartado,None,None,None,None,2PN,None,None,None,Não,None,Fresco,ICSI,None,None,None,None,Sim,5,2,Assimétricos,None,None,None,None,None,None,Não,None,None,None,None,Não,None,None,None,None,Não,None,None,None,None,None,None,940a1ca1ffb627af7f697ad152ce2ef3,2026-02-05 21:00:42,None,3
17,74461,8048,Não,MII,4,None,1393,None,Criopreservado,None,Sim,None,PGT-A,2PN,None,None,None,Não,None,Fresco,ICSI,None,None,None,None,Sim,8,1,Compactando,None,None,None,None,None,None,Sim,None,Blastocisto Grau 5,A,B,None,None,None,None,None,None,None,None,None,None,None,None,c9903e1493a3484f634e364d6f87fc1b,2026-02-05 21:00:42,None,4
18,74462,8048,Não,MII,5,None,1393,None,Criopreservado,None,None,None,None,2PN,None,None,None,Não,None,Fresco,ICSI,None,None,None,None,Sim,8,1,Simétricos,None,None,None,None,None,None,Sim,None,Blastocisto Grau 2,None,None,Sim,None,Blastocisto Grau 5,B,C,None,None,None,None,None,None,None,4472ee6b3e9532a1e4760c49b62a1ea6,2026-02-05 21:00:42,None,5
19,74463,8048,Não,GV,None,None,None,None,Descartado,None,None,None,None,None,None,None,None,Não,None,Fresco,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,ebad6da283a4d8bfe394160700cd9bc0,2026-02-05 21:00:42,None,6
20,74948,8088,Não,MII,1,None,1237,None,Criopreservado,Sim,Sim,None,PGT-A,2PN,None,None,None,Não,None,Fresco,ICSI,None,None,None,None,Sim,7,2,Simétricos,None,None,None,None,None,None,Sim,None,Blastocisto Grau 5,A,B,None,None,None,None,None,None,None,None,None,None,None,None,92497c14d2a4db85b1a868c7b9936124,2026-02-05 21:00:42,None,1
21,74949,8088,Não,MII,2,None,1237,None,Descartado,None,None,None,None,2CP,None,None,None,Não,None,Fresco,ICSI,None,None,None,None,Sim,3,1,Simétricos,None,None,None,None,None,None,Não,None,None,None,None,Não,None,None,None,None,Não,None,None,None,None,None,None,3afb557c15ab9a7aa25e7bfc831bb74a,2026-02-05 21:00:42,None,2
22,74950,8088,Não,MII,3,None,1237,None,Descartado,None,None,None,None,2PN,None,None,None,Não,None,Fresco,ICSI,None,None,None,None,Sim,8,1,Simétricos,None,None,None,None,None,None,Não,None,None,None,None,Não,None,None,None,None,Não,None,None,None,None,None,None,5f1b3959b53a4d81d738930de5f25ac7,2026-02-05 21:00:42,None,3
23,74951,8088,Não,MII,4,None,1237,None,Criopreservado,None,Sim,None,PGT-A,2PN,None,None,None,Não,None,Fresco,ICSI,None,None,None,None,Sim,5,1,Simétricos,None,None,None,None,None,None,Não,None,None,None,None,Não,None,None,None,None,Sim,None,Blastocisto Grau 5,C,B,None,None,c47951761ce6ebfa5baf303fd03057ff,2026-02-05 21:00:42,None,4
24,74952,8088,Não,MII,5,None,1237,None,Descartado,None,None,None,None,2PN,None,None,None,Não,None,Fresco,ICSI,None,None,None,None,Sim,8,1,Simétricos,None,None,None,None,None,None,Não,None,None,None,None,Não,None,None,None,None,Não,None,None,None,None,None,None,34f5463d4beae70f52eab9c8ecc50ff0,2026-02-05 21:00:42,None,5
25,83347,10116,Não,MII,1,None,1237,None,Descartado,None,None,None,None,2CP,None,None,None,Não,None,Fresco,ICSI,None,None,None,None,Sim,4,1,Simétricos,None,None,None,None,None,None,Não,None,None,None,None,Não,None,None,None,None,Não,None,None,None,None,None,None,2504bebb60702b3d44a6823aa5006d40,2026-02-05 21:00:42,None,1
26,83348,10116,Não,MII,2,None,1237,None,Descartado,None,None,None,None,3PN+,None,None,None,Não,None,Fresco,ICSI,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,6206bc5fff2ab435f5410684133d4d20,2026-02-05 21:00:42,None,2
27,83349,10116,Não,MII,3,None,1237,None,Descartado,None,None,None,None,2PN,None,None,None,Não,None,Fresco,ICSI,None,None,None,None,Sim,3,1,Simétricos,None,None,None,None,None,None,Não,None,None,None,None,Não,None,None,None,None,Não,None,None,None,None,None,None,b2fe850fe6c6698805e90e4374a1f317,2026-02-05 21:00:42,None,3
28,83350,10116,Não,MII,4,None,1237,None,Descartado,None,None,None,None,DEG,None,None,None,Não,None,Fresco,ICSI,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,8c05dc225354e97c182837ab5c86e77b,2026-02-05 21:00:42,None,4
29,83351,10116,Não,GV,None,None,None,None,Descartado,None,None,None,None,None,None,None,None,Não,None,Fresco,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,da0e8d536b1ec4c60e185ce99dda4e9f,2026-02-05 21:00:42,None,5
30,83810,10163,Não,MII,1,None,1237,None,Criopreservado,None,Sim,None,PGT-A,2PN,None,None,None,Não,None,Fresco,ICSI,None,None,None,None,Sim,6,1,Simétricos,None,None,None,None,None,None,Sim,None,Blastocisto Grau 5,B,C,None,None,None,None,None,None,None,None,None,None,None,None,e2ce58edafddf7c13511607c76b09260,2026-02-05 21:00:42,None,1
31,83811,10163,Não,MII,2,None,1237,None,Descartado,None,None,None,None,DEG,None,None,None,Não,None,Fresco,ICSI,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,5c5d81fc4097d61da5785aec6a9ba6ba,2026-02-05 21:00:42,None,2
32,83812,10163,Não,MII,3,None,1237,None,Criopreservado,None,Sim,None,PGT-A,2PN,None,None,None,Não,None,Fresco,ICSI,None,None,None,None,Sim,6,1,Compactando,None,None,None,None,None,None,Sim,None,Blastocisto Grau 5,A,B,None,None,None,None,None,None,None,None,None,None,None,None,1a858ad1b02b89e5ca165b79644fdf36,2026-02-05 21:00:42,None,3
33,83813,10163,Não,MII,4,None,1237,None,Descartado,None,None,None,None,2PN,None,None,None,Não,None,Fresco,ICSI,None,None,None,None,Sim,6,1,Simétricos,None,None,None,None,None,None,Não,None,None,None,None,Não,None,None,None,None,Não,None,None,None,None,None,None,271108e7f6573055fd80cd020b66a6ca,2026-02-05 21:00:42,None,4
34,83814,10163,Não,MII,5,None,1237,None,Criopreservado,None,Sim,None,PGT-A,2PN,None,None,None,Não,None,Fresco,ICSI,None,None,None,None,Sim,10,1,Compactando,None,None,None,None,None,None,Sim,None,Blastocisto Grau 5,A,A,None,None,None,None,None,None,None,None,None,None,None,None,dba946befe60e9b2ee1e384d8c5f33fb,2026-02-05 21:00:42,None,5
35,83815,10163,Não,MII,6,None,1237,None,Descartado,None,None,None,None,NF,None,None,None,Não,None,Fresco,ICSI,None,None,None,None,Não,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,ed879851b50a005f660a285abdf1ec72,2026-02-05 21:00:42,None,6
36,83816,10163,Não,MII,7,None,1237,None,Criopreservado,None,Sim,None,PGT-A,2PN,None,None,None,Não,None,Fresco,ICSI,None,None,None,None,Sim,10,1,Simétricos,None,None,None,None,None,None,Sim,None,Blastocisto Grau 5,A,A,None,None,None,None,None,None,None,None,None,None,None,None,cc75f7d13352a40cb9481eb30a492373,2026-02-05 21:00:42,None,7
37,83817,10163,Não,MII,8,None,1237,None,Descartado,None,None,None,None,2PN,None,None,None,Não,None,Fresco,ICSI,None,None,None,None,Sim,4,2,Simétricos,None,None,None,None,None,None,Não,None,None,None,None,Não,None,None,None,None,Não,None,None,None,None,None,None,2de729b1fa057489e06ae5c4db093e73,2026-02-05 21:00:42,None,8
38,83818,10163,Não,GV,None,None,None,None,Descartado,None,None,None,None,None,None,None,None,Não,None,Fresco,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,5390abeb89ba0c6f2f8ed5cd2024ba84,2026-02-05 21:00:42,None,9
39,83819,10163,Não,GV,None,None,None,None,Descartado,None,None,None,None,None,None,None,None,Não,None,Fresco,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,5546b5c7557aebea5f42b4a02d2207c4,2026-02-05 21:00:42,None,10
40,85253,10309,Não,MII,None,None,1237,None,Criopreservado,None,Sim,None,PGT-A,2PN,None,None,None,Não,None,Descongelado,ICSI,None,None,None,None,Sim,11,1,Simétricos,None,None,None,None,None,None,Sim,None,Blastocisto Grau 5,A,A,None,None,None,None,None,None,None,None,None,None,None,None,c26088e988e281f9154e7a89b6e8d79f,2026-02-05 21:00:42,None,1
41,85254,10309,Não,MII,None,None,1237,None,Criopreservado,None,Sim,None,PGT-A,2PN,None,None,None,Não,None,Descongelado,ICSI,None,None,None,None,Sim,8,1,Simétricos,None,None,None,None,None,None,Sim,None,Blastocisto Grau 5,B,B,None,None,None,None,None,None,None,None,None,None,None,None,bd6c6a608edce465d180a0f1b148af3a,2026-02-05 21:00:42,None,2
42,85255,10309,Não,MII,None,None,1237,None,Criopreservado,None,Sim,None,PGT-A,2PN,None,None,None,Não,None,Descongelado,ICSI,None,None,None,None,Sim,7,1,Simétricos,None,None,None,None,None,None,Sim,None,Blastocisto Grau 5,A,B,None,None,None,None,None,None,None,None,None,None,None,None,b66b4ce9ae4e9609b0b9addf06df5631,2026-02-05 21:00:42,None,3
43,85256,10309,Não,MII,None,None,1237,None,Criopreservado,None,Sim,None,PGT-A,2PN,None,None,None,Não,None,Descongelado,ICSI,None,None,None,None,Sim,9,1,Simétricos,None,None,None,None,None,None,Sim,None,Blastocisto Grau 5,B,C,None,None,None,None,None,None,None,None,None,None,None,None,edc9c3003d9306d89f4718ef2166cc3e,2026-02-05 21:00:42,None,4
44,85257,10309,Não,MII,None,None,1237,None,Criopreservado,None,Sim,None,PGT-A,2PN,None,None,None,Não,None,Descongelado,ICSI,None,None,None,None,Sim,10,1,Simétricos,None,None,None,None,None,None,Sim,None,Blastocisto Grau 5,A,A,None,None,None,None,None,None,None,None,None,None,None,None,e22c4a4562430f5fd743597bd0ac9ca2,2026-02-05 21:00:42,None,5
45,85258,10309,Não,MII,None,None,1237,None,Descartado,None,None,None,None,2PN,None,None,None,Não,None,Descongelado,ICSI,None,None,None,None,Sim,8,1,Simétricos,None,None,None,None,None,None,Não,None,None,None,None,Não,None,None,None,None,Não,None,None,None,None,None,None,b7568c14e06e13e36959dea18319bfd7,2026-02-05 21:00:42,None,6
46,85259,10309,Não,DEG,None,None,None,None,Descartado,None,None,None,None,None,None,None,None,Não,None,Descongelado,ICSI,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,a1348085576391abf2461a799ac92751,2026-02-05 21:00:42,None,7
47,85260,10309,Não,DEG,None,None,None,None,Descartado,None,None,None,None,None,None,None,None,Não,None,Descongelado,ICSI,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,c6bfcf7b29f3bd80f3db5919489f2b3d,2026-02-05 21:00:42,None,8

### 3. Tratamentos

In [36]:
print("=== TRATAMENTOS DATA ===")
tratamentos_data = results['tratamentos']
print(f"Records: {len(tratamentos_data)}")
if not tratamentos_data.empty:
    display(tratamentos_data)
else:
    print("No tratamentos data found.")

=== TRATAMENTOS DATA ===
Records: 10

,id,prontuario,idade_esposa,idade_marido,paciente_tratamento,tentativa,data_procedimento,hora_procedimento,tipo_procedimento,motivo_congelamento,tipo_inducao,protocolo,tipo_ciclo_congelado,tipo_preparo_endometrial,num_congelados,num_transferir,origem_ovulo,status_ovulo,prontuario_doadora,origem_espermatozoide,fonte_espermatozoide,status_espermatozoide,origem_material,material_heterologo,utero_substituicao,prontuario_genitores,prontuario_uter_substituicao,doacao_ovulos,destino_doacao_ovulos,prontuario_receptora,complemento_receptora,doacao_embrioes,era,emma,alice,matrice_lab,imunohistoquimica,outros_biopsia,consentimento,financeiro,embryoscope,pgt,era_auxiliar,recomendacao_transferencia,resultado_era,emma_resultado,alice_resultado,picsi,hatching_od,hatching_oe,medicacao_parental,peso_paciente,altura_paciente,fumante_paciente,data_dum,peso_conjuge,altura_conjuge,fumante_conjuge,fator_infertilidade1,fator_infertilidade2,fator_infertilidade3,fsh_exame,foliculos_antrais,data_histeroscopia,data_inicio_inducao,dias_inducao_preparo,paciente_inducao,ropa,data_inicio_agonista,gnrh,fsh_agonista,lh_agonista,outros_medicamentos,gonal,menogon,menopur,pergoveris,elonva,serofene_clomid_indux,luveris,puregon,letrozole,fostimon,merional,rekovelle,descricao_outras_medicacoes,dose_total_fsh,dose_total_lh,dose_total_fsh_lh,coorte_e2,coorte_aco,coorte_progesterona,coq10,hormonal_combinado,coorte_testosterona,agonista_coorte,coorte_antagonista,coorte_dhea,utilizado_hcg,motivo_cancelamento_hcg,data_hcg,horario_planejado_hcg,horario_real_hcg,ovidrel,gonapeptyl,dose_gonapeptyl,outras_complicacoes_hcg,dose_outras_complicacoes,lupron,outros_hcg,descricao_outros_hcg,data_inicio_progesterona,p4_inicio_progesterona,estradiol_fase_lutea,progesterona_fase_lutea,progesterona_oral,progesterona_vaginal,progesterona_injetavel,combinacao_oral_vaginal,nenhuma_progesterona,hcg_progesterona,data_congelamento,metodo_descongelamento,valor_palheta,manter_excedentes,observacoes_descongelamento,dia_transferencia,data_transferencia,medida_endometrio,padrao_endometrio,p4_transferencia,motivo_nao_transferir,motivo_cancelamento_tratamento,ligacao_enfermagem,beta_valor,beta_valor2,data_ultrassom1,data_ultrassom2,num_sacos_gestacionais,tsh,data_ultrassom1_contato,descricao_ultrassom1,bcf_embrião1_status,bcf_embrião1_fonte,data_ultrassom2_contato,descricao_ultrassom2,data_ultrassom3_contato,descricao_ultrassom3,resultado_tratamento,analise_genetica,resultado_analise_genetica,motivo_perda_aborto,data_nascimento_bebes,obstetra,nome_bebe1,sexo_bebe1,peso_bebe1,altura_bebe1,idade_gestacional_bebe1,via_parto_bebe1,viabilidade_bebe1,anomalias_bebe1,nome_bebe2,sexo_bebe2,peso_bebe2,altura_bebe2,idade_gestacional_bebe2,via_parto_bebe2,viabilidade_bebe2,anomalias_bebe2,nome_bebe3,sexo_bebe3,peso_bebe3,altura_bebe3,idade_gestacional_bebe3,via_parto_bebe3,viabilidade_bebe3,anomalias_bebe3,nome_bebe4,sexo_bebe4,peso_bebe4,altura_bebe4,idade_gestacional_bebe4,via_parto_bebe4,viabilidade_bebe4,anomalias_bebe4,observacoes_bebes,observacoes_gerais,usuario_responsavel,responsavel_informacoes,hash,extraction_timestamp,bmi,previous_et,previous_et_od,unidade
0,12953,516203,44,48,esposa,None,2022-03-16,None,Ciclo de Congelados,None,None,None,Continuação de Ciclo,Hormonal,None,None,None,None,NaN,None,None,None,None,None,Não,NaN,NaN,None,None,NaN,None,None,None,None,None,None,None,None,None,None,None,Não,Não,None,None,Não,Não,None,None,None,None,64.0,1.70,Não,2022-02-18,NaN,NaN,None,Inexplicado,Outros,None,None,None,None,2022-02-25,None,None,None,None,Nenhum,Nenhum,Nenhum,Nenhum,None,None,None,None,None,None,None,None,None,None,None,None,Primogyna,None,None,None,None,None,None,None,None,None,None,None,None,Não utilizado,None,None,None,None,None,None,None,None,None,None,None,None,11/03/2022,None,None,None,None,1,None,None,None,None,2022-02-21,None,P1,Sim,None,5,NaT,"8,4 II",Trilaminar,None,None,None,None,"233,3","664,3",None,None,1,None,None,None,None,None,None,None,None,None,Gestação Clínica,Não,None,None,None,None,None,None,None,0,None,0,None,None,None,None,None,0,None,0,None,None,None,None,None,0,None,0,None,<NA>,<NA>,<NA>,<NA>,0,<NA>,0,<NA>,<NA>,None,None,2962,209,24b812b73b440db42493df230243c973,2025-07-21 21:38:38,22.15,8,0,7
1,12897,516203,44,48,esposa,None,2022-02-16,None,Ciclo a Fresco FIV,None,Terceira via,None,None,Hormonal,None,None,Heterólogo,Criopreservado,NaN,Homólogo,Sêmen,Fresco,None,None,None,NaN,NaN,Não,None,NaN,None,None,None,None,None,None,None,None,None,None,None,PGT-A,None,None,None,None,None,None,None,None,None,64.0,1.70,Não,NaT,87.0,1.85,Não,Inexplicado,Outros,None,None,None,None,NaT,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,Não utilizado,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,1,None,NaT,None,None,None,None,No transfer,NaT,None,None,None,Congelamento total,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,No transfer,Não,None,None,None,None,None,None,None,0,None,0,None,None,None,None,None,0,None,0,None,None,None,None,None,0,None,0,None,<NA>,<NA>,<NA>,<NA>,0,<NA>,0,<NA>,<NA>,None,DESONGELOU 08 ÓVULOS \r\nVAI REALIZAR PGTA - RECEPTORA.,4520,209,22c8903c076abe56bc583ec099e8d36c,2025-07-21 21:38:38,22.15,8,0,7
2,12744,516203,44,48,esposa,None,NaT,None,Ciclo a Fresco FIV,None,Terceira via,None,None,None,None,None,Heterólogo,Criopreservado,NaN,Homólogo,Sêmen,Fresco,None,None,None,NaN,NaN,Não,None,NaN,None,None,None,None,None,None,None,None,None,None,None,Não,None,None,None,None,None,None,None,Sim,None,NaN,NaN,Não,2022-01-15,NaN,NaN,None,Inexplicado,Outros,None,None,None,None,2022-01-15,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,Cancelamento,Outras complicações,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,1,None,None,None,None,NaT,None,None,None,None,5,NaT,None,Trilaminar,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,Não,None,None,None,None,None,None,None,0,None,0,None,None,None,None,None,0,None,0,None,None,None,None,None,0,None,0,None,<NA>,<NA>,<NA>,<NA>,0,<NA>,0,<NA>,<NA>,None,None,1233,209,1984082723afb9a1e9bca2c21146b680,2025-07-21 21:38:38,NaN,7,0,<NA>
3,12449,516203,44,48,esposa,None,2021-11-30,None,Ciclo a Fresco FIV,None,Duostim 2,Progesterona,None,None,None,None,Homólogo,Fresco,NaN,Homólogo,Sêmen,Fresco,None,None,None,NaN,NaN,Não,None,NaN,None,None,None,None,None,None,None,None,None,None,None,PGT-A,None,None,None,None,None,None,None,Sim,None,64.0,1.70,Não,NaT,87.0,1.85,Não,Inexplicado,Outros,None,None,None,None,2021-11-16,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,Utilizado,None,28/11/2021,None,None,None,1,"0,3",1,10.000,None,None,DUAL TRIGGER,None,None,None,None,None,None,None,None,1,None,NaT,None,None,None,None,No transfer,NaT,None,None,None,Congelamento total,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,Não,None,None,None,None,None,None,None,0,None,0,None,None,None,None,None,0,None,0,None,None,None,None,None,0,None,0,None,<NA>,<NA>,<NA>,<NA>,0,<NA>,0,<NA>,<NA>,None,None,1533,209,749704a456c758fc5ecd4f63dbebd368,2025-07-21 21:38:38,22.15,6,0,<NA>
4,12382,516203,44,48,esposa,None,2021-11-12,None,Ciclo a Fresco FIV,None,Duostim 1,Progesterona,None,None,None,None,Homólogo,Fresco,NaN,Homólogo,Sêmen,Fresco,None,None,None,NaN,NaN,Não,None,NaN,None,None,None,None,None,None,None,None,None,None,None,PGT-A,None,None,None,None,None,None,None,Sim,None,60.0,1.65,Não,2021-10-31,75.0,1.70,Sim,Inexplicado,Outros,None,None,None,None,2021-11-02,None,None,None,None,Nenhum,rFSH,Nenhum,Nenhum,None,None,None,None,1,None,None,None,None,None,1,None,None,None,None,None,None,None,None,None,None,None,None,None,None,Utilizado,None,10/11/2021,21:30,None,None,1,"0,3",None,None,None,None,None,None,None,None,None,None,None,None,None,1,None,NaT,None,None,None,None,No transfer,NaT,None,None,None,Congelamento total,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,Não,None,None,None,None,None,None,None,0,None,0,None,None,None,None,None,0,None,0,None,None,None,None,None,0,None,0,None,<NA>,<NA>,<NA>,<NA>,0,<NA>,0,<NA>,<NA>,None,None,1235,209,d9b66af92676cccaa9a9cc68bd72fe61,2025-07-21 21:38:38,22.04,5,0,<NA>
5,10332,516203,44,47,esposa,None,2021-03-29,None,Ciclo a Fresco FIV,None,Duostim 2,Progesterona,None,None,None,None,Homólogo,Fresco,NaN,Homólogo,Sêmen,Fresco,None,None,None,NaN,NaN,Não,None,NaN,None,None,None,None,None,None,None,None,None,None,None,PGT-A,None,None,None,None,None,None,None,Sim,None,60.0,1.65,Não,NaT,70.0,1.70,Não,Inexplicado,Outros,None,None,None,None,2021-03-15,None,None,None,None,Nenhum,rFSH,Nenhum,Nenhum,None,None,1,None,1,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,Utilizado,None,27/03/2021,22:30,None,None,1,"0,3",None,None,None,None,None,None,None,None,None,None,None,None,None,1,None,NaT,None,None,None,None,No transfer,NaT,None,None,None,Congelamento total,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,Não,None,None,None,None,None,None,None,0,None,0,None,None,None,None,None,0,None,0,None,None,None,None,None,0,None,0,None,<NA>,<NA>,<NA>,<NA>,0,<NA>,0,<NA>,<NA>,None,None,1235,209,bd7003ce0a257f67dae2d72df189c8c9,2025-07-21 21:38:38,22.04,4,0,<NA>
6,10111,516203,43,47,esposa,None,2021-03-11,None,Ciclo a Fresco FIV,None,Duostim 1,Progesterona,None,None,None,None,Homólogo,Fresco,NaN,Homólogo,Sêmen,Fresco,None,None,None,NaN,NaN,Não,None,NaN,None,None,None,None,None,None,None,None,None,None,None,PGT-A,None,None,None,None,None,None,None,Sim,None,64.0,1.70,Não,2021-02-10,87.0,1.85,Não,Inexplicado,Outros,None,"11,23",8,None,2021-02-26,None,None,None,None,Nenhum,rFSH,Nenhum,Nenhum,None,None,1,None,1,None,None,None,None,None,None,None,None,None,None,None,None,1,None,None,None,None,None,None,None,Utilizado,None,09/03/2021,22:00,None,None,1,"0,3",None,None,None,None,None,None,None,None,None,None,None,None,None,1,None,NaT,None,None,None,None,No transfer,NaT,None,None,None,Congelamento total,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,Não,None,None,None,None,None,None,None,0,None,0,None,None,None,None,None,0,None,0,None,None,None,None,None,0,None,0,None,<NA>,<NA>,<NA>,<NA>,0,<NA>,0,<NA>,<NA>,None,None,1235,209,2713918b84ad26393f2ef36eefc014a4,2025-07-21 21:38:38,22.15,3,0,<NA>
7,9744,516203,43,47,None,None,2020-12-01,None,Ciclo de Congelados,None,None,None,Continuação de Ciclo,None,None,None,None,None,NaN,None,None,None,None,None,None,NaN,NaN,None,None,NaN,None,None,None,None,None,None,None,None,None,None,None,PGT-A,None,None,None,None,None,None,None,None,None,NaN,NaN,None,NaT,NaN,NaN,None,Outros,None,None,None,None,None,2020-11-15,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,Não utilizado,None,None,None,None,None,None,None,None,None,None,None,None,26/11/2020,None,None,None,None,1,None,None,None,None,NaT,None,None,None,None,5,NaT,"8,3",Trilaminar,"17,16",None,None,None,2,None,None,None,None,None,None,None,None,None,None,None,None,None,Negativo,Não,None,None,None,None,None,None,None,0,None,0,None,None,None,None,None,0,None,0,None,None,None,None,None,0,None,0,None,<NA>,<NA>,<NA>,<NA>,0,<NA>,0,<NA>,<NA>,None,None,1179,229,b89de468a42d23a636efb362c1e398cb,2025-07-21 21:38:38,NaN,2,0,<NA>
8,8890,516203,43,47,None,None,2020-07-22,None,Ciclo a Fresco FIV,None,Duostim 2,Antagonista,None,None,None,None,Homólogo,Fresco,NaN,Homólogo,Sêmen,Fresco,None,None,None,NaN,NaN,Não,None,NaN,None,None,None,None,None,None,None,None,None,None,None,PGT-A,None,None,None,None,None,Não,Não,Sim,None,62.0,1.70,Não,NaT,NaN,NaN,None,Outros,None,None,None,None,None,2020-07-09,None,None,None,None,Nenhum,rFSH,Nenhum,Nenhum,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,Utilizado,None,20/07/2020,22:00,None,1,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,NaT,None,None,None,None,No transfer,NaT,None,None,None,Congelamento total,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,Não,None,None,None,None,None,None,None,0,None,0,None,None,None,None,None,0,None,0,None,None,None,None,None,0,None,0,None,<NA>,<NA>,<NA>,<NA>,0,<NA>,0,<NA>,<NA>,None,None,1187,214,b4d0d7564fb7ce4695d8dab853923cc3,2025-07-21 21:38:38,21.45,1,0,<NA>
9,8807,516203,43,120,None,None,2020-07-04,None,Ciclo a Fresco FIV,None,Duostim 1,Antagonista,None,None,None,None,Homólogo,Fresco,NaN,Homólogo,Sêmen,Fresco,None,None,None,NaN,NaN,Não,None,NaN,None,None,None,None,None,None,None,None,None,None,None,PGT-A,None,None,None,None,None,None,None,None,None,60.0,1.65,None,2020-06-22,NaN,NaN,None,Outros,None,None,None,None,None,2020-06-24,None,None,None,None,None,None,None,None,None,None,None,1,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,Utilizado,None,02/07/2020,22:30,None,None,1,3 AMPOLAS,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,NaT,None,None,None,None,No transfer,NaT,None,None,None,Congelamento total,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,Não,None,None,None,None,None,None,None,0,None,0,None,None,None,None,None,0,None,0,None,None,None,None,None,0,None,0,None,<NA>,<NA>,<NA>,<NA>,0,<NA>,0,<NA>,<NA>,None,Dra Layza médica de Vitória,1178,229,5bb0c55d6737f9835942780fe9d549eb,2025-07-21 21:38:38,22.04,0,0,<NA>

### 4. Congelamentos Embrioes

In [37]:
print("=== CONGELAMENTOS EMBRIOES DATA ===")
congelamentos_data = results['congelamentos_embrioes']
print(f"Records: {len(congelamentos_data)}")
if not congelamentos_data.empty:
    display(congelamentos_data)
else:
    print("No congelamentos embrioes data found.")

=== CONGELAMENTOS EMBRIOES DATA ===
Records: 6

,id,CodCongelamento,Unidade,prontuario,paciente,Data,Hora,Ciclo,CicloRecongelamento,condicoes_amostra,empresa_transporte,clinica_origem,responsavel_recebimento,responsavel_recebimento_data,responsavel_armazenamento,responsavel_armazenamento_data,NEmbrioes,NPailletes,Identificacao,Tambor,Cane,Cane2,Tecnica,Ovulo,D2,D3,D4,D5,D6,D7,rack,rack2,rack3,rack4,Observacoes,BiologoResponsavel,BiologoFIV,BiologoFIV2,status_financeiro,responsavel_congelamento_d5,responsavel_checagem_d5,responsavel_congelamento_d6,responsavel_checagem_d6,responsavel_congelamento_d7,responsavel_checagem_d7,hash,extraction_timestamp
0,14416,PC_E58/22,7,516203,esposa,2022-02-21,1900-01-01 10:00:00,ED4/22,Não,None,None,None,<NA>,NaT,2731,2022-02-21,5,5,SLB16510,E8,Azul,8,Vitrificação,NaN,NaN,NaN,NaN,1.0,NaN,NaN,None,NaN,NaN,NaN,None,<NA>,Camila Cruz de Moraes,Camila Cruz de Moraes,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,c0f330e2c2959bac90dd9da6aacc7dca,2025-07-21 21:38:47
1,14318,PC_E565/21,7,516203,esposa,2021-12-05,1900-01-01 10:00:00,745/21,Não,None,None,None,<NA>,NaT,<NA>,NaT,4,4,SLB16510,E4,Branca,1,Vitrificação,NaN,NaN,NaN,NaN,1.0,NaN,NaN,None,NaN,NaN,NaN,None,<NA>,Ana Luisa Menezes Campos,Ana Luisa Menezes Campos,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,465fdbf85b3bac0040ca8fc36c62a1c2,2025-07-21 21:38:47
2,12705,PC_E127/21,7,516203,None,2021-04-03,1900-01-01 09:00:00,156/21,Não,None,None,None,<NA>,NaT,<NA>,NaT,2,2,SLB16510,E11,Verde,18,Vitrificação,NaN,NaN,NaN,NaN,1.0,NaN,1.0,None,NaN,NaN,NaN,None,<NA>,Bárbara Cristina Linhares Guimarães,Ana Luisa Menezes Campos,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,c2333ccb2f181eab503dbbfbbb02d69e,2025-07-21 21:38:47
3,12679,PC_E102/21,7,516203,None,2021-03-16,1900-01-01 15:00:00,119/21,Não,None,None,None,<NA>,NaT,<NA>,NaT,3,3,SLB16510,E11,Rosa,27,Vitrificação,NaN,NaN,NaN,NaN,1.0,1.0,NaN,None,NaN,NaN,NaN,None,<NA>,Camila Cruz de Moraes,Camila Cruz de Moraes,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,ff4bf01c03f3b638ca2638709cc6e062,2025-07-21 21:38:47
4,12262,PC_E222/20,7,516203,None,2020-07-27,1900-01-01 10:00:00,295/20,Não,None,None,None,<NA>,NaT,<NA>,NaT,1,1,SLB16510,E9,Amarelo,19,Vitrificação,NaN,NaN,NaN,NaN,1.0,NaN,NaN,None,NaN,NaN,NaN,None,<NA>,Ana Luisa Menezes Campos,Ana Luisa Menezes Campos,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,668ea2798cc4435971b0daceda7dd07b,2025-07-21 21:38:47
5,12234,PC_E194/20,7,516203,None,2020-07-09,1900-01-01 10:00:00,259/20,Não,None,None,None,<NA>,NaT,<NA>,NaT,3,3,SLB16510,E9,Azul,14,Vitrificação,NaN,NaN,NaN,NaN,1.0,1.0,NaN,None,NaN,NaN,NaN,None,<NA>,Thais Helena Soares Olintho,Ana Luisa Menezes Campos,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,135808350bab3e6549400340375cd311,2025-07-21 21:38:47

### 5. Descongelamentos Embrioes

In [38]:
print("=== DESCONGELAMENTOS EMBRIOES DATA ===")
descongelamentos_data = results['descongelamentos_embrioes']
print(f"Records: {len(descongelamentos_data)}")
if not descongelamentos_data.empty:
    display(descongelamentos_data)
else:
    print("No descongelamentos embrioes data found.")

=== DESCONGELAMENTOS EMBRIOES DATA ===
Records: 2

,id,CodDescongelamento,Unidade,prontuario,doadora,DataCongelamento,DataDescongelamento,Ciclo,Identificacao,CodCongelamento,Tambor,Cane,PailletesDescongeladas,Tecnica,Transferencia,DataTransferencia,Prateleira,Incubadora,transferidos_transferencia,cateter_transferencia,lote_transferencia,validade_transferencia,intercorrencia_transferencia,sangue_interno_transferencia,sangue_externo_transferencia,retorno_transferencia,vezes_retorno_transferencia,Transfer_D5,responsavel_transferencia,Observacoes,BiologoFIV,BiologoFIV2,hash,extraction_timestamp
0,8452,PC_148/22,None,516203,0,2022-02-21,2022-03-16,ED4/22,SLB16510,PC_E58/22,E8,Azul,1,Desvitrificação,<NA>,2022-03-16,<NA>,8,1,Guardia,138972960195,19/05/2024,None,Não,Não,Não,None,None,1075.0,None,None,None,3a34dcc1b9a2eee8faf2211fdee3c9dc,2025-07-21 21:38:51
1,6320,PC_510/20,None,516203,0,2020-07-27,2020-12-01,295/20,SLB16510,PC_E222/20,E9,Amarelo,1,Desvitrificação,<NA>,2020-12-01,<NA>,None,1,Guardia,101188370068,21/11/2022,None,Não,Não,Não,None,None,1237.0,None,None,None,522c0ecf1a2a00bcec37064023490c24,2025-07-21 21:38:51

### 6. Embrioes Congelados

In [39]:
print("=== EMBRIOES CONGELADOS DATA ===")
embrioes_congelados_data = results['embrioes_congelados']
print(f"Records: {len(embrioes_congelados_data)}")
if not embrioes_congelados_data.empty:
    display(embrioes_congelados_data)
    # display(embrioes_congelados_data[embrioes_congelados_data['id_descongelamento']!=0])
else:
    print("No embrioes congelados data found.")

=== EMBRIOES CONGELADOS DATA ===
Records: 18

,id,id_oocito,id_congelamento,id_descongelamento,prontuario,pailletes,pailletes_id,cores,embriao,doado,lote,celulas,qualidade,qualidade_recongelamento,comentarios,comentarios_descongelamento,ah,dia2,maturidade,dia2_2,dia2_3,dia3,dia3_2,dia3_3,dia4,dia4_2,dia4_3,dia4_4,gd,gd2,gd3,dia5,dia5_2,dia5_3,dia5_4,dia6,dia6_2,dia6_3,dia6_4,dia7,dia7_2,dia7_3,dia7_4,clivou_d2,clivou_d3,clivou_d4,clivou_d5,clivou_d6,clivou_d7,transferidos,pgd,resultado_pgd,colapso,pgd_congelamento,resultado_pgd_congelamento,mito_teste_pgd_congelamento,dia_congelamento,score_maia,tanque_amostra,caneca_amostra,rack_amostra,observacao,destino,hash,extraction_timestamp
0,37353,85256,14416,0,516203,#4,None,<NA>,4,None,None,None,Blastocisto Grau V - B - C,<NA>,Col. - Ejaculado,None,None,None,MII,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,<NA>,None,None,None,None,None,Descartado,None,None,None,Sim,Alterado,None,D5,None,None,None,None,None,<NA>,8160d723a66c1e8b7177fbe57a052aee,2025-07-21 21:38:57
1,37352,85255,14416,0,516203,#3,None,<NA>,3,None,None,None,Blastocisto Grau V - A - B,<NA>,Col. - Ejaculado,None,None,None,MII,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,<NA>,None,None,None,None,None,Descartado,None,None,None,Sim,Alterado,None,D5,None,None,None,None,None,<NA>,efeb21d4a5032853aed6b1afe83b17e5,2025-07-21 21:38:57
2,37349,85254,14416,0,516203,#2,None,<NA>,2,None,None,None,Blastocisto Grau V - B - B,<NA>,Col. - Ejaculado,None,None,None,MII,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,<NA>,None,None,None,None,None,Descartado,None,None,None,Sim,Alterado,None,D5,None,None,None,None,None,<NA>,5166fd56edc7b3e25d7aac5a2ca7741a,2025-07-21 21:38:57
3,37348,85257,14416,0,516203,#5,None,<NA>,5,None,None,None,Blastocisto Grau V - A - A,<NA>,Col. - Ejaculado,None,None,None,MII,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,<NA>,None,None,None,None,None,None,None,None,None,Sim,Normal,None,D5,None,None,None,None,None,<NA>,827b657da3393f1fa1399472a90375b6,2025-07-21 21:38:57
4,37347,85253,14416,8452,516203,#1,None,<NA>,1,None,None,None,Blastocisto Grau V - A - A,<NA>,Col. - Ejaculado,None,Não,None,MII,None,None,None,None,None,None,None,None,None,None,None,None,None,Blastocisto Grau 5,A,A,None,None,None,None,None,None,None,None,<NA>,None,None,None,None,None,Transferido,Não,None,None,Sim,Normal,None,D5,None,None,None,None,None,<NA>,6728ba838bf740f8d01d50edcb3d90f4,2025-07-21 21:38:57
5,37000,83816,14318,0,516203,#7,None,<NA>,7,None,None,None,Blastocisto Grau V - A - A,<NA>,Col. - Ejaculado,None,None,None,MII,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,<NA>,None,None,None,None,None,Descartado,None,None,None,Sim,Alterado,None,D5,None,None,None,None,None,<NA>,dbc71da02211a1a928b76a0791bacdaf,2025-07-21 21:38:57
6,36999,83814,14318,0,516203,#5,None,<NA>,5,None,None,None,Blastocisto Grau V - A - A,<NA>,Col. - Ejaculado,None,None,None,MII,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,<NA>,None,None,None,None,None,Descartado,None,None,None,Sim,Alterado,None,D5,None,None,None,None,None,<NA>,6aaa333e20e1b5ad628c2d991a7bc63d,2025-07-21 21:38:57
7,36998,83812,14318,0,516203,#3,None,<NA>,3,None,None,None,Blastocisto Grau V - A - B,<NA>,Col. - Ejaculado,None,None,None,MII,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,<NA>,None,None,None,None,None,Descartado,None,None,None,Sim,Alterado,None,D5,None,None,None,None,None,<NA>,cbbd1c1648606b89571193809ba2417e,2025-07-21 21:38:57
8,36997,83810,14318,0,516203,#1,None,<NA>,1,None,None,None,Blastocisto Grau V - B - C,<NA>,Col. - Ejaculado,None,None,None,MII,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,<NA>,None,None,None,None,None,Descartado,None,None,None,Sim,Alterado,None,D5,None,None,None,None,None,<NA>,0d6d9dbd595d7a2752ec56cc7df18416,2025-07-21 21:38:57
9,34114,0,12705,0,516203,#4,None,<NA>,4,None,None,None,Blastocisto Grau V - C - B,<NA>,Col. - Ejaculado,None,None,None,MII,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,<NA>,None,None,None,None,None,Descartado,None,None,None,Sim,Alterado,None,D7,None,None,None,None,None,<NA>,e1818e7aa5b9a7ea037e136fdf5fe753,2025-07-21 21:38:57
10,34099,74948,12705,0,516203,#1,None,<NA>,1,None,None,None,Blastocisto Grau V - A - B,<NA>,Col. - Ejaculado,None,None,None,MII,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,<NA>,None,None,None,None,None,Descartado,None,None,None,Sim,Alterado,None,D5,None,None,None,None,None,<NA>,f3b06e52cee84fdb8733230dac6b0f7c,2025-07-21 21:38:57
11,34031,0,12679,0,516203,#5,None,<NA>,5,None,None,None,Blastocisto Grau V - B - C,<NA>,Col. - Ejaculado,None,None,None,MII,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,<NA>,None,None,None,None,None,Descartado,None,None,None,Sim,Alterado,None,None,None,None,None,None,None,<NA>,e3bef15a2a16faa4f795caf245e1526b,2025-07-21 21:38:57
12,34030,0,12679,0,516203,#1,None,<NA>,1,None,None,None,Blastocisto Grau V - B - C,<NA>,Col. - Ejaculado,None,None,None,MII,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,<NA>,None,None,None,None,None,Descartado,None,None,None,Sim,Alterado,None,None,None,None,None,None,None,<NA>,8ebdf6ffda2c1cea4597c46c800ba325,2025-07-21 21:38:57
13,34018,74461,12679,0,516203,#4,None,<NA>,4,None,None,None,Blastocisto Grau V - A - B,<NA>,Col. - Ejaculado,None,None,None,MII,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,<NA>,None,None,None,None,None,Descartado,None,None,None,Sim,Alterado,None,None,None,None,None,None,None,<NA>,91120b8ff28e0842535e7b6a3610e289,2025-07-21 21:38:57
14,32564,69105,12262,6320,516203,#5,None,<NA>,5,None,None,None,Blastocisto Grau V - A - A,<NA>,Col. - Ejaculado,None,Não,None,MII,None,None,None,None,None,None,None,None,None,None,None,None,None,Blastocisto Grau 5,A,A,None,None,None,None,None,None,None,None,<NA>,None,None,None,None,None,Transferido,Não,None,None,Sim,Normal,None,None,None,None,None,None,None,<NA>,e8e999713f19818ebe777ec960810e2d,2025-07-21 21:38:57
15,32485,0,12234,0,516203,#3,None,<NA>,3,None,None,None,Blastocisto Grau V - A - B,<NA>,Col. - Ejaculado,None,None,None,MII,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,<NA>,None,None,None,None,None,Descartado,None,None,None,Sim,Alterado,None,None,None,None,None,None,None,<NA>,9fc9d8c93bbeb7e4d599aa81b10f3fd7,2025-07-21 21:38:57
16,32484,68714,12234,0,516203,#4,None,<NA>,2,None,None,None,Blastocisto Grau V - A - A,<NA>,Col. - Ejaculado,None,None,None,MII,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,<NA>,None,None,None,None,None,Descartado,None,None,None,Sim,Alterado,None,None,None,None,None,None,None,<NA>,d3a6c7609a8f5358f570b3c5092c71a5,2025-07-21 21:38:57
17,32483,68711,12234,0,516203,#1,None,<NA>,1,None,None,None,Blastocisto Grau V - A - A,<NA>,Col. - Ejaculado,None,None,None,MII,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,<NA>,None,None,None,None,None,Descartado,None,None,None,Sim,Alterado,None,None,None,None,None,None,None,<NA>,0adaa324b5255c571cddc6b810bc24f9,2025-07-21 21:38:57

### 7. Clinisys Embrioes

In [40]:
print("=== CLINISYS EMBRIOES DATA ===")
clinisys_embrioes_data = results['clinisys_embrioes']
print(f"Records: {len(clinisys_embrioes_data)}")
if not clinisys_embrioes_data.empty:
    display(clinisys_embrioes_data.head(30))
else:
    print("No clinisys embrioes data found.")

=== CLINISYS EMBRIOES DATA ===
Records: 48

,oocito_id,oocito_id_micromanipulacao,oocito_TCD,oocito_embryo_number,oocito_OrigemOocito,oocito_ResultadoPGD,oocito_ResultadoPGDDetalhes,micro_numero_caso,micro_prontuario,micro_Data_DL,micro_data_procedimento,micro_oocitos,micro_recepcao_ovulos,micro_CicloDoadora,trat1_id,trat1_tentativa,trat1_idade_esposa,trat1_idade_marido,trat1_prontuario_doadora,trat1_tipo_procedimento,trat1_data_inicio_inducao,trat1_motivo_nao_transferir,trat1_data_transferencia,trat1_resultado_tratamento,trat1_fator_infertilidade1,trat1_origem_ovulo,trat1_bmi,trat1_previous_et,trat1_previous_et_od,emb_cong_id,emb_cong_qualidade,emb_cong_transferidos,cong_em_id,cong_em_CodCongelamento,cong_em_Data,descong_em_id,descong_em_CodDescongelamento,descong_em_DataTransferencia,descong_em_DataCongelamento,descong_em_DataDescongelamento,trat2_id,trat2_tentativa,trat2_idade_esposa,trat2_idade_marido,trat2_prontuario_doadora,trat2_tipo_procedimento,trat2_data_inicio_inducao,trat2_motivo_nao_transferir,trat2_data_transferencia,trat2_resultado_tratamento,trat2_bmi,trat2_previous_et,trat2_previous_et_od,nome_medico,tipo_medico,flag_is_external_medical
0,85253,10309,Criopreservado,1,Descongelado,None,None,ED4/22,516203,2022-02-16,NaT,8,Sim,BOSP,12897,None,44,48,NaN,Ciclo a Fresco FIV,NaT,Congelamento total,NaT,No transfer,Inexplicado,Heterólogo,22.15,8,0,37347,Blastocisto Grau V - A - A,Transferido,14416,PC_E58/22,2022-02-21,8452,PC_148/22,2022-03-16,2022-02-21,2022-03-16,12953,None,44,48,NaN,Ciclo de Congelados,2022-02-25,None,NaT,Gestação Clínica,22.15,8,0,João Pedro Junqueira Caetano,Médico Pró-Criar,0
1,85254,10309,Criopreservado,2,Descongelado,None,None,ED4/22,516203,2022-02-16,NaT,8,Sim,BOSP,12897,None,44,48,NaN,Ciclo a Fresco FIV,NaT,Congelamento total,NaT,No transfer,Inexplicado,Heterólogo,22.15,8,0,37349,Blastocisto Grau V - B - B,Descartado,14416,PC_E58/22,2022-02-21,<NA>,None,NaT,NaT,NaT,<NA>,None,<NA>,None,NaN,None,NaT,None,NaT,None,NaN,<NA>,<NA>,João Pedro Junqueira Caetano,Médico Pró-Criar,0
2,85255,10309,Criopreservado,3,Descongelado,None,None,ED4/22,516203,2022-02-16,NaT,8,Sim,BOSP,12897,None,44,48,NaN,Ciclo a Fresco FIV,NaT,Congelamento total,NaT,No transfer,Inexplicado,Heterólogo,22.15,8,0,37352,Blastocisto Grau V - A - B,Descartado,14416,PC_E58/22,2022-02-21,<NA>,None,NaT,NaT,NaT,<NA>,None,<NA>,None,NaN,None,NaT,None,NaT,None,NaN,<NA>,<NA>,João Pedro Junqueira Caetano,Médico Pró-Criar,0
3,85256,10309,Criopreservado,4,Descongelado,None,None,ED4/22,516203,2022-02-16,NaT,8,Sim,BOSP,12897,None,44,48,NaN,Ciclo a Fresco FIV,NaT,Congelamento total,NaT,No transfer,Inexplicado,Heterólogo,22.15,8,0,37353,Blastocisto Grau V - B - C,Descartado,14416,PC_E58/22,2022-02-21,<NA>,None,NaT,NaT,NaT,<NA>,None,<NA>,None,NaN,None,NaT,None,NaT,None,NaN,<NA>,<NA>,João Pedro Junqueira Caetano,Médico Pró-Criar,0
4,85257,10309,Criopreservado,5,Descongelado,None,None,ED4/22,516203,2022-02-16,NaT,8,Sim,BOSP,12897,None,44,48,NaN,Ciclo a Fresco FIV,NaT,Congelamento total,NaT,No transfer,Inexplicado,Heterólogo,22.15,8,0,37348,Blastocisto Grau V - A - A,None,14416,PC_E58/22,2022-02-21,<NA>,None,NaT,NaT,NaT,<NA>,None,<NA>,None,NaN,None,NaT,None,NaT,None,NaN,<NA>,<NA>,João Pedro Junqueira Caetano,Médico Pró-Criar,0
5,85258,10309,Descartado,6,Descongelado,None,None,ED4/22,516203,2022-02-16,NaT,8,Sim,BOSP,12897,None,44,48,NaN,Ciclo a Fresco FIV,NaT,Congelamento total,NaT,No transfer,Inexplicado,Heterólogo,22.15,8,0,<NA>,None,None,<NA>,None,NaT,<NA>,None,NaT,NaT,NaT,<NA>,None,<NA>,None,NaN,None,NaT,None,NaT,None,NaN,<NA>,<NA>,João Pedro Junqueira Caetano,Médico Pró-Criar,0
6,85259,10309,Descartado,7,Descongelado,None,None,ED4/22,516203,2022-02-16,NaT,8,Sim,BOSP,12897,None,44,48,NaN,Ciclo a Fresco FIV,NaT,Congelamento total,NaT,No transfer,Inexplicado,Heterólogo,22.15,8,0,<NA>,None,None,<NA>,None,NaT,<NA>,None,NaT,NaT,NaT,<NA>,None,<NA>,None,NaN,None,NaT,None,NaT,None,NaN,<NA>,<NA>,João Pedro Junqueira Caetano,Médico Pró-Criar,0
7,85260,10309,Descartado,8,Descongelado,None,None,ED4/22,516203,2022-02-16,NaT,8,Sim,BOSP,12897,None,44,48,NaN,Ciclo a Fresco FIV,NaT,Congelamento total,NaT,No transfer,Inexplicado,Heterólogo,22.15,8,0,<NA>,None,None,<NA>,None,NaT,<NA>,None,NaT,NaT,NaT,<NA>,None,<NA>,None,NaN,None,NaT,None,NaT,None,NaN,<NA>,<NA>,João Pedro Junqueira Caetano,Médico Pró-Criar,0
8,83810,10163,Criopreservado,1,Fresco,None,None,745/21,516203,2021-11-30,NaT,10,Não,None,12449,None,44,48,NaN,Ciclo a Fresco FIV,2021-11-16,Congelamento total,NaT,None,Inexplicado,Homólogo,22.15,6,0,36997,Blastocisto Grau V - B - C,Descartado,14318,PC_E565/21,2021-12-05,<NA>,None,NaT,NaT,NaT,<NA>,None,<NA>,None,NaN,None,NaT,None,NaT,None,NaN,<NA>,<NA>,João Pedro Junqueira Caetano,Médico Pró-Criar,0
9,83811,10163,Descartado,2,Fresco,None,None,745/21,516203,2021-11-30,NaT,10,Não,None,12449,None,44,48,NaN,Ciclo a Fresco FIV,2021-11-16,Congelamento total,NaT,None,Inexplicado,Homólogo,22.15,6,0,<NA>,None,None,<NA>,None,NaT,<NA>,None,NaT,NaT,NaT,<NA>,None,<NA>,None,NaN,None,NaT,None,NaT,None,NaN,<NA>,<NA>,João Pedro Junqueira Caetano,Médico Pró-Criar,0
10,83812,10163,Criopreservado,3,Fresco,None,None,745/21,516203,2021-11-30,NaT,10,Não,None,12449,None,44,48,NaN,Ciclo a Fresco FIV,2021-11-16,Congelamento total,NaT,None,Inexplicado,Homólogo,22.15,6,0,36998,Blastocisto Grau V - A - B,Descartado,14318,PC_E565/21,2021-12-05,<NA>,None,NaT,NaT,NaT,<NA>,None,<NA>,None,NaN,None,NaT,None,NaT,None,NaN,<NA>,<NA>,João Pedro Junqueira Caetano,Médico Pró-Criar,0
11,83813,10163,Descartado,4,Fresco,None,None,745/21,516203,2021-11-30,NaT,10,Não,None,12449,None,44,48,NaN,Ciclo a Fresco FIV,2021-11-16,Congelamento total,NaT,None,Inexplicado,Homólogo,22.15,6,0,<NA>,None,None,<NA>,None,NaT,<NA>,None,NaT,NaT,NaT,<NA>,None,<NA>,None,NaN,None,NaT,None,NaT,None,NaN,<NA>,<NA>,João Pedro Junqueira Caetano,Médico Pró-Criar,0
12,83814,10163,Criopreservado,5,Fresco,None,None,745/21,516203,2021-11-30,NaT,10,Não,None,12449,None,44,48,NaN,Ciclo a Fresco FIV,2021-11-16,Congelamento total,NaT,None,Inexplicado,Homólogo,22.15,6,0,36999,Blastocisto Grau V - A - A,Descartado,14318,PC_E565/21,2021-12-05,<NA>,None,NaT,NaT,NaT,<NA>,None,<NA>,None,NaN,None,NaT,None,NaT,None,NaN,<NA>,<NA>,João Pedro Junqueira Caetano,Médico Pró-Criar,0
13,83815,10163,Descartado,6,Fresco,None,None,745/21,516203,2021-11-30,NaT,10,Não,None,12449,None,44,48,NaN,Ciclo a Fresco FIV,2021-11-16,Congelamento total,NaT,None,Inexplicado,Homólogo,22.15,6,0,<NA>,None,None,<NA>,None,NaT,<NA>,None,NaT,NaT,NaT,<NA>,None,<NA>,None,NaN,None,NaT,None,NaT,None,NaN,<NA>,<NA>,João Pedro Junqueira Caetano,Médico Pró-Criar,0
14,83816,10163,Criopreservado,7,Fresco,None,None,745/21,516203,2021-11-30,NaT,10,Não,None,12449,None,44,48,NaN,Ciclo a Fresco FIV,2021-11-16,Congelamento total,NaT,None,Inexplicado,Homólogo,22.15,6,0,37000,Blastocisto Grau V - A - A,Descartado,14318,PC_E565/21,2021-12-05,<NA>,None,NaT,NaT,NaT,<NA>,None,<NA>,None,NaN,None,NaT,None,NaT,None,NaN,<NA>,<NA>,João Pedro Junqueira Caetano,Médico Pró-Criar,0
15,83817,10163,Descartado,8,Fresco,None,None,745/21,516203,2021-11-30,NaT,10,Não,None,12449,None,44,48,NaN,Ciclo a Fresco FIV,2021-11-16,Congelamento total,NaT,None,Inexplicado,Homólogo,22.15,6,0,<NA>,None,None,<NA>,None,NaT,<NA>,None,NaT,NaT,NaT,<NA>,None,<NA>,None,NaN,None,NaT,None,NaT,None,NaN,<NA>,<NA>,João Pedro Junqueira Caetano,Médico Pró-Criar,0
16,83818,10163,Descartado,9,Fresco,None,None,745/21,516203,2021-11-30,NaT,10,Não,None,12449,None,44,48,NaN,Ciclo a Fresco FIV,2021-11-16,Congelamento total,NaT,None,Inexplicado,Homólogo,22.15,6,0,<NA>,None,None,<NA>,None,NaT,<NA>,None,NaT,NaT,NaT,<NA>,None,<NA>,None,NaN,None,NaT,None,NaT,None,NaN,<NA>,<NA>,João Pedro Junqueira Caetano,Médico Pró-Criar,0
17,83819,10163,Descartado,10,Fresco,None,None,745/21,516203,2021-11-30,NaT,10,Não,None,12449,None,44,48,NaN,Ciclo a Fresco FIV,2021-11-16,Congelamento total,NaT,None,Inexplicado,Homólogo,22.15,6,0,<NA>,None,None,<NA>,None,NaT,<NA>,None,NaT,NaT,NaT,<NA>,None,<NA>,None,NaN,None,NaT,None,NaT,None,NaN,<NA>,<NA>,João Pedro Junqueira Caetano,Médico Pró-Criar,0
18,83347,10116,Descartado,1,Fresco,None,None,704/21,516203,2021-11-12,NaT,5,Não,None,12382,None,44,48,NaN,Ciclo a Fresco FIV,2021-11-02,Congelamento total,NaT,None,Inexplicado,Homólogo,22.04,5,0,<NA>,None,None,<NA>,None,NaT,<NA>,None,NaT,NaT,NaT,<NA>,None,<NA>,None,NaN,None,NaT,None,NaT,None,NaN,<NA>,<NA>,João Pedro Junqueira Caetano,Médico Pró-Criar,0
19,83348,10116,Descartado,2,Fresco,None,None,704/21,516203,2021-11-12,NaT,5,Não,None,12382,None,44,48,NaN,Ciclo a Fresco FIV,2021-11-02,Congelamento total,NaT,None,Inexplicado,Homólogo,22.04,5,0,<NA>,None,None,<NA>,None,NaT,<NA>,None,NaT,NaT,NaT,<NA>,None,<NA>,None,NaN,None,NaT,None,NaT,None,NaN,<NA>,<NA>,João Pedro Junqueira Caetano,Médico Pró-Criar,0
20,83349,10116,Descartado,3,Fresco,None,None,704/21,516203,2021-11-12,NaT,5,Não,None,12382,None,44,48,NaN,Ciclo a Fresco FIV,2021-11-02,Congelamento total,NaT,None,Inexplicado,Homólogo,22.04,5,0,<NA>,None,None,<NA>,None,NaT,<NA>,None,NaT,NaT,NaT,<NA>,None,<NA>,None,NaN,None,NaT,None,NaT,None,NaN,<NA>,<NA>,João Pedro Junqueira Caetano,Médico Pró-Criar,0
21,83350,10116,Descartado,4,Fresco,None,None,704/21,516203,2021-11-12,NaT,5,Não,None,12382,None,44,48,NaN,Ciclo a Fresco FIV,2021-11-02,Congelamento total,NaT,None,Inexplicado,Homólogo,22.04,5,0,<NA>,None,None,<NA>,None,NaT,<NA>,None,NaT,NaT,NaT,<NA>,None,<NA>,None,NaN,None,NaT,None,NaT,None,NaN,<NA>,<NA>,João Pedro Junqueira Caetano,Médico Pró-Criar,0
22,83351,10116,Descartado,5,Fresco,None,None,704/21,516203,2021-11-12,NaT,5,Não,None,12382,None,44,48,NaN,Ciclo a Fresco FIV,2021-11-02,Congelamento total,NaT,None,Inexplicado,Homólogo,22.04,5,0,<NA>,None,None,<NA>,None,NaT,<NA>,None,NaT,NaT,NaT,<NA>,None,<NA>,None,NaN,None,NaT,None,NaT,None,NaN,<NA>,<NA>,João Pedro Junqueira Caetano,Médico Pró-Criar,0
23,74948,8088,Criopreservado,1,Fresco,None,None,156/21,516203,2021-03-29,NaT,5,Não,None,10332,None,44,47,NaN,Ciclo a Fresco FIV,2021-03-15,Congelamento total,NaT,None,Inexplicado,Homólogo,22.04,4,0,34099,Blastocisto Grau V - A - B,Descartado,12705,PC_E127/21,2021-04-03,<NA>,None,NaT,NaT,NaT,<NA>,None,<NA>,None,NaN,None,NaT,None,NaT,None,NaN,<NA>,<NA>,João Pedro Junqueira Caetano,Médico Pró-Criar,0
24,74949,8088,Descartado,2,Fresco,None,None,156/21,516203,2021-03-29,NaT,5,Não,None,10332,None,44,47,NaN,Ciclo a Fresco FIV,2021-03-15,Congelamento total,NaT,None,Inexplicado,Homólogo,22.04,4,0,<NA>,None,None,<NA>,None,NaT,<NA>,None,NaT,NaT,NaT,<NA>,None,<NA>,None,NaN,None,NaT,None,NaT,None,NaN,<NA>,<NA>,João Pedro Junqueira Caetano,Médico Pró-Criar,0
25,74950,8088,Descartado,3,Fresco,None,None,156/21,516203,2021-03-29,NaT,5,Não,None,10332,None,44,47,NaN,Ciclo a Fresco FIV,2021-03-15,Congelamento total,NaT,None,Inexplicado,Homólogo,22.04,4,0,<NA>,None,None,<NA>,None,NaT,<NA>,None,NaT,NaT,NaT,<NA>,None,<NA>,None,NaN,None,NaT,None,NaT,None,NaN,<NA>,<NA>,João Pedro Junqueira Caetano,Médico Pró-Criar,0
26,74951,8088,Criopreservado,4,Fresco,None,None,156/21,516203,2021-03-29,NaT,5,Não,None,10332,None,44,47,NaN,Ciclo a Fresco FIV,2021-03-15,Congelamento total,NaT,None,Inexplicado,Homólogo,22.04,4,0,<NA>,None,None,<NA>,None,NaT,<NA>,None,NaT,NaT,NaT,<NA>,None,<NA>,None,NaN,None,NaT,None,NaT,None,NaN,<NA>,<NA>,João Pedro Junqueira Caetano,Médico Pró-Criar,0
27,74952,8088,Descartado,5,Fresco,None,None,156/21,516203,2021-03-29,NaT,5,Não,None,10332,None,44,47,NaN,Ciclo a Fresco FIV,2021-03-15,Congelamento total,NaT,None,Inexplicado,Homólogo,22.04,4,0,<NA>,None,None,<NA>,None,NaT,<NA>,None,NaT,NaT,NaT,<NA>,None,<NA>,None,NaN,None,NaT,None,NaT,None,NaN,<NA>,<NA>,João Pedro Junqueira Caetano,Médico Pró-Criar,0
28,74458,8048,Criopreservado,1,Fresco,None,None,119/21,516203,2021-03-11,NaT,6,Não,None,10111,None,43,47,NaN,Ciclo a Fresco FIV,2021-02-26,Congelamento total,NaT,None,Inexplicado,Homólogo,22.15,3,0,<NA>,None,None,<NA>,None,NaT,<NA>,None,NaT,NaT,NaT,<NA>,None,<NA>,None,NaN,None,NaT,None,NaT,None,NaN,<NA>,<NA>,João Pedro Junqueira Caetano,Médico Pró-Criar,0
29,74459,8048,Descartado,2,Fresco,None,None,119/21,516203,2021-03-11,NaT,6,Não,None,10111,None,43,47,NaN,Ciclo a Fresco FIV,2021-02-26,Congelamento total,NaT,None,Inexplicado,Homólogo,22.15,3,0,<NA>,None,None,<NA>,None,NaT,<NA>,None,NaT,NaT,NaT,<NA>,None,<NA>,None,NaN,None,NaT,None,NaT,None,NaN,<NA>,<NA>,João Pedro Junqueira Caetano,Médico Pró-Criar,0

In [41]:
# clinisys_embrioes_data[clinisys_embrioes_data['oocito_id'].isin([184181])]

In [42]:
colunas = [
    'oocito_id','oocito_id_micromanipulacao', 'oocito_embryo_number', 'oocito_TCD', 
    'oocito_id_micromanipulacao', 'micro_numero_caso', 'micro_Data_DL', 'micro_data_procedimento', 
    'cong_em_id', 'cong_em_CodCongelamento', 'cong_em_Ciclo', 'cong_em_NEmbrioes', 
    'emb_cong_id', 'emb_cong_id_oocito', 'emb_cong_id_congelamento', 'emb_cong_id_descongelamento','emb_cong_embriao', 
    'descong_em_id', 'descong_em_transferidos_transferencia'	, 'descong_em_CodDescongelamento', 'descong_em_Ciclo' , 'descong_em_DataDescongelamento', 'descong_em_DataTransferencia', 
    'trat_id', 'trat_data_procedimento', 'trat_data_transferencia', 'trat_resultado_tratamento'
]

# clinisys_embrioes_data.loc[clinisys_embrioes_data['oocito_embryo_number'].isin([33,35]), colunas]

### 8. Embryoscope Embrioes

In [43]:
print("=== EMBRYOSCOPE EMBRIOES DATA ===")
embryoscope_embrioes_data = results['embryoscope_embrioes']
print(f"Records: {len(embryoscope_embrioes_data)}")
if not embryoscope_embrioes_data.empty:
    display(embryoscope_embrioes_data)
else:
    print("No embryoscope embrioes data found.")

=== EMBRYOSCOPE EMBRIOES DATA ===
Records: 36

,prontuario,patient_PatientID,patient_PatientIDx,patient_FirstName,patient_LastName,patient_DateOfBirth,patient_YearOfBirth,patient_unit_huntington,treatment_TreatmentName,embryo_EmbryoID,embryo_EmbryoDate,embryo_embryo_number,embryo_Position,embryo_InstrumentNumber,embryo_WellNumber,embryo_FertilizationTime,embryo_FertilizationMethod,embryo_EmbryoFate,embryo_Description,embryo_EmbryoDescriptionID,embryo_KIDScore,embryo_KIDDate,embryo_KIDVersion,embryo_KIDUser,embryo_Name_BlastExpandLast,embryo_Time_BlastExpandLast,embryo_Value_BlastExpandLast,embryo_Timestamp_BlastExpandLast,embryo_Name_BlastomereSize,embryo_Time_BlastomereSize,embryo_Value_BlastomereSize,embryo_Timestamp_BlastomereSize,embryo_Name_EVEN2,embryo_Time_EVEN2,embryo_Value_EVEN2,embryo_Timestamp_EVEN2,embryo_Name_EVEN4,embryo_Time_EVEN4,embryo_Value_EVEN4,embryo_Timestamp_EVEN4,embryo_Name_EVEN8,embryo_Time_EVEN8,embryo_Value_EVEN8,embryo_Timestamp_EVEN8,embryo_Name_FRAG2,embryo_Time_FRAG2,embryo_Value_FRAG2,embryo_Timestamp_FRAG2,embryo_Name_FRAG2CAT,embryo_Time_FRAG2CAT,embryo_Value_FRAG2CAT,embryo_Timestamp_FRAG2CAT,embryo_Name_FRAG4,embryo_Time_FRAG4,embryo_Value_FRAG4,embryo_Timestamp_FRAG4,embryo_Name_FRAG8,embryo_Time_FRAG8,embryo_Value_FRAG8,embryo_Timestamp_FRAG8,embryo_Name_Fragmentation,embryo_Time_Fragmentation,embryo_Value_Fragmentation,embryo_Timestamp_Fragmentation,embryo_Name_ICM,embryo_Time_ICM,embryo_Value_ICM,embryo_Timestamp_ICM,embryo_Name_Line,embryo_Time_Line,embryo_Value_Line,embryo_Timestamp_Line,embryo_Name_MN2Type,embryo_Time_MN2Type,embryo_Value_MN2Type,embryo_Timestamp_MN2Type,embryo_Name_MorphologicalGrade,embryo_Time_MorphologicalGrade,embryo_Value_MorphologicalGrade,embryo_Timestamp_MorphologicalGrade,embryo_Name_MultiNucleation,embryo_Time_MultiNucleation,embryo_Value_MultiNucleation,embryo_Timestamp_MultiNucleation,embryo_Name_Nuclei2,embryo_Time_Nuclei2,embryo_Value_Nuclei2,embryo_Timestamp_Nuclei2,embryo_Name_PN,embryo_Time_PN,embryo_Value_PN,embryo_Timestamp_PN,embryo_Name_Pulsing,embryo_Time_Pulsing,embryo_Value_Pulsing,embryo_Timestamp_Pulsing,embryo_Name_ReexpansionCount,embryo_Time_ReexpansionCount,embryo_Value_ReexpansionCount,embryo_Timestamp_ReexpansionCount,embryo_Name_Strings,embryo_Time_Strings,embryo_Value_Strings,embryo_Timestamp_Strings,embryo_Name_TE,embryo_Time_TE,embryo_Value_TE,embryo_Timestamp_TE,embryo_Name_t2,embryo_Time_t2,embryo_Value_t2,embryo_Timestamp_t2,embryo_Name_t3,embryo_Time_t3,embryo_Value_t3,embryo_Timestamp_t3,embryo_Name_t4,embryo_Time_t4,embryo_Value_t4,embryo_Timestamp_t4,embryo_Name_t5,embryo_Time_t5,embryo_Value_t5,embryo_Timestamp_t5,embryo_Name_t6,embryo_Time_t6,embryo_Value_t6,embryo_Timestamp_t6,embryo_Name_t7,embryo_Time_t7,embryo_Value_t7,embryo_Timestamp_t7,embryo_Name_t8,embryo_Time_t8,embryo_Value_t8,embryo_Timestamp_t8,embryo_Name_t9,embryo_Time_t9,embryo_Value_t9,embryo_Timestamp_t9,embryo_Name_tB,embryo_Time_tB,embryo_Value_tB,embryo_Timestamp_tB,embryo_Name_tEB,embryo_Time_tEB,embryo_Value_tEB,embryo_Timestamp_tEB,embryo_Name_tHB,embryo_Time_tHB,embryo_Value_tHB,embryo_Timestamp_tHB,embryo_Name_tM,embryo_Time_tM,embryo_Value_tM,embryo_Timestamp_tM,embryo_Name_tPB2,embryo_Time_tPB2,embryo_Value_tPB2,embryo_Timestamp_tPB2,embryo_Name_tPNa,embryo_Time_tPNa,embryo_Value_tPNa,embryo_Timestamp_tPNa,embryo_Name_tPNf,embryo_Time_tPNf,embryo_Value_tPNf,embryo_Timestamp_tPNf,embryo_Name_tSB,embryo_Time_tSB,embryo_Value_tSB,embryo_Timestamp_tSB,embryo_Name_tSC,embryo_Time_tSC,embryo_Value_tSC,embryo_Timestamp_tSC,idascore_IDAScore,idascore_IDATime,idascore_IDAVersion,AgeAtFertilization
0,516203,16510,PC10T4JJ68660_44016.3920154630,"BARBOSA, SOFIA LETAIF",PG,1977-03-03,1977,Belo Horizonte,16/02/2022,D2022.02.16_S01321_I3254_P-1,2022-02-16,1,6,3254,1,2022-02-16 10:30:00,None,Freeze,None,AH1,9.8,2022-03-15,KIDScoreD5 v3.1,TAYNARA,None,NaN,None,None,BlastomereSize,26.0,Uneven,2022.02.17 12:29:40,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,Fragmentation,26.0,5,2022.02.17 12:29:40,ICM,89.5,A,2022.02.20 03:59:23,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,MultiNucleation,26.0,0,2022.02.17 12:29:40,None,NaN,None,None,PN,16.1,2,2022.02.17 02:34:14,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,TE,89.5,A,2022.02.20 03:59:23,t2,21.7,44609.3435896528,2022.02.17 08:14:46,t3,32.0,44609.7706915046,2022.02.17 18:29:47,t4,32.5,44609.7915307176,2022.02.17 18:59:48,t5,42.2,44610.1944331597,2022.02.18 04:39:59,None,NaN,None,None,None,NaN,None,None,t8,44.0,44610.2708449769,2022.02.18 06:30:01,None,NaN,None,None,tB,89.5,44612.1662439815,2022.02.20 03:59:23,tEB,96.0,44612.4375129282,2022.02.20 10:30:01,None,NaN,None,None,tM,78.8,44611.7210757176,2022.02.19 17:18:20,tPB2,3.0,44608.5630564005,2022.02.16 13:30:48,tPNa,5.0,44608.6458248148,2022.02.16 15:29:59,tPNf,19.6,44609.2529854861,2022.02.17 06:04:17,tSB,82.1,44611.8601915162,2022.02.19 20:38:40,tSC,77.3,44611.6584784259,2022.02.19 15:48:12,None,None,None,44.96
1,516203,16510,PC10T4JJ68660_44016.3920154630,"BARBOSA, SOFIA LETAIF",PG,1977-03-03,1977,Belo Horizonte,16/02/2022,D2022.02.16_S01321_I3254_P-2,2022-02-16,2,6,3254,2,2022-02-16 10:30:00,None,Freeze,None,AH2,NA,2022-03-15,KIDScoreD5 v3.1,TAYNARA,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,None,None,44.96
2,516203,16510,PC10T4JJ68660_44016.3920154630,"BARBOSA, SOFIA LETAIF",PG,1977-03-03,1977,Belo Horizonte,16/02/2022,D2022.02.16_S01321_I3254_P-3,2022-02-16,3,6,3254,3,2022-02-16 10:30:00,None,Freeze,None,AH3,NA,2022-03-15,KIDScoreD5 v3.1,TAYNARA,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,None,None,44.96
3,516203,16510,PC10T4JJ68660_44016.3920154630,"BARBOSA, SOFIA LETAIF",PG,1977-03-03,1977,Belo Horizonte,16/02/2022,D2022.02.16_S01321_I3254_P-4,2022-02-16,4,6,3254,4,2022-02-16 10:30:00,None,Freeze,None,AH4,NA,2022-03-15,KIDScoreD5 v3.1,TAYNARA,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,None,None,44.96
4,516203,16510,PC10T4JJ68660_44016.3920154630,"BARBOSA, SOFIA LETAIF",PG,1977-03-03,1977,Belo Horizonte,16/02/2022,D2022.02.16_S01321_I3254_P-5,2022-02-16,5,6,3254,5,2022-02-16 10:30:00,None,Freeze,None,AH5,9,2022-03-15,KIDScoreD5 v3.1,TAYNARA,None,NaN,None,None,BlastomereSize,32.3,Uneven,2022.02.17 18:50:03,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,Fragmentation,32.3,5,2022.02.17 18:50:03,ICM,97.2,A,2022.02.20 11:40:22,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,MultiNucleation,32.3,0,2022.02.17 18:50:03,None,NaN,None,None,PN,16.4,2,2022.02.17 02:54:29,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,TE,97.2,A,2022.02.20 11:40:22,t2,25.2,44609.4860508102,2022.02.17 11:39:54,t3,35.0,44609.8959045139,2022.02.17 21:30:06,t4,35.5,44609.9167435417,2022.02.17 22:00:06,t5,47.4,44610.412934456,2022.02.18 09:54:37,None,NaN,None,None,None,NaN,None,None,t8,53.1,44610.6492767245,2022.02.18 15:34:57,None,NaN,None,None,tB,97.2,44612.4863769676,2022.02.20 11:40:22,tEB,99.2,44612.5706838542,2022.02.20 13:41:47,None,NaN,None,None,tM,83.5,44611.9160106366,2022.02.19 21:59:03,tPB2,3.8,44608.5939121759,2022.02.16 14:15:14,tPNa,4.8,44608.639052581,2022.02.16 15:20:14,tPNf,23.0,44609.395742338,2022.02.17 09:29:52,tSB,89.0,44612.1455497917,2022.02.20 03:29:35,tSC,73.8,44611.5125843403,2022.02.19 12:18:07,None,None,None,44.96
5,516203,16510,PC10T4JJ68660_44016.3920154630,"BARBOSA, SOFIA LETAIF",PG,1977-03-03,1977,Belo Horizonte,16/02/2022,D2022.02.16_S01321_I3254_P-6,2022-02-16,6,6,3254,6,2022-02-16 10:30:00,None,Avoid,None,AH6,NA,2022-03-15,KIDScoreD5 v3.1,TAYNARA,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,None,None,44.96
6,516203,16510,PC10T4JJ68660_44016.3920154630,"BARBOSA, SOFIA LETAIF",PG,1977-03-03,1977,Belo Horizonte,30/11/2021,D2021.11.30_S01219_I3254_P-6,2021-11-30,6,1,3254,6,2021-11-30 11:00:00,None,Avoid,None,AG6,NA,2021-12-14,KIDScoreD5 v3.1,CAMILA,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,None,None,44.74
7,516203,16510,PC10T4JJ68660_44016.3920154630,"BARBOSA, SOFIA LETAIF",PG,1977-03-03,1977,Belo Horizonte,30/11/2021,D2021.11.30_S01219_I3254_P-3,2021-11-30,3,1,3254,3,2021-11-30 11:00:00,None,Freeze,None,AG3,5.9,2021-12-14,KIDScoreD5 v3.1,CAMILA,None,NaN,None,None,BlastomereSize,33.4,Even,2021.12.01 20:25:18,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,Fragmentation,33.4,5,2021.12.01 20:25:18,ICM,119.3,A,2021.12.05 10:15:14,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,MultiNucleation,33.4,0,2021.12.01 20:25:18,None,NaN,None,None,PN,14.1,2,2021.12.01 01:06:56,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,TE,119.3,B,2021.12.05 10:15:14,t2,24.3,44531.4692760648,2021.12.01 11:15:45,t3,36.3,44531.9727472222,2021.12.01 23:20:45,t4,36.8,44531.9930514468,2021.12.01 23:49:59,t5,50.4,44532.5600261806,2021.12.02 13:26:26,None,NaN,None,None,None,NaN,None,None,t8,55.2,44532.7571267708,2021.12.02 18:10:15,None,NaN,None,None,tB,110.5,44535.0617058449,2021.12.05 01:28:51,None,NaN,None,None,None,NaN,None,None,tM,78.4,44533.7238332755,2021.12.03 17:22:19,tPB2,2.9,44530.5774793981,2021.11.30 13:51:34,tPNa,7.0,44530.7488859143,2021.11.30 17:58:23,tPNf,21.5,44531.3540531019,2021.12.01 08:29:50,tSB,96.7,44534.4883109838,2021.12.04 11:43:10,tSC,66.1,44533.210449213,2021.12.03 05:03:02,None,None,None,44.74
8,516203,16510,PC10T4JJ68660_44016.3920154630,"BARBOSA, SOFIA LETAIF",PG,1977-03-03,1977,Belo Horizonte,30/11/2021,D2021.11.30_S01219_I3254_P-8,2021-11-30,8,1,3254,8,2021-11-30 11:00:00,None,Avoid,None,AG8,NA,2021-12-14,KIDScoreD5 v3.1,CAMILA,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,None,None,44.74
9,516203,16510,PC10T4JJ68660_44016.3920154630,"BARBOSA, SOFIA LETAIF",PG,1977-03-03,1977,Belo Horizonte,30/11/2021,D2021.11.30_S01219_I3254_P-4,2021-11-30,4,1,3254,4,2021-11-30 11:00:00,None,Avoid,None,AG4,NA,2021-12-14,KIDScoreD5 v3.1,CAMILA,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,None,None,44.74
10,516203,16510,PC10T4JJ68660_44016.3920154630,"BARBOSA, SOFIA LETAIF",PG,1977-03-03,1977,Belo Horizonte,30/11/2021,D2021.11.30_S01219_I3254_P-5,2021-11-30,5,1,3254,5,2021-11-30 11:00:00,None,Freeze,None,AG5,9.2,2021-12-14,KIDScoreD5 v3.1,CAMILA,None,NaN,None,None,BlastomereSize,33.6,Uneven,2021.12.01 20:35:11,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,Fragmentation,33.6,5,2021.12.01 20:35:11,ICM,102.2,A,2021.12.04 17:13:33,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,MultiNucleation,33.6,0,2021.12.01 20:35:11,None,NaN,None,None,PN,18.1,2,2021.12.01 05:05:08,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,TE,102.2,A,2021.12.04 17:13:33,t2,25.2,44531.5085020718,2021.12.01 12:12:14,None,NaN,None,None,t4,35.5,44531.9389896644,2021.12.01 22:32:08,t5,49.3,44532.5127526505,2021.12.02 12:18:21,None,NaN,None,None,None,NaN,None,None,t8,51.3,44532.5948297801,2021.12.02 14:16:33,None,NaN,None,None,tB,94.4,44534.392782581,2021.12.04 09:25:36,None,NaN,None,None,None,NaN,None,None,tM,75.0,44533.5851064005,2021.12.03 14:02:33,tPB2,2.5,44530.5643393519,2021.11.30 13:32:38,tPNa,6.0,44530.7092924421,2021.11.30 17:01:22,tPNf,22.2,44531.385020787,2021.12.01 09:14:25,tSB,87.3,44534.0940995718,2021.12.04 02:15:30,tSC,67.7,44533.2781984028,2021.12.03 06:40:36,None,None,None,44.74
11,516203,16510,PC10T4JJ68660_44016.3920154630,"BARBOSA, SOFIA LETAIF",PG,1977-03-03,1977,Belo Horizonte,30/11/2021,D2021.11.30_S01219_I3254_P-1,2021-11-30,1,1,3254,1,2021-11-30 11:00:00,None,Freeze,None,AG1,5.3,2021-12-14,KIDScoreD5 v3.1,CAMILA,None,NaN,None,None,BlastomereSize,32.1,Even,2021.12.01 19:07:12,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,Fragmentation,32.9,5,2021.12.01 19:55:56,ICM,103.6,B,2021.12.04 18:35:53,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,MultiNucleation,32.9,1,2021.12.01 19:55:56,None,NaN,None,None,PN,16.2,2,2021.12.01 03:10:36,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,TE,103.6,C,2021.12.04 18:35:53,t2,25.4,44531.5150994097,2021.12.01 12:21:44,t3,37.0,44531.9997327431,2021.12.01 23:59:36,t4,38.0,44532.0403460995,2021.12.02 00:58:05,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,t8,51.3,44532.5946557986,2021.12.02 14:16:18,None,NaN,None,None,tB,103.6,44534.7749195833,2021.12.04 18:35:53,None,NaN,None,None,None,NaN,None,None,tM,87.6,44534.1071454167,2021.12.04 02:34:17,tPB2,3.0,44530.5840054861,2021.11.30 14:00:58,tPNa,6.0,44530.7091182755,2021.11.30 17:01:07,tPNf,22.7,44531.4051531944,2021.12.01 09:43:25,tSB,100.0,44534.6243956134,2021.12.04 14:59:07,tSC,74.6,44533.5651011227,2021.12.03 13:33:44,None,None,None,44.74
12,516203,16510,PC10T4JJ68660_44016.3920154630,"BARBOSA, SOFIA LETAIF",PG,1977-03-03,1977,Belo Horizonte,30/11/2021,D2021.11.30_S01219_I3254_P-7,2021-11-30,7,1,3254,7,2021-11-30 11:00:00,None,Freeze,None,AG7,9.2,2021-12-14,KIDScoreD5 v3.1,CAMILA,None,NaN,None,None,BlastomereSize,34.1,Even,2021.12.01 21:04:33,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,Fragmentation,34.1,5,2021.12.01 21:04:33,ICM,105.7,A,2021.12.04 20:40:06,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,MultiNucleation,34.1,0,2021.12.01 21:04:33,None,NaN,None,None,PN,17.5,2,2021.12.01 04:27:10,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,TE,105.7,A,2021.12.04 20:40:06,t2,26.8,44531.5763396065,2021.12.01 13:49:55,t3,38.1,44532.0473767708,2021.12.02 01:08:13,t4,38.3,44532.0541450231,2021.12.02 01:17:58,t5,51.1,44532.5881521412,2021.12.02 14:06:56,None,NaN,None,None,None,NaN,None,None,t8,53.7,44532.6964082523,2021.12.02 16:42:49,None,NaN,None,None,tB,95.9,44534.4545652083,2021.12.04 10:54:34,None,NaN,None,None,None,NaN,None,None,tM,75.5,44533.6050245023,2021.12.03 14:31:14,tPB2,4.4,44530.6424715856,2021.11.30 15:25:09,tPNa,6.2,44530.7159932407,2021.11.30 17:11:01,tPNf,24.3,44531.4694507755,2021.12.01 11:16:00,tSB,90.6,44534.2330054398,2021.12.04 05:35:31,tSC,69.5,44533.3530432639,2021.12.03 08:28:22,None,None,None,44.74
13,516203,16510,PC10T4JJ68660_44016.3920154630,"BARBOSA, SOFIA LETAIF",PG,1977-03-03,1977,Belo Horizonte,30/11/2021,D2021.11.30_S01219_I3254_P-2,2021-11-30,2,1,3254,2,2021-11-30 11:00:00,None,Avoid,None,AG2,NA,2021-12-14,KIDScoreD5 v3.1,CAMILA,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,None,None,44.74

In [44]:
# embryoscope_embrioes_data.loc[embryoscope_embrioes_data['embryo_FertilizationTime'].isin(['2024-01-15 12:45:00'])].sort_values(by='embryo_embryo_number')

### 9. Embryoscope Clinisys Combined

In [45]:
print("=== EMBRYOSCOPE CLINISYS COMBINED DATA ===")
combined_data = results['embryoscope_clinisys_combined']
print(f"Records: {len(combined_data)}")
if not combined_data.empty:
    display(combined_data.head(20))
else:
    print("No embryoscope clinisys combined data found.")

=== EMBRYOSCOPE CLINISYS COMBINED DATA ===
Records: 48

,oocito_id,oocito_id_micromanipulacao,oocito_TCD,oocito_embryo_number,oocito_OrigemOocito,oocito_ResultadoPGD,oocito_ResultadoPGDDetalhes,micro_numero_caso,micro_prontuario,micro_Data_DL,micro_data_procedimento,micro_oocitos,micro_recepcao_ovulos,micro_CicloDoadora,trat1_id,trat1_tentativa,trat1_idade_esposa,trat1_idade_marido,trat1_prontuario_doadora,trat1_tipo_procedimento,trat1_data_inicio_inducao,trat1_motivo_nao_transferir,trat1_data_transferencia,trat1_resultado_tratamento,trat1_fator_infertilidade1,trat1_origem_ovulo,trat1_bmi,trat1_previous_et,trat1_previous_et_od,emb_cong_id,emb_cong_qualidade,emb_cong_transferidos,cong_em_id,cong_em_CodCongelamento,cong_em_Data,descong_em_id,descong_em_CodDescongelamento,descong_em_DataTransferencia,descong_em_DataCongelamento,descong_em_DataDescongelamento,trat2_id,trat2_tentativa,trat2_idade_esposa,trat2_idade_marido,trat2_prontuario_doadora,trat2_tipo_procedimento,trat2_data_inicio_inducao,trat2_motivo_nao_transferir,trat2_data_transferencia,trat2_resultado_tratamento,trat2_bmi,trat2_previous_et,trat2_previous_et_od,nome_medico,tipo_medico,flag_is_external_medical,prontuario,patient_PatientID,patient_PatientIDx,patient_FirstName,patient_LastName,patient_DateOfBirth,patient_YearOfBirth,patient_unit_huntington,treatment_TreatmentName,embryo_EmbryoID,embryo_EmbryoDate,embryo_embryo_number,embryo_Position,embryo_InstrumentNumber,embryo_WellNumber,embryo_FertilizationTime,embryo_FertilizationMethod,embryo_EmbryoFate,embryo_Description,embryo_EmbryoDescriptionID,embryo_KIDScore,embryo_KIDDate,embryo_KIDVersion,embryo_KIDUser,embryo_Name_BlastExpandLast,embryo_Time_BlastExpandLast,embryo_Value_BlastExpandLast,embryo_Timestamp_BlastExpandLast,embryo_Name_BlastomereSize,embryo_Time_BlastomereSize,embryo_Value_BlastomereSize,embryo_Timestamp_BlastomereSize,embryo_Name_EVEN2,embryo_Time_EVEN2,embryo_Value_EVEN2,embryo_Timestamp_EVEN2,embryo_Name_EVEN4,embryo_Time_EVEN4,embryo_Value_EVEN4,embryo_Timestamp_EVEN4,embryo_Name_EVEN8,embryo_Time_EVEN8,embryo_Value_EVEN8,embryo_Timestamp_EVEN8,embryo_Name_FRAG2,embryo_Time_FRAG2,embryo_Value_FRAG2,embryo_Timestamp_FRAG2,embryo_Name_FRAG2CAT,embryo_Time_FRAG2CAT,embryo_Value_FRAG2CAT,embryo_Timestamp_FRAG2CAT,embryo_Name_FRAG4,embryo_Time_FRAG4,embryo_Value_FRAG4,embryo_Timestamp_FRAG4,embryo_Name_FRAG8,embryo_Time_FRAG8,embryo_Value_FRAG8,embryo_Timestamp_FRAG8,embryo_Name_Fragmentation,embryo_Time_Fragmentation,embryo_Value_Fragmentation,embryo_Timestamp_Fragmentation,embryo_Name_ICM,embryo_Time_ICM,embryo_Value_ICM,embryo_Timestamp_ICM,embryo_Name_Line,embryo_Time_Line,embryo_Value_Line,embryo_Timestamp_Line,embryo_Name_MN2Type,embryo_Time_MN2Type,embryo_Value_MN2Type,embryo_Timestamp_MN2Type,embryo_Name_MorphologicalGrade,embryo_Time_MorphologicalGrade,embryo_Value_MorphologicalGrade,embryo_Timestamp_MorphologicalGrade,embryo_Name_MultiNucleation,embryo_Time_MultiNucleation,embryo_Value_MultiNucleation,embryo_Timestamp_MultiNucleation,embryo_Name_Nuclei2,embryo_Time_Nuclei2,embryo_Value_Nuclei2,embryo_Timestamp_Nuclei2,embryo_Name_PN,embryo_Time_PN,embryo_Value_PN,embryo_Timestamp_PN,embryo_Name_Pulsing,embryo_Time_Pulsing,embryo_Value_Pulsing,embryo_Timestamp_Pulsing,embryo_Name_ReexpansionCount,embryo_Time_ReexpansionCount,embryo_Value_ReexpansionCount,embryo_Timestamp_ReexpansionCount,embryo_Name_Strings,embryo_Time_Strings,embryo_Value_Strings,embryo_Timestamp_Strings,embryo_Name_TE,embryo_Time_TE,embryo_Value_TE,embryo_Timestamp_TE,embryo_Name_t2,embryo_Time_t2,embryo_Value_t2,embryo_Timestamp_t2,embryo_Name_t3,embryo_Time_t3,embryo_Value_t3,embryo_Timestamp_t3,embryo_Name_t4,embryo_Time_t4,embryo_Value_t4,embryo_Timestamp_t4,embryo_Name_t5,embryo_Time_t5,embryo_Value_t5,embryo_Timestamp_t5,embryo_Name_t6,embryo_Time_t6,embryo_Value_t6,embryo_Timestamp_t6,embryo_Name_t7,embryo_Time_t7,embryo_Value_t7,embryo_Timestamp_t7,embryo_Name_t8,embryo_Time_t8,embryo_Value_t8,embryo_Timestamp_t8,embryo_Name_t9,embryo_Time_t9,embryo_Value_t9,embryo_Timestamp_t9,embryo_Name_tB,embryo_Time_tB,embryo_Value_tB,embryo_Timestamp_tB,embryo_Name_tEB,embryo_Time_tEB,embryo_Value_tEB,embryo_Timestamp_tEB,embryo_Name_tHB,embryo_Time_tHB,embryo_Value_tHB,embryo_Timestamp_tHB,embryo_Name_tM,embryo_Time_tM,embryo_Value_tM,embryo_Timestamp_tM,embryo_Name_tPB2,embryo_Time_tPB2,embryo_Value_tPB2,embryo_Timestamp_tPB2,embryo_Name_tPNa,embryo_Time_tPNa,embryo_Value_tPNa,embryo_Timestamp_tPNa,embryo_Name_tPNf,embryo_Time_tPNf,embryo_Value_tPNf,embryo_Timestamp_tPNf,embryo_Name_tSB,embryo_Time_tSB,embryo_Value_tSB,embryo_Timestamp_tSB,embryo_Name_tSC,embryo_Time_tSC,embryo_Value_tSC,embryo_Timestamp_tSC,idascore_IDAScore,idascore_IDATime,idascore_IDAVersion,AgeAtFertilization
0,85253,10309,Criopreservado,1,Descongelado,None,None,ED4/22,516203,2022-02-16,NaT,8,Sim,BOSP,12897,None,44,48,NaN,Ciclo a Fresco FIV,NaT,Congelamento total,NaT,No transfer,Inexplicado,Heterólogo,22.15,8,0,37347,Blastocisto Grau V - A - A,Transferido,14416,PC_E58/22,2022-02-21,8452,PC_148/22,2022-03-16,2022-02-21,2022-03-16,12953,None,44,48,NaN,Ciclo de Congelados,2022-02-25,None,NaT,Gestação Clínica,22.15,8,0,João Pedro Junqueira Caetano,Médico Pró-Criar,0,516203,16510,PC10T4JJ68660_44016.3920154630,"BARBOSA, SOFIA LETAIF",PG,1977-03-03,1977,Belo Horizonte,16/02/2022,D2022.02.16_S01321_I3254_P-1,2022-02-16,1,6,3254,1,2022-02-16 10:30:00,None,Freeze,None,AH1,9.8,2022-03-15,KIDScoreD5 v3.1,TAYNARA,None,NaN,None,None,BlastomereSize,26.0,Uneven,2022.02.17 12:29:40,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,Fragmentation,26.0,5,2022.02.17 12:29:40,ICM,89.5,A,2022.02.20 03:59:23,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,MultiNucleation,26.0,0,2022.02.17 12:29:40,None,NaN,None,None,PN,16.1,2,2022.02.17 02:34:14,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,TE,89.5,A,2022.02.20 03:59:23,t2,21.7,44609.3435896528,2022.02.17 08:14:46,t3,32.0,44609.7706915046,2022.02.17 18:29:47,t4,32.5,44609.7915307176,2022.02.17 18:59:48,t5,42.2,44610.1944331597,2022.02.18 04:39:59,None,NaN,None,None,None,NaN,None,None,t8,44.0,44610.2708449769,2022.02.18 06:30:01,None,NaN,None,None,tB,89.5,44612.1662439815,2022.02.20 03:59:23,tEB,96.0,44612.4375129282,2022.02.20 10:30:01,None,NaN,None,None,tM,78.8,44611.7210757176,2022.02.19 17:18:20,tPB2,3.0,44608.5630564005,2022.02.16 13:30:48,tPNa,5.0,44608.6458248148,2022.02.16 15:29:59,tPNf,19.6,44609.2529854861,2022.02.17 06:04:17,tSB,82.1,44611.8601915162,2022.02.19 20:38:40,tSC,77.3,44611.6584784259,2022.02.19 15:48:12,None,None,None,44.96
1,85254,10309,Criopreservado,2,Descongelado,None,None,ED4/22,516203,2022-02-16,NaT,8,Sim,BOSP,12897,None,44,48,NaN,Ciclo a Fresco FIV,NaT,Congelamento total,NaT,No transfer,Inexplicado,Heterólogo,22.15,8,0,37349,Blastocisto Grau V - B - B,Descartado,14416,PC_E58/22,2022-02-21,<NA>,None,NaT,NaT,NaT,<NA>,None,<NA>,None,NaN,None,NaT,None,NaT,None,NaN,<NA>,<NA>,João Pedro Junqueira Caetano,Médico Pró-Criar,0,516203,16510,PC10T4JJ68660_44016.3920154630,"BARBOSA, SOFIA LETAIF",PG,1977-03-03,1977,Belo Horizonte,16/02/2022,D2022.02.16_S01321_I3254_P-2,2022-02-16,2,6,3254,2,2022-02-16 10:30:00,None,Freeze,None,AH2,NA,2022-03-15,KIDScoreD5 v3.1,TAYNARA,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,None,None,44.96
2,85255,10309,Criopreservado,3,Descongelado,None,None,ED4/22,516203,2022-02-16,NaT,8,Sim,BOSP,12897,None,44,48,NaN,Ciclo a Fresco FIV,NaT,Congelamento total,NaT,No transfer,Inexplicado,Heterólogo,22.15,8,0,37352,Blastocisto Grau V - A - B,Descartado,14416,PC_E58/22,2022-02-21,<NA>,None,NaT,NaT,NaT,<NA>,None,<NA>,None,NaN,None,NaT,None,NaT,None,NaN,<NA>,<NA>,João Pedro Junqueira Caetano,Médico Pró-Criar,0,516203,16510,PC10T4JJ68660_44016.3920154630,"BARBOSA, SOFIA LETAIF",PG,1977-03-03,1977,Belo Horizonte,16/02/2022,D2022.02.16_S01321_I3254_P-3,2022-02-16,3,6,3254,3,2022-02-16 10:30:00,None,Freeze,None,AH3,NA,2022-03-15,KIDScoreD5 v3.1,TAYNARA,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,None,None,44.96
3,85256,10309,Criopreservado,4,Descongelado,None,None,ED4/22,516203,2022-02-16,NaT,8,Sim,BOSP,12897,None,44,48,NaN,Ciclo a Fresco FIV,NaT,Congelamento total,NaT,No transfer,Inexplicado,Heterólogo,22.15,8,0,37353,Blastocisto Grau V - B - C,Descartado,14416,PC_E58/22,2022-02-21,<NA>,None,NaT,NaT,NaT,<NA>,None,<NA>,None,NaN,None,NaT,None,NaT,None,NaN,<NA>,<NA>,João Pedro Junqueira Caetano,Médico Pró-Criar,0,516203,16510,PC10T4JJ68660_44016.3920154630,"BARBOSA, SOFIA LETAIF",PG,1977-03-03,1977,Belo Horizonte,16/02/2022,D2022.02.16_S01321_I3254_P-4,2022-02-16,4,6,3254,4,2022-02-16 10:30:00,None,Freeze,None,AH4,NA,2022-03-15,KIDScoreD5 v3.1,TAYNARA,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,None,None,44.96
4,85257,10309,Criopreservado,5,Descongelado,None,None,ED4/22,516203,2022-02-16,NaT,8,Sim,BOSP,12897,None,44,48,NaN,Ciclo a Fresco FIV,NaT,Congelamento total,NaT,No transfer,Inexplicado,Heterólogo,22.15,8,0,37348,Blastocisto Grau V - A - A,None,14416,PC_E58/22,2022-02-21,<NA>,None,NaT,NaT,NaT,<NA>,None,<NA>,None,NaN,None,NaT,None,NaT,None,NaN,<NA>,<NA>,João Pedro Junqueira Caetano,Médico Pró-Criar,0,516203,16510,PC10T4JJ68660_44016.3920154630,"BARBOSA, SOFIA LETAIF",PG,1977-03-03,1977,Belo Horizonte,16/02/2022,D2022.02.16_S01321_I3254_P-5,2022-02-16,5,6,3254,5,2022-02-16 10:30:00,None,Freeze,None,AH5,9,2022-03-15,KIDScoreD5 v3.1,TAYNARA,None,NaN,None,None,BlastomereSize,32.3,Uneven,2022.02.17 18:50:03,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,Fragmentation,32.3,5,2022.02.17 18:50:03,ICM,97.2,A,2022.02.20 11:40:22,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,MultiNucleation,32.3,0,2022.02.17 18:50:03,None,NaN,None,None,PN,16.4,2,2022.02.17 02:54:29,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,TE,97.2,A,2022.02.20 11:40:22,t2,25.2,44609.4860508102,2022.02.17 11:39:54,t3,35.0,44609.8959045139,2022.02.17 21:30:06,t4,35.5,44609.9167435417,2022.02.17 22:00:06,t5,47.4,44610.412934456,2022.02.18 09:54:37,None,NaN,None,None,None,NaN,None,None,t8,53.1,44610.6492767245,2022.02.18 15:34:57,None,NaN,None,None,tB,97.2,44612.4863769676,2022.02.20 11:40:22,tEB,99.2,44612.5706838542,2022.02.20 13:41:47,None,NaN,None,None,tM,83.5,44611.9160106366,2022.02.19 21:59:03,tPB2,3.8,44608.5939121759,2022.02.16 14:15:14,tPNa,4.8,44608.639052581,2022.02.16 15:20:14,tPNf,23.0,44609.395742338,2022.02.17 09:29:52,tSB,89.0,44612.1455497917,2022.02.20 03:29:35,tSC,73.8,44611.5125843403,2022.02.19 12:18:07,None,None,None,44.96
5,85258,10309,Descartado,6,Descongelado,None,None,ED4/22,516203,2022-02-16,NaT,8,Sim,BOSP,12897,None,44,48,NaN,Ciclo a Fresco FIV,NaT,Congelamento total,NaT,No transfer,Inexplicado,Heterólogo,22.15,8,0,<NA>,None,None,<NA>,None,NaT,<NA>,None,NaT,NaT,NaT,<NA>,None,<NA>,None,NaN,None,NaT,None,NaT,None,NaN,<NA>,<NA>,João Pedro Junqueira Caetano,Médico Pró-Criar,0,516203,16510,PC10T4JJ68660_44016.3920154630,"BARBOSA, SOFIA LETAIF",PG,1977-03-03,1977,Belo Horizonte,16/02/2022,D2022.02.16_S01321_I3254_P-6,2022-02-16,6,6,3254,6,2022-02-16 10:30:00,None,Avoid,None,AH6,NA,2022-03-15,KIDScoreD5 v3.1,TAYNARA,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,None,None,44.96
6,85259,10309,Descartado,7,Descongelado,None,None,ED4/22,516203,2022-02-16,NaT,8,Sim,BOSP,12897,None,44,48,NaN,Ciclo a Fresco FIV,NaT,Congelamento total,NaT,No transfer,Inexplicado,Heterólogo,22.15,8,0,<NA>,None,None,<NA>,None,NaT,<NA>,None,NaT,NaT,NaT,<NA>,None,<NA>,None,NaN,None,NaT,None,NaT,None,NaN,<NA>,<NA>,João Pedro Junqueira Caetano,Médico Pró-Criar,0,<NA>,<NA>,None,None,None,NaT,<NA>,None,None,None,NaT,<NA>,<NA>,<NA>,<NA>,NaT,None,None,None,None,None,NaT,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,None,None,NaN
7,85260,10309,Descartado,8,Descongelado,None,None,ED4/22,516203,2022-02-16,NaT,8,Sim,BOSP,12897,None,44,48,NaN,Ciclo a Fresco FIV,NaT,Congelamento total,NaT,No transfer,Inexplicado,Heterólogo,22.15,8,0,<NA>,None,None,<NA>,None,NaT,<NA>,None,NaT,NaT,NaT,<NA>,None,<NA>,None,NaN,None,NaT,None,NaT,None,NaN,<NA>,<NA>,João Pedro Junqueira Caetano,Médico Pró-Criar,0,<NA>,<NA>,None,None,None,NaT,<NA>,None,None,None,NaT,<NA>,<NA>,<NA>,<NA>,NaT,None,None,None,None,None,NaT,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,None,None,NaN
8,83810,10163,Criopreservado,1,Fresco,None,None,745/21,516203,2021-11-30,NaT,10,Não,None,12449,None,44,48,NaN,Ciclo a Fresco FIV,2021-11-16,Congelamento total,NaT,None,Inexplicado,Homólogo,22.15,6,0,36997,Blastocisto Grau V - B - C,Descartado,14318,PC_E565/21,2021-12-05,<NA>,None,NaT,NaT,NaT,<NA>,None,<NA>,None,NaN,None,NaT,None,NaT,None,NaN,<NA>,<NA>,João Pedro Junqueira Caetano,Médico Pró-Criar,0,516203,16510,PC10T4JJ68660_44016.3920154630,"BARBOSA, SOFIA LETAIF",PG,1977-03-03,1977,Belo Horizonte,30/11/2021,D2021.11.30_S01219_I3254_P-1,2021-11-30,1,1,3254,1,2021-11-30 11:00:00,None,Freeze,None,AG1,5.3,2021-12-14,KIDScoreD5 v3.1,CAMILA,None,NaN,None,None,BlastomereSize,32.1,Even,2021.12.01 19:07:12,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,Fragmentation,32.9,5,2021.12.01 19:55:56,ICM,103.6,B,2021.12.04 18:35:53,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,MultiNucleation,32.9,1,2021.12.01 19:55:56,None,NaN,None,None,PN,16.2,2,2021.12.01 03:10:36,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,TE,103.6,C,2021.12.04 18:35:53,t2,25.4,44531.5150994097,2021.12.01 12:21:44,t3,37.0,44531.9997327431,2021.12.01 23:59:36,t4,38.0,44532.0403460995,2021.12.02 00:58:05,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,t8,51.3,44532.5946557986,2021.12.02 14:16:18,None,NaN,None,None,tB,103.6,44534.7749195833,2021.12.04 18:35:53,None,NaN,None,None,None,NaN,None,None,tM,87.6,44534.1071454167,2021.12.04 02:34:17,tPB2,3.0,44530.5840054861,2021.11.30 14:00:58,tPNa,6.0,44530.7091182755,2021.11.30 17:01:07,tPNf,22.7,44531.4051531944,2021.12.01 09:43:25,tSB,100.0,44534.6243956134,2021.12.04 14:59:07,tSC,74.6,44533.5651011227,2021.12.03 13:33:44,None,None,None,44.74
9,83811,10163,Descartado,2,Fresco,None,None,745/21,516203,2021-11-30,NaT,10,Não,None,12449,None,44,48,NaN,Ciclo a Fresco FIV,2021-11-16,Congelamento total,NaT,None,Inexplicado,Homólogo,22.15,6,0,<NA>,None,None,<NA>,None,NaT,<NA>,None,NaT,NaT,NaT,<NA>,None,<NA>,None,NaN,None,NaT,None,NaT,None,NaN,<NA>,<NA>,João Pedro Junqueira Caetano,Médico Pró-Criar,0,516203,16510,PC10T4JJ68660_44016.3920154630,"BARBOSA, SOFIA LETAIF",PG,1977-03-03,1977,Belo Horizonte,30/11/2021,D2021.11.30_S01219_I3254_P-2,2021-11-30,2,1,3254,2,2021-11-30 11:00:00,None,Avoid,None,AG2,NA,2021-12-14,KIDScoreD5 v3.1,CAMILA,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,None,None,44.74

In [46]:
colunas = [
    'oocito_id','oocito_id_micromanipulacao', 'oocito_embryo_number', 'oocito_TCD', 
    'oocito_id_micromanipulacao', 'micro_numero_caso', 'micro_Data_DL', 'micro_data_procedimento', 
    'cong_em_id', 'cong_em_CodCongelamento', 'cong_em_Ciclo', 'cong_em_NEmbrioes', 
    'treatment_TreatmentName', 'embryo_EmbryoID', 'embryo_KIDScore', 'embryo_Description', 'embryo_EmbryoDescriptionID', 'embryo_embryo_number',
    'emb_cong_transferidos', 'emb_cong_id', 'emb_cong_id_oocito', 'emb_cong_id_congelamento', 'emb_cong_id_descongelamento','emb_cong_embriao', 
    'descong_em_id', 'descong_em_transferidos_transferencia'	, 'descong_em_CodDescongelamento', 'descong_em_Ciclo' , 'descong_em_DataDescongelamento', 'descong_em_DataTransferencia', 
    'trat_id', 'trat_data_procedimento', 'trat_data_transferencia', 'trat_resultado_tratamento', 'trat_tentativa'
]

# combined_data.loc[combined_data['oocito_id_micromanipulacao'].isin([21961]), colunas]
# combined_data.loc[combined_data['embryo_EmbryoDescriptionID'].isin(['AA5']), colunas] 
# combined_data.loc[:, colunas]

### 11. Planilha Embriologia FESH

In [47]:
print("=== PLANILHA EMBRIOLOGIA DATA FRESH===")
planilha_data = results['planilha_embriologia_fresh']
print(f"Records: {len(planilha_data)}")
if not planilha_data.empty:
    display(planilha_data)
else:
    print("No planilha embriologia data found.")

=== PLANILHA EMBRIOLOGIA DATA FRESH===
Records: 0
No planilha embriologia data found.

### 12. Planilha Embriologia FET

In [48]:
print("=== PLANILHA EMBRIOLOGIA DATA FET===")
planilha_data = results['planilha_embriologia_fet']
print(f"Records: {len(planilha_data)}")
if not planilha_data.empty:
    display(planilha_data)
else:
    print("No planilha embriologia data found.")

=== PLANILHA EMBRIOLOGIA DATA FET===
Records: 0
No planilha embriologia data found.

### 12b. Fresh - fet combined

In [49]:
print("=== PLANILHA EMBRIOLOGIA COMBINED===")
planilha_data = results['planilha_embriologia_combined']
print(f"Records: {len(planilha_data)}")
if not planilha_data.empty:
    display(planilha_data)
else:
    print("No planilha embriologia data found.")

=== PLANILHA EMBRIOLOGIA COMBINED===
Records: 0
No planilha embriologia data found.

### 13. Planilha Embryoscope Combined

In [50]:
print("=== PLANILHA EMBRYOSCOPE COMBINED DATA ===")
combined_planilha_data = results['planilha_embryoscope_combined']
print(f"Records: {len(combined_planilha_data)}")
if not combined_planilha_data.empty:
    display(combined_planilha_data.head(20))
else:
    print("No planilha embryoscope combined data found.")

=== PLANILHA EMBRYOSCOPE COMBINED DATA ===
Records: 48

,oocito_id,oocito_id_micromanipulacao,oocito_TCD,oocito_embryo_number,oocito_OrigemOocito,oocito_ResultadoPGD,oocito_ResultadoPGDDetalhes,micro_numero_caso,micro_prontuario,micro_Data_DL,micro_data_procedimento,micro_oocitos,micro_recepcao_ovulos,micro_CicloDoadora,trat1_id,trat1_tentativa,trat1_idade_esposa,trat1_idade_marido,trat1_prontuario_doadora,trat1_tipo_procedimento,trat1_data_inicio_inducao,trat1_motivo_nao_transferir,trat1_data_transferencia,trat1_resultado_tratamento,trat1_fator_infertilidade1,trat1_origem_ovulo,trat1_bmi,trat1_previous_et,trat1_previous_et_od,emb_cong_id,emb_cong_qualidade,emb_cong_transferidos,cong_em_id,cong_em_CodCongelamento,cong_em_Data,descong_em_id,descong_em_CodDescongelamento,descong_em_DataTransferencia,descong_em_DataCongelamento,descong_em_DataDescongelamento,trat2_id,trat2_tentativa,trat2_idade_esposa,trat2_idade_marido,trat2_prontuario_doadora,trat2_tipo_procedimento,trat2_data_inicio_inducao,trat2_motivo_nao_transferir,trat2_data_transferencia,trat2_resultado_tratamento,trat2_bmi,trat2_previous_et,trat2_previous_et_od,nome_medico,tipo_medico,flag_is_external_medical,prontuario,patient_PatientID,patient_PatientIDx,patient_FirstName,patient_LastName,patient_DateOfBirth,patient_YearOfBirth,patient_unit_huntington,treatment_TreatmentName,embryo_EmbryoID,embryo_EmbryoDate,embryo_embryo_number,embryo_Position,embryo_InstrumentNumber,embryo_WellNumber,embryo_FertilizationTime,embryo_FertilizationMethod,embryo_EmbryoFate,embryo_Description,embryo_EmbryoDescriptionID,embryo_KIDScore,embryo_KIDDate,embryo_KIDVersion,embryo_KIDUser,embryo_Name_BlastExpandLast,embryo_Time_BlastExpandLast,embryo_Value_BlastExpandLast,embryo_Timestamp_BlastExpandLast,embryo_Name_BlastomereSize,embryo_Time_BlastomereSize,embryo_Value_BlastomereSize,embryo_Timestamp_BlastomereSize,embryo_Name_EVEN2,embryo_Time_EVEN2,embryo_Value_EVEN2,embryo_Timestamp_EVEN2,embryo_Name_EVEN4,embryo_Time_EVEN4,embryo_Value_EVEN4,embryo_Timestamp_EVEN4,embryo_Name_EVEN8,embryo_Time_EVEN8,embryo_Value_EVEN8,embryo_Timestamp_EVEN8,embryo_Name_FRAG2,embryo_Time_FRAG2,embryo_Value_FRAG2,embryo_Timestamp_FRAG2,embryo_Name_FRAG2CAT,embryo_Time_FRAG2CAT,embryo_Value_FRAG2CAT,embryo_Timestamp_FRAG2CAT,embryo_Name_FRAG4,embryo_Time_FRAG4,embryo_Value_FRAG4,embryo_Timestamp_FRAG4,embryo_Name_FRAG8,embryo_Time_FRAG8,embryo_Value_FRAG8,embryo_Timestamp_FRAG8,embryo_Name_Fragmentation,embryo_Time_Fragmentation,embryo_Value_Fragmentation,embryo_Timestamp_Fragmentation,embryo_Name_ICM,embryo_Time_ICM,embryo_Value_ICM,embryo_Timestamp_ICM,embryo_Name_Line,embryo_Time_Line,embryo_Value_Line,embryo_Timestamp_Line,embryo_Name_MN2Type,embryo_Time_MN2Type,embryo_Value_MN2Type,embryo_Timestamp_MN2Type,embryo_Name_MorphologicalGrade,embryo_Time_MorphologicalGrade,embryo_Value_MorphologicalGrade,embryo_Timestamp_MorphologicalGrade,embryo_Name_MultiNucleation,embryo_Time_MultiNucleation,embryo_Value_MultiNucleation,embryo_Timestamp_MultiNucleation,embryo_Name_Nuclei2,embryo_Time_Nuclei2,embryo_Value_Nuclei2,embryo_Timestamp_Nuclei2,embryo_Name_PN,embryo_Time_PN,embryo_Value_PN,embryo_Timestamp_PN,embryo_Name_Pulsing,embryo_Time_Pulsing,embryo_Value_Pulsing,embryo_Timestamp_Pulsing,embryo_Name_ReexpansionCount,embryo_Time_ReexpansionCount,embryo_Value_ReexpansionCount,embryo_Timestamp_ReexpansionCount,embryo_Name_Strings,embryo_Time_Strings,embryo_Value_Strings,embryo_Timestamp_Strings,embryo_Name_TE,embryo_Time_TE,embryo_Value_TE,embryo_Timestamp_TE,embryo_Name_t2,embryo_Time_t2,embryo_Value_t2,embryo_Timestamp_t2,embryo_Name_t3,embryo_Time_t3,embryo_Value_t3,embryo_Timestamp_t3,embryo_Name_t4,embryo_Time_t4,embryo_Value_t4,embryo_Timestamp_t4,embryo_Name_t5,embryo_Time_t5,embryo_Value_t5,embryo_Timestamp_t5,embryo_Name_t6,embryo_Time_t6,embryo_Value_t6,embryo_Timestamp_t6,embryo_Name_t7,embryo_Time_t7,embryo_Value_t7,embryo_Timestamp_t7,embryo_Name_t8,embryo_Time_t8,embryo_Value_t8,embryo_Timestamp_t8,embryo_Name_t9,embryo_Time_t9,embryo_Value_t9,embryo_Timestamp_t9,embryo_Name_tB,embryo_Time_tB,embryo_Value_tB,embryo_Timestamp_tB,embryo_Name_tEB,embryo_Time_tEB,embryo_Value_tEB,embryo_Timestamp_tEB,embryo_Name_tHB,embryo_Time_tHB,embryo_Value_tHB,embryo_Timestamp_tHB,embryo_Name_tM,embryo_Time_tM,embryo_Value_tM,embryo_Timestamp_tM,embryo_Name_tPB2,embryo_Time_tPB2,embryo_Value_tPB2,embryo_Timestamp_tPB2,embryo_Name_tPNa,embryo_Time_tPNa,embryo_Value_tPNa,embryo_Timestamp_tPNa,embryo_Name_tPNf,embryo_Time_tPNf,embryo_Value_tPNf,embryo_Timestamp_tPNf,embryo_Name_tSB,embryo_Time_tSB,embryo_Value_tSB,embryo_Timestamp_tSB,embryo_Name_tSC,embryo_Time_tSC,embryo_Value_tSC,embryo_Timestamp_tSC,idascore_IDAScore,idascore_IDATime,idascore_IDAVersion,AgeAtFertilization,join_step,matched_src_row_id,matched_planilha_prontuario,matched_planilha_transfer_date,merged_numero_de_nascidos,incubadora_padronizada,outcome,outcome_type,chart_or_pin,date_of_delivery,gestational_age_at_delivery,type_of_delivery,baby_1_weight,baby_2_weight,baby_3_weight,complications_of_pregnancy_specify,number_of_fet_after_originally_frozen,n_of_biopsied,n_of_normal,number_of_embryos_transferred,year,unidade,join_step_1,fresh_fator_1,fresh_incubadora,fresh_data_crio,fresh_tipo_1,fresh_tipo_de_inseminacao,fresh_tipo_biopsia,fresh_altura,fresh_peso,fresh_data_de_nasc,fresh_idade_espermatozoide,fresh_origem,fresh_tipo,fresh_opu,fresh_total_de_mii,fresh_qtd_blasto,fresh_qtd_blasto_tq_a_e_b,fresh_no_biopsiados,fresh_qtd_analisados,fresh_qtd_normais,fresh_dia_cryo,fresh_file_name,fresh_sheet_name,fet_data_crio,fet_resultado,fet_tipo_resultado,fet_tipo_1,fet_tipo_de_tratamento,fet_tipo_de_fet,fet_tipo_biopsia,fet_tipo_da_doacao,fet_idade_mulher,fet_idade_do_cong_de_embriao,fet_preparo_para_transferencia,fet_dia_cryo,fet_no_da_transfer_1a_2a_3a,fet_dia_et,fet_no_et,fet_gravidez_bioquimica,fet_gravidez_clinica,fet_file_name,fet_sheet_name
0,85260,10309,Descartado,8,Descongelado,None,None,ED4/22,516203,2022-02-16,NaT,8,Sim,BOSP,12897,None,44,48,NaN,Ciclo a Fresco FIV,NaT,Congelamento total,NaT,No transfer,Inexplicado,Heterólogo,22.15,8,0,<NA>,None,None,<NA>,None,NaT,<NA>,None,NaT,NaT,NaT,<NA>,None,<NA>,None,NaN,None,NaT,None,NaT,None,NaN,<NA>,<NA>,João Pedro Junqueira Caetano,Médico Pró-Criar,0,<NA>,<NA>,None,None,None,NaT,<NA>,None,None,None,NaT,<NA>,<NA>,<NA>,<NA>,NaT,None,None,None,None,None,NaT,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,None,None,NaN,<NA>,<NA>,<NA>,NaT,<NA>,None,None,None,None,NaT,None,None,None,None,None,None,None,None,None,None,<NA>,None,<NA>,None,None,NaT,None,None,None,NaN,<NA>,NaT,None,None,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,None,None,NaT,None,None,None,None,None,None,None,<NA>,NaN,None,None,None,<NA>,<NA>,None,None,None,None
1,85259,10309,Descartado,7,Descongelado,None,None,ED4/22,516203,2022-02-16,NaT,8,Sim,BOSP,12897,None,44,48,NaN,Ciclo a Fresco FIV,NaT,Congelamento total,NaT,No transfer,Inexplicado,Heterólogo,22.15,8,0,<NA>,None,None,<NA>,None,NaT,<NA>,None,NaT,NaT,NaT,<NA>,None,<NA>,None,NaN,None,NaT,None,NaT,None,NaN,<NA>,<NA>,João Pedro Junqueira Caetano,Médico Pró-Criar,0,<NA>,<NA>,None,None,None,NaT,<NA>,None,None,None,NaT,<NA>,<NA>,<NA>,<NA>,NaT,None,None,None,None,None,NaT,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,None,None,NaN,<NA>,<NA>,<NA>,NaT,<NA>,None,None,None,None,NaT,None,None,None,None,None,None,None,None,None,None,<NA>,None,<NA>,None,None,NaT,None,None,None,NaN,<NA>,NaT,None,None,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,None,None,NaT,None,None,None,None,None,None,None,<NA>,NaN,None,None,None,<NA>,<NA>,None,None,None,None
2,85258,10309,Descartado,6,Descongelado,None,None,ED4/22,516203,2022-02-16,NaT,8,Sim,BOSP,12897,None,44,48,NaN,Ciclo a Fresco FIV,NaT,Congelamento total,NaT,No transfer,Inexplicado,Heterólogo,22.15,8,0,<NA>,None,None,<NA>,None,NaT,<NA>,None,NaT,NaT,NaT,<NA>,None,<NA>,None,NaN,None,NaT,None,NaT,None,NaN,<NA>,<NA>,João Pedro Junqueira Caetano,Médico Pró-Criar,0,516203,16510,PC10T4JJ68660_44016.3920154630,"BARBOSA, SOFIA LETAIF",PG,1977-03-03,1977,Belo Horizonte,16/02/2022,D2022.02.16_S01321_I3254_P-6,2022-02-16,6,6,3254,6,2022-02-16 10:30:00,None,Avoid,None,AH6,NA,2022-03-15,KIDScoreD5 v3.1,TAYNARA,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,None,None,44.96,<NA>,<NA>,<NA>,NaT,<NA>,None,None,None,None,NaT,None,None,None,None,None,None,None,None,None,None,<NA>,None,<NA>,None,None,NaT,None,None,None,NaN,<NA>,NaT,None,None,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,None,None,NaT,None,None,None,None,None,None,None,<NA>,NaN,None,None,None,<NA>,<NA>,None,None,None,None
3,85257,10309,Criopreservado,5,Descongelado,None,None,ED4/22,516203,2022-02-16,NaT,8,Sim,BOSP,12897,None,44,48,NaN,Ciclo a Fresco FIV,NaT,Congelamento total,NaT,No transfer,Inexplicado,Heterólogo,22.15,8,0,37348,Blastocisto Grau V - A - A,None,14416,PC_E58/22,2022-02-21,<NA>,None,NaT,NaT,NaT,<NA>,None,<NA>,None,NaN,None,NaT,None,NaT,None,NaN,<NA>,<NA>,João Pedro Junqueira Caetano,Médico Pró-Criar,0,516203,16510,PC10T4JJ68660_44016.3920154630,"BARBOSA, SOFIA LETAIF",PG,1977-03-03,1977,Belo Horizonte,16/02/2022,D2022.02.16_S01321_I3254_P-5,2022-02-16,5,6,3254,5,2022-02-16 10:30:00,None,Freeze,None,AH5,9,2022-03-15,KIDScoreD5 v3.1,TAYNARA,None,NaN,None,None,BlastomereSize,32.3,Uneven,2022.02.17 18:50:03,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,Fragmentation,32.3,5,2022.02.17 18:50:03,ICM,97.2,A,2022.02.20 11:40:22,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,MultiNucleation,32.3,0,2022.02.17 18:50:03,None,NaN,None,None,PN,16.4,2,2022.02.17 02:54:29,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,TE,97.2,A,2022.02.20 11:40:22,t2,25.2,44609.4860508102,2022.02.17 11:39:54,t3,35.0,44609.8959045139,2022.02.17 21:30:06,t4,35.5,44609.9167435417,2022.02.17 22:00:06,t5,47.4,44610.412934456,2022.02.18 09:54:37,None,NaN,None,None,None,NaN,None,None,t8,53.1,44610.6492767245,2022.02.18 15:34:57,None,NaN,None,None,tB,97.2,44612.4863769676,2022.02.20 11:40:22,tEB,99.2,44612.5706838542,2022.02.20 13:41:47,None,NaN,None,None,tM,83.5,44611.9160106366,2022.02.19 21:59:03,tPB2,3.8,44608.5939121759,2022.02.16 14:15:14,tPNa,4.8,44608.639052581,2022.02.16 15:20:14,tPNf,23.0,44609.395742338,2022.02.17 09:29:52,tSB,89.0,44612.1455497917,2022.02.20 03:29:35,tSC,73.8,44611.5125843403,2022.02.19 12:18:07,None,None,None,44.96,<NA>,<NA>,<NA>,NaT,<NA>,None,None,None,None,NaT,None,None,None,None,None,None,None,None,None,None,<NA>,None,<NA>,None,None,NaT,None,None,None,NaN,<NA>,NaT,None,None,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,None,None,NaT,None,None,None,None,None,None,None,<NA>,NaN,None,None,None,<NA>,<NA>,None,None,None,None
4,85256,10309,Criopreservado,4,Descongelado,None,None,ED4/22,516203,2022-02-16,NaT,8,Sim,BOSP,12897,None,44,48,NaN,Ciclo a Fresco FIV,NaT,Congelamento total,NaT,No transfer,Inexplicado,Heterólogo,22.15,8,0,37353,Blastocisto Grau V - B - C,Descartado,14416,PC_E58/22,2022-02-21,<NA>,None,NaT,NaT,NaT,<NA>,None,<NA>,None,NaN,None,NaT,None,NaT,None,NaN,<NA>,<NA>,João Pedro Junqueira Caetano,Médico Pró-Criar,0,516203,16510,PC10T4JJ68660_44016.3920154630,"BARBOSA, SOFIA LETAIF",PG,1977-03-03,1977,Belo Horizonte,16/02/2022,D2022.02.16_S01321_I3254_P-4,2022-02-16,4,6,3254,4,2022-02-16 10:30:00,None,Freeze,None,AH4,NA,2022-03-15,KIDScoreD5 v3.1,TAYNARA,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,None,None,44.96,<NA>,<NA>,<NA>,NaT,<NA>,None,None,None,None,NaT,None,None,None,None,None,None,None,None,None,None,<NA>,None,<NA>,None,None,NaT,None,None,None,NaN,<NA>,NaT,None,None,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,None,None,NaT,None,None,None,None,None,None,None,<NA>,NaN,None,None,None,<NA>,<NA>,None,None,None,None
5,85255,10309,Criopreservado,3,Descongelado,None,None,ED4/22,516203,2022-02-16,NaT,8,Sim,BOSP,12897,None,44,48,NaN,Ciclo a Fresco FIV,NaT,Congelamento total,NaT,No transfer,Inexplicado,Heterólogo,22.15,8,0,37352,Blastocisto Grau V - A - B,Descartado,14416,PC_E58/22,2022-02-21,<NA>,None,NaT,NaT,NaT,<NA>,None,<NA>,None,NaN,None,NaT,None,NaT,None,NaN,<NA>,<NA>,João Pedro Junqueira Caetano,Médico Pró-Criar,0,516203,16510,PC10T4JJ68660_44016.3920154630,"BARBOSA, SOFIA LETAIF",PG,1977-03-03,1977,Belo Horizonte,16/02/2022,D2022.02.16_S01321_I3254_P-3,2022-02-16,3,6,3254,3,2022-02-16 10:30:00,None,Freeze,None,AH3,NA,2022-03-15,KIDScoreD5 v3.1,TAYNARA,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,None,None,44.96,<NA>,<NA>,<NA>,NaT,<NA>,None,None,None,None,NaT,None,None,None,None,None,None,None,None,None,None,<NA>,None,<NA>,None,None,NaT,None,None,None,NaN,<NA>,NaT,None,None,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,None,None,NaT,None,None,None,None,None,None,None,<NA>,NaN,None,None,None,<NA>,<NA>,None,None,None,None
6,85254,10309,Criopreservado,2,Descongelado,None,None,ED4/22,516203,2022-02-16,NaT,8,Sim,BOSP,12897,None,44,48,NaN,Ciclo a Fresco FIV,NaT,Congelamento total,NaT,No transfer,Inexplicado,Heterólogo,22.15,8,0,37349,Blastocisto Grau V - B - B,Descartado,14416,PC_E58/22,2022-02-21,<NA>,None,NaT,NaT,NaT,<NA>,None,<NA>,None,NaN,None,NaT,None,NaT,None,NaN,<NA>,<NA>,João Pedro Junqueira Caetano,Médico Pró-Criar,0,516203,16510,PC10T4JJ68660_44016.3920154630,"BARBOSA, SOFIA LETAIF",PG,1977-03-03,1977,Belo Horizonte,16/02/2022,D2022.02.16_S01321_I3254_P-2,2022-02-16,2,6,3254,2,2022-02-16 10:30:00,None,Freeze,None,AH2,NA,2022-03-15,KIDScoreD5 v3.1,TAYNARA,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,NaN,None,None,None,None,None,44.96,<NA>,<NA>,<NA>,NaT,<NA>,None,None,None,None,NaT,None,None,None,None,None,None,None,None,None,None,<NA>,None,<NA>,None,None,NaT,None,None,None,NaN,<NA>,NaT,None,None,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,None,None,NaT,None,None,None,None,None,None,None,<NA>,NaN,None,None,None,<NA>,<NA>,None,None,None,None

In [51]:
cols = [
    'oocito_id', 'oocito_id_micromanipulacao', 'oocito_TCD', 'oocito_embryo_number', 
    'oocito_OrigemOocito', 'micro_numero_caso', 'micro_prontuario', 'micro_Data_DL', 
    'micro_data_procedimento', 'micro_oocitos', 'trat1_id', 'trat1_tentativa', 
    'trat1_tipo_procedimento', 'trat1_data_inicio_inducao', 'trat1_motivo_nao_transferir', 
    'trat1_data_transferencia', 'trat1_resultado_tratamento', 'trat1_fator_infertilidade1', 
    'trat1_origem_ovulo', 'trat1_bmi', 'trat1_previous_et', 'trat1_previous_et_od', 
    'emb_cong_id', 'emb_cong_qualidade', 'emb_cong_transferidos', 'cong_em_id', 
    'cong_em_CodCongelamento', 'cong_em_Data', 'descong_em_id', 'descong_em_CodDescongelamento', 
    'descong_em_DataTransferencia', 'descong_em_DataCongelamento', 'descong_em_DataDescongelamento', 
    'trat2_id', 'trat2_tentativa', 'trat2_tipo_procedimento', 'trat2_data_inicio_inducao', 
    'trat2_motivo_nao_transferir', 'trat2_data_transferencia', 'trat2_resultado_tratamento', 
    'trat2_bmi', 'trat2_previous_et', 'trat2_previous_et_od', 'prontuario', 
    'patient_PatientID', 'patient_PatientIDx', 'join_step', 'matched_planilha_prontuario', 
    'matched_planilha_transfer_date', 'merged_numero_de_nascidos', 'incubadora_padronizada', 
    'outcome', 'outcome_type', 'chart_or_pin', 'date_of_delivery', 
    'gestational_age_at_delivery', 'type_of_delivery', 'baby_1_weight', 'baby_2_weight', 
    'baby_3_weight', 'complications_of_pregnancy_specify', 'number_of_fet_after_originally_frozen', 
    'n_of_biopsied', 'n_of_normal', 'number_of_embryos_transferred', 'year', 'unidade', 
    'fresh_fator_1', 'fresh_incubadora', 'fresh_data_crio', 'fresh_tipo_1', 
    'fresh_tipo_de_inseminacao', 'fresh_tipo_biopsia', 'fresh_altura', 'fresh_peso', 
    'fresh_data_de_nasc', 'fresh_idade_espermatozoide', 'fresh_origem', 'fresh_tipo', 
    'fresh_opu', 'fresh_total_de_mii', 'fresh_qtd_blasto', 'fresh_qtd_blasto_tq_a_e_b', 
    'fresh_no_biopsiados', 'fresh_qtd_analisados', 'fresh_qtd_normais', 'fresh_dia_cryo', 
    'fresh_file_name', 'fresh_sheet_name', 'fet_data_crio', 'fet_resultado', 
    'fet_tipo_resultado', 'fet_tipo_1', 'fet_tipo_de_tratamento', 'fet_tipo_de_fet', 
    'fet_tipo_biopsia', 'fet_tipo_da_doacao', 'fet_idade_mulher', 'fet_idade_do_cong_de_embriao', 
    'fet_preparo_para_transferencia', 'fet_dia_cryo', 'fet_no_da_transfer_1a_2a_3a', 
    'fet_dia_et', 'fet_no_et', 'fet_gravidez_bioquimica', 'fet_gravidez_clinica', 
    'fet_file_name', 'fet_sheet_name'
]

combined_planilha_data[cols]

,oocito_id,oocito_id_micromanipulacao,oocito_TCD,oocito_embryo_number,oocito_OrigemOocito,micro_numero_caso,micro_prontuario,micro_Data_DL,micro_data_procedimento,micro_oocitos,trat1_id,trat1_tentativa,trat1_tipo_procedimento,trat1_data_inicio_inducao,trat1_motivo_nao_transferir,trat1_data_transferencia,trat1_resultado_tratamento,trat1_fator_infertilidade1,trat1_origem_ovulo,trat1_bmi,trat1_previous_et,trat1_previous_et_od,emb_cong_id,emb_cong_qualidade,emb_cong_transferidos,cong_em_id,cong_em_CodCongelamento,cong_em_Data,descong_em_id,descong_em_CodDescongelamento,descong_em_DataTransferencia,descong_em_DataCongelamento,descong_em_DataDescongelamento,trat2_id,trat2_tentativa,trat2_tipo_procedimento,trat2_data_inicio_inducao,trat2_motivo_nao_transferir,trat2_data_transferencia,trat2_resultado_tratamento,trat2_bmi,trat2_previous_et,trat2_previous_et_od,prontuario,patient_PatientID,patient_PatientIDx,join_step,matched_planilha_prontuario,matched_planilha_transfer_date,merged_numero_de_nascidos,incubadora_padronizada,outcome,outcome_type,chart_or_pin,date_of_delivery,gestational_age_at_delivery,type_of_delivery,baby_1_weight,baby_2_weight,baby_3_weight,complications_of_pregnancy_specify,number_of_fet_after_originally_frozen,n_of_biopsied,n_of_normal,number_of_embryos_transferred,year,unidade,fresh_fator_1,fresh_incubadora,fresh_data_crio,fresh_tipo_1,fresh_tipo_de_inseminacao,fresh_tipo_biopsia,fresh_altura,fresh_peso,fresh_data_de_nasc,fresh_idade_espermatozoide,fresh_origem,fresh_tipo,fresh_opu,fresh_total_de_mii,fresh_qtd_blasto,fresh_qtd_blasto_tq_a_e_b,fresh_no_biopsiados,fresh_qtd_analisados,fresh_qtd_normais,fresh_dia_cryo,fresh_file_name,fresh_sheet_name,fet_data_crio,fet_resultado,fet_tipo_resultado,fet_tipo_1,fet_tipo_de_tratamento,fet_tipo_de_fet,fet_tipo_biopsia,fet_tipo_da_doacao,fet_idade_mulher,fet_idade_do_cong_de_embriao,fet_preparo_para_transferencia,fet_dia_cryo,fet_no_da_transfer_1a_2a_3a,fet_dia_et,fet_no_et,fet_gravidez_bioquimica,fet_gravidez_clinica,fet_file_name,fet_sheet_name
0,85260,10309,Descartado,8,Descongelado,ED4/22,516203,2022-02-16,NaT,8,12897,None,Ciclo a Fresco FIV,NaT,Congelamento total,NaT,No transfer,Inexplicado,Heterólogo,22.15,8,0,<NA>,None,None,<NA>,None,NaT,<NA>,None,NaT,NaT,NaT,<NA>,None,None,NaT,None,NaT,None,NaN,<NA>,<NA>,<NA>,<NA>,None,<NA>,<NA>,NaT,<NA>,None,None,None,None,NaT,None,None,None,None,None,None,None,None,None,None,<NA>,None,None,None,NaT,None,None,None,NaN,<NA>,NaT,None,None,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,None,None,NaT,None,None,None,None,None,None,None,<NA>,NaN,None,None,None,<NA>,<NA>,None,None,None,None
1,85259,10309,Descartado,7,Descongelado,ED4/22,516203,2022-02-16,NaT,8,12897,None,Ciclo a Fresco FIV,NaT,Congelamento total,NaT,No transfer,Inexplicado,Heterólogo,22.15,8,0,<NA>,None,None,<NA>,None,NaT,<NA>,None,NaT,NaT,NaT,<NA>,None,None,NaT,None,NaT,None,NaN,<NA>,<NA>,<NA>,<NA>,None,<NA>,<NA>,NaT,<NA>,None,None,None,None,NaT,None,None,None,None,None,None,None,None,None,None,<NA>,None,None,None,NaT,None,None,None,NaN,<NA>,NaT,None,None,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,None,None,NaT,None,None,None,None,None,None,None,<NA>,NaN,None,None,None,<NA>,<NA>,None,None,None,None
2,85258,10309,Descartado,6,Descongelado,ED4/22,516203,2022-02-16,NaT,8,12897,None,Ciclo a Fresco FIV,NaT,Congelamento total,NaT,No transfer,Inexplicado,Heterólogo,22.15,8,0,<NA>,None,None,<NA>,None,NaT,<NA>,None,NaT,NaT,NaT,<NA>,None,None,NaT,None,NaT,None,NaN,<NA>,<NA>,516203,16510,PC10T4JJ68660_44016.3920154630,<NA>,<NA>,NaT,<NA>,None,None,None,None,NaT,None,None,None,None,None,None,None,None,None,None,<NA>,None,None,None,NaT,None,None,None,NaN,<NA>,NaT,None,None,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,None,None,NaT,None,None,None,None,None,None,None,<NA>,NaN,None,None,None,<NA>,<NA>,None,None,None,None
3,85257,10309,Criopreservado,5,Descongelado,ED4/22,516203,2022-02-16,NaT,8,12897,None,Ciclo a Fresco FIV,NaT,Congelamento total,NaT,No transfer,Inexplicado,Heterólogo,22.15,8,0,37348,Blastocisto Grau V - A - A,None,14416,PC_E58/22,2022-02-21,<NA>,None,NaT,NaT,NaT,<NA>,None,None,NaT,None,NaT,None,NaN,<NA>,<NA>,516203,16510,PC10T4JJ68660_44016.3920154630,<NA>,<NA>,NaT,<NA>,None,None,None,None,NaT,None,None,None,None,None,None,None,None,None,None,<NA>,None,None,None,NaT,None,None,None,NaN,<NA>,NaT,None,None,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,None,None,NaT,None,None,None,None,None,None,None,<NA>,NaN,None,None,None,<NA>,<NA>,None,None,None,None
4,85256,10309,Criopreservado,4,Descongelado,ED4/22,516203,2022-02-16,NaT,8,12897,None,Ciclo a Fresco FIV,NaT,Congelamento total,NaT,No transfer,Inexplicado,Heterólogo,22.15,8,0,37353,Blastocisto Grau V - B - C,Descartado,14416,PC_E58/22,2022-02-21,<NA>,None,NaT,NaT,NaT,<NA>,None,None,NaT,None,NaT,None,NaN,<NA>,<NA>,516203,16510,PC10T4JJ68660_44016.3920154630,<NA>,<NA>,NaT,<NA>,None,None,None,None,NaT,None,None,None,None,None,None,None,None,None,None,<NA>,None,None,None,NaT,None,None,None,NaN,<NA>,NaT,None,None,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,None,None,NaT,None,None,None,None,None,None,None,<NA>,NaN,None,None,None,<NA>,<NA>,None,None,None,None
5,85255,10309,Criopreservado,3,Descongelado,ED4/22,516203,2022-02-16,NaT,8,12897,None,Ciclo a Fresco FIV,NaT,Congelamento total,NaT,No transfer,Inexplicado,Heterólogo,22.15,8,0,37352,Blastocisto Grau V - A - B,Descartado,14416,PC_E58/22,2022-02-21,<NA>,None,NaT,NaT,NaT,<NA>,None,None,NaT,None,NaT,None,NaN,<NA>,<NA>,516203,16510,PC10T4JJ68660_44016.3920154630,<NA>,<NA>,NaT,<NA>,None,None,None,None,NaT,None,None,None,None,None,None,None,None,None,None,<NA>,None,None,None,NaT,None,None,None,NaN,<NA>,NaT,None,None,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,None,None,NaT,None,None,None,None,None,None,None,<NA>,NaN,None,None,None,<NA>,<NA>,None,None,None,None
6,85254,10309,Criopreservado,2,Descongelado,ED4/22,516203,2022-02-16,NaT,8,12897,None,Ciclo a Fresco FIV,NaT,Congelamento total,NaT,No transfer,Inexplicado,Heterólogo,22.15,8,0,37349,Blastocisto Grau V - B - B,Descartado,14416,PC_E58/22,2022-02-21,<NA>,None,NaT,NaT,NaT,<NA>,None,None,NaT,None,NaT,None,NaN,<NA>,<NA>,516203,16510,PC10T4JJ68660_44016.3920154630,<NA>,<NA>,NaT,<NA>,None,None,None,None,NaT,None,None,None,None,None,None,None,None,None,None,<NA>,None,None,None,NaT,None,None,None,NaN,<NA>,NaT,None,None,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,None,None,NaT,None,None,None,None,None,None,None,<NA>,NaN,None,None,None,<NA>,<NA>,None,None,None,None
7,85253,10309,Criopreservado,1,Descongelado,ED4/22,516203,2022-02-16,NaT,8,12897,None,Ciclo a Fresco FIV,NaT,Congelamento total,NaT,No transfer,Inexplicado,Heterólogo,22.15,8,0,37347,Blastocisto Grau V - A - A,Transferido,14416,PC_E58/22,2022-02-21,8452,PC_148/22,2022-03-16,2022-02-21,2022-03-16,12953,None,Ciclo de Congelados,2022-02-25,None,NaT,Gestação Clínica,22.15,8,0,516203,16510,PC10T4JJ68660_44016.3920154630,<NA>,<NA>,NaT,<NA>,None,None,None,None,NaT,None,None,None,None,None,None,None,None,None,None,<NA>,None,None,None,NaT,None,None,None,NaN,<NA>,NaT,None,None,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,None,None,NaT,None,None,None,None,None,None,None,<NA>,NaN,None,None,None,<NA>,<NA>,None,None,None,None
8,83819,10163,Descartado,10,Fresco,745/21,516203,2021-11-30,NaT,10,12449,None,Ciclo a Fresco FIV,2021-11-16,Congelamento total,NaT,None,Inexplicado,Homólogo,22.15,6,0,<NA>,None,None,<NA>,None,NaT,<NA>,None,NaT,NaT,NaT,<NA>,None,None,NaT,None,NaT,None,NaN,<NA>,<NA>,<NA>,<NA>,None,<NA>,<NA>,NaT,<NA>,None,None,None,None,NaT,None,None,None,None,None,None,None,None,None,None,<NA>,None,None,None,NaT,None,None,None,NaN,<NA>,NaT,None,None,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,None,None,NaT,None,None,None,None,None,None,None,<NA>,NaN,None,None,None,<NA>,<NA>,None,None,None,None
9,83818,10163,Descartado,9,Fresco,745/21,516203,2021-11-30,NaT,10,12449,None,Ciclo a Fresco FIV,2021-11-16,Congelamento total,NaT,None,Inexplicado,Homólogo,22.15,6,0,<NA>,None,None,<NA>,None,NaT,<NA>,None,NaT,NaT,NaT,<NA>,None,None,NaT,None,NaT,None,NaN,<NA>,<NA>,<NA>,<NA>,None,<NA>,<NA>,NaT,<NA>,None,None,None,None,NaT,None,None,None,None,None,None,None,None,None,None,<NA>,None,None,None,NaT,None,None,None,NaN,<NA>,NaT,None,None,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,None,None,NaT,None,None,None,None,None,None,None,<NA>,NaN,None,None,None,<NA>,<NA>,None,None,None,None
10,83817,10163,Descartado,8,Fresco,745/21,516203,2021-11-30,NaT,10,12449,None,Ciclo a Fresco FIV,2021-11-16,Congelamento total,NaT,None,Inexplicado,Homólogo,22.15,6,0,<NA>,None,None,<NA>,None,NaT,<NA>,None,NaT,NaT,NaT,<NA>,None,None,NaT,None,NaT,None,NaN,<NA>,<NA>,516203,16510,PC10T4JJ68660_44016.3920154630,<NA>,<NA>,NaT,<NA>,None,None,None,None,NaT,None,None,None,None,None,None,None,None,None,None,<NA>,None,None,None,NaT,None,None,None,NaN,<NA>,NaT,None,None,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,None,None,NaT,None,None,None,None,None,None,None,<NA>,NaN,None,None,None,<NA>,<NA>,None,None,None,None
11,83816,10163,Criopreservado,7,Fresco,745/21,516203,2021-11-30,NaT,10,12449,None,Ciclo a Fresco FIV,2021-11-16,Congelamento total,NaT,None,Inexplicado,Homólogo,22.15,6,0,37000,Blastocisto Grau V - A - A,Descartado,14318,PC_E565/21,2021-12-05,<NA>,None,NaT,NaT,NaT,<NA>,None,None,NaT,None,NaT,None,NaN,<NA>,<NA>,516203,16510,PC10T4JJ68660_44016.3920154630,<NA>,<NA>,NaT,<NA>,None,None,None,None,NaT,None,None,None,None,None,None,None,None,None,None,<NA>,None,None,None,NaT,None,None,None,NaN,<NA>,NaT,None,None,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,None,None,NaT,None,None,None,None,None,None,None,<NA>,NaN,None,None,None,<NA>,<NA>,None,None,None,None
12,83815,10163,Descartado,6,Fresco,745/21,516203,2021-11-30,NaT,10,12449,None,Ciclo a Fresco FIV,2021-11-16,Congelamento total,NaT,None,Inexplicado,Homólogo,22.15,6,0,<NA>,None,None,<NA>,None,NaT,<NA>,None,NaT,NaT,NaT,<NA>,None,None,NaT,None,NaT,None,NaN,<NA>,<NA>,516203,16510,PC10T4JJ68660_44016.3920154630,<NA>,<NA>,NaT,<NA>,None,None,None,None,NaT,None,None,None,None,None,None,None,None,None,None,<NA>,None,None,None,NaT,None,None,None,NaN,<NA>,NaT,None,None,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,None,None,NaT,None,None,None,None,None,None,None,<NA>,NaN,None,None,None,<NA>,<NA>,None,None,None,None
13,83814,10163,Criopreservado,5,Fresco,745/21,516203,2021-11-30,NaT,10,12449,None,Ciclo a Fresco FIV,2021-11-16,Congelamento total,NaT,None,Inexplicado,Homólogo,22.15,6,0,36999,Blastocisto Grau V - A - A,Descartado,14318,PC_E565/21,2021-12-05,<NA>,None,NaT,NaT,NaT,<NA>,None,None,NaT,None,NaT,None,NaN,<NA>,<NA>,516203,16510,PC10T4JJ68660_44016.3920154630,<NA>,<NA>,NaT,<NA>,None,None,None,None,NaT,None,None,None,None,None,None,None,None,None,None,<NA>,None,None,None,NaT,None,None,None,NaN,<NA>,NaT,None,None,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,None,None,NaT,None,None,None,None,None,None,None,<NA>,NaN,None,None,None,<NA>,<NA>,None,None,None,None
14,83813,10163,Descartado,4,Fresco,745/21,516203,2021-11-30,NaT,10,12449,None,Ciclo a Fresco FIV,2021-11-16,Congelamento total,NaT,None,Inexplicado,Homólogo,22.15,6,0,<NA>,None,None,<NA>,None,NaT,<NA>,None,NaT,NaT,NaT,<NA>,None,None,NaT,None,NaT,None,NaN,<NA>,<NA>,516203,16510,PC10T4JJ68660_44016.3920154630,<NA>,<NA>,NaT,<NA>,None,None,None,None,NaT,None,None,None,None,None,None,None,None,None,None,<NA>,None,None,None,NaT,None,None,None,NaN,<NA>,NaT,None,None,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,None,None,NaT,None,None,None,None,None,None,None,<NA>,NaN,None,None,None,<NA>,<NA>,None,None,None,None
15,83812,10163,Criopreservado,3,Fresco,745/21,516203,2021-11-30,NaT,10,12449,None,Ciclo a Fresco FIV,2021-11-16,Congelamento total,NaT,None,Inexplicado,Homólogo,22.15,6,0,36998,Blastocisto Grau V - A - B,Descartado,14318,PC_E565/21,2021-12-05,<NA>,None,NaT,NaT,NaT,<NA>,None,None,NaT,None,NaT,None,NaN,<NA>,<NA>,516203,16510,PC10T4JJ68660_44016.3920154630,<NA>,<NA>,NaT,<NA>,None,None,None,None,NaT,None,None,None,None,None,None,None,None,None,None,<NA>,None,None,None,NaT,None,None,None,NaN,<NA>,NaT,None,None,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,None,None,NaT,None,None,None,None,None,None,None,<NA>,NaN,None,None,None,<NA>,<NA>,None,None,None,None
16,83811,10163,Descartado,2,Fresco,745/21,516203,2021-11-30,NaT,10,12449,None,Ciclo a Fresco FIV,2021-11-16,Congelamento total,NaT,None,Inexplicado,Homólogo,22.15,6,0,<NA>,None,None,<NA>,None,NaT,<NA>,None,NaT,NaT,NaT,<NA>,None,None,NaT,None,NaT,None,NaN,<NA>,<NA>,516203,16510,PC10T4JJ68660_44016.3920154630,<NA>,<NA>,NaT,<NA>,None,None,None,None,NaT,None,None,None,None,None,None,None,None,None,None,<NA>,None,None,None,NaT,None,None,None,NaN,<NA>,NaT,None,None,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,None,None,NaT,None,None,None,None,None,None,None,<NA>,NaN,None,None,None,<NA>,<NA>,None,None,None,None
17,83810,10163,Criopreservado,1,Fresco,745/21,516203,2021-11-30,NaT,10,12449,None,Ciclo a Fresco FIV,2021-11-16,Congelamento total,NaT,None,Inexplicado,Homólogo,22.15,6,0,36997,Blastocisto Grau V - B - C,Descartado,14318,PC_E565/21,2021-12-05,<NA>,None,NaT,NaT,NaT,<NA>,None,None,NaT,None,NaT,None,NaN,<NA>,<NA>,516203,16510,PC10T4JJ68660_44016.3920154630,<NA>,<NA>,NaT,<NA>,None,None,None,None,NaT,None,None,None,None,None,None,None,None,None,None,<NA>,None,None,None,NaT,None,None,None,NaN,<NA>,NaT,None,None,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,None,None,NaT,None,None,None,None,None,None,None,<NA>,NaN,None,None,None,<NA>,<NA>,None,None,None,None
18,83351,10116,Descartado,5,Fresco,704/21,516203,2021-11-12,NaT,5,12382,None,Ciclo a Fresco FIV,2021-11-02,Congelamento total,NaT,None,Inexplicado,Homólogo,22.04,5,0,<NA>,None,None,<NA>,None,NaT,<NA>,None,NaT,NaT,NaT,<NA>,None,None,NaT,None,NaT,None,NaN,<NA>,<NA>,<NA>,<NA>,None,<NA>,<NA>,NaT,<NA>,None,None,None,None,NaT,None,None,None,None,None,None,None,None,None,None,<NA>,None,None,None,NaT,None,None,None,NaN,<NA>,NaT,None,None,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,None,None,NaT,None,None,None,None,None,None,None,<NA>,NaN,None,None,None,<NA>,<NA>,None,None,None,None
19,83350,10116,Descartado,4,Fresco,704/21,516203,2021-11-12,NaT,5,12382,None,Ciclo a Fresco FIV,2021-11-02,Congelamento total,NaT,None,Inexplicado,Homólogo,22.04,5,0,<NA>,None,None,<NA>,None,NaT,<NA>,None,NaT,NaT,NaT,<NA>,None,None,NaT,None,NaT,None,NaN,<NA>,<NA>,<NA>,<NA>,None,<NA>,<NA>,NaT,<NA>,None,None,None,None,NaT,None,None,None,None,None,None,None,None,None,None,<NA>,None,None,None,NaT,None,None,None,NaN,<NA>,NaT,None,None,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,None,None,NaT,None,None,None,None,None,None,None,<NA>,NaN,None,None,None,<NA>,<NA>,None,None,None,None
20,83349,10116,Descartado,3,Fresco,704/21,516203,2021-11-12,NaT,5,12382,None,Ciclo a Fresco FIV,2021-11-02,Congelamento total,NaT,None,Inexplicado,Homólogo,22.04,5,0,<NA>,None,None,<NA>,None,NaT,<NA>,None,NaT,NaT,NaT,<NA>,None,None,NaT,None,NaT,None,NaN,<NA>,<NA>,<NA>,<NA>,None,<NA>,<NA>,NaT,<NA>,None,None,None,None,NaT,None,None,None,None,None,None,None,None,None,None,<NA>,None,None,None,NaT,None,None,None,NaN,<NA>,NaT,None,None,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,None,None,NaT,None,None,None,None,None,None,None,<NA>,NaN,None,None,None,<NA>,<NA>,None,None,None,None
21,83348,10116,Descartado,2,Fresco,704/21,516203,2021-11-12,NaT,5,12382,None,Ciclo a Fresco FIV,2021-11-02,Congelamento total,NaT,None,Inexplicado,Homólogo,22.04,5,0,<NA>,None,None,<NA>,None,NaT,<NA>,None,NaT,NaT,NaT,<NA>,None,None,NaT,None,NaT,None,NaN,<NA>,<NA>,<NA>,<NA>,None,<NA>,<NA>,NaT,<NA>,None,None,None,None,NaT,None,None,None,None,None,None,None,None,None,None,<NA>,None,None,None,NaT,None,None,None,NaN,<NA>,NaT,None,None,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,None,None,NaT,None,None,None,None,None,None,None,<NA>,NaN,None,None,None,<NA>,<NA>,None,None,None,None
22,83347,10116,Descartado,1,Fresco,704/21,516203,2021-11-12,NaT,5,12382,None,Ciclo a Fresco FIV,2021-11-02,Congelamento total,NaT,None,Inexplicado,Homólogo,22.04,5,0,<NA>,None,None,<NA>,None,NaT,<NA>,None,NaT,NaT,NaT,<NA>,None,None,NaT,None,NaT,None,NaN,<NA>,<NA>,<NA>,<NA>,None,<NA>,<NA>,NaT,<NA>,None,None,None,None,NaT,None,None,None,None,None,None,None,None,None,None,<NA>,None,None,None,NaT,None,None,None,NaN,<NA>,NaT,None,None,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,None,None,NaT,None,None,None,None,None,None,None,<NA>,NaN,None,None,None,<NA>,<NA>,None,None,None,None
23,74952,8088,Descartado,5,Fresco,156/21,516203,2021-03-29,NaT,5,10332,None,Ciclo a Fresco FIV,2021-03-15,Congelamento total,NaT,None,Inexplicado,Homólogo,22.04,4,0,<NA>,None,None,<NA>,None,NaT,<NA>,None,NaT,NaT,NaT,<NA>,None,None,NaT,None,NaT,None,NaN,<NA>,<NA>,516203,16510,PC10T4JJ68660_44016.3920154630,<NA>,<NA>,NaT,<NA>,None,None,None,None,NaT,None,None,None,None,None,None,None,None,None,None,<NA>,None,None,None,NaT,None,None,None,NaN,<NA>,NaT,None,None,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,None,None,NaT,None,None,None,None,None,None,None,<NA>,NaN,None,None,None,<NA>,<NA>,None,None,None,None
24,74951,8088,Criopreservado,4,Fresco,156/21,516203,2021-03-29,NaT,5,10332,None,Ciclo a Fresco FIV,2021-03-15,Congelamento total,NaT,None,Inexplicado,Homólogo,22.04,4,0,<NA>,None,None,<NA>,None,NaT,<NA>,None,NaT,NaT,NaT,<NA>,None,None,NaT,None,NaT,None,NaN,<NA>,<NA>,516203,16510,PC10T4JJ68660_44016.3920154630,<NA>,<NA>,NaT,<NA>,None,None,None,None,NaT,None,None,None,None,None,None,None,None,None,None,<NA>,None,None,None,NaT,None,None,None,NaN,<NA>,NaT,None,None,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,None,None,NaT,None,None,None,None,None,None,None,<NA>,NaN,None,None,None,<NA>,<NA>,None,None,None,None
25,74950,8088,Descartado,3,Fresco,156/21,516203,2021-03-29,NaT,5,10332,None,Ciclo a Fresco FIV,2021-03-15,Congelamento total,NaT,None,Inexplicado,Homólogo,22.04,4,0,<NA>,None,None,<NA>,None,NaT,<NA>,None,NaT,NaT,NaT,<NA>,None,None,NaT,None,NaT,None,NaN,<NA>,<NA>,516203,16510,PC10T4JJ68660_44016.3920154630,<NA>,<NA>,NaT,<NA>,None,None,None,None,NaT,None,None,None,None,None,None,None,None,None,None,<NA>,None,None,None,NaT,None,None,None,NaN,<NA>,NaT,None,None,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,None,None,NaT,None,None,None,None,None,None,None,<NA>,NaN,None,None,None,<NA>,<NA>,None,None,None,None
26,74949,8088,Descartado,2,Fresco,156/21,516203,2021-03-29,NaT,5,10332,None,Ciclo a Fresco FIV,2021-03-15,Congelamento total,NaT,None,Inexplicado,Homólogo,22.04,4,0,<NA>,None,None,<NA>,None,NaT,<NA>,None,NaT,NaT,NaT,<NA>,None,None,NaT,None,NaT,None,NaN,<NA>,<NA>,516203,16510,PC10T4JJ68660_44016.3920154630,<NA>,<NA>,NaT,<NA>,None,None,None,None,NaT,None,None,None,None,None,None,None,None,None,None,<NA>,None,None,None,NaT,None,None,None,NaN,<NA>,NaT,None,None,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,None,None,NaT,None,None,None,None,None,None,None,<NA>,NaN,None,None,None,<NA>,<NA>,None,None,None,None
27,74948,8088,Criopreservado,1,Fresco,156/21,516203,2021-03-29,NaT,5,10332,None,Ciclo a Fresco FIV,2021-03-15,Congelamento total,NaT,None,Inexplicado,Homólogo,22.04,4,0,34099,Blastocisto Grau V - A - B,Descartado,12705,PC_E127/21,2021-04-03,<NA>,None,NaT,NaT,NaT,<NA>,None,None,NaT,None,NaT,None,NaN,<NA>,<NA>,516203,16510,PC10T4JJ68660_44016.3920154630,<NA>,<NA>,NaT,<NA>,None,None,None,None,NaT,None,None,None,None,None,None,None,None,None,None,<NA>,None,None,None,NaT,None,None,None,NaN,<NA>,NaT,None,None,None,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,None,None,None,NaT,None,None,None,None,None,None,None,<NA>,NaN,None,None,None,<NA>,<NA>,None,None,None,None

### 14. Congelamentos Ovulos

In [52]:
print("=== CONGELAMENTOS OVULOS DATA ===")
congelamentos_ovulos_data = results['congelamentos_ovulos']
print(f"Records: {len(congelamentos_ovulos_data)}")
if not congelamentos_ovulos_data.empty:
    display(congelamentos_ovulos_data)
else:
    print("No congelamentos ovulos data found.")

=== CONGELAMENTOS OVULOS DATA ===
Records: 1

,id,CodCongelamento,Unidade,prontuario,paciente,Data,Hora,Ciclo,condicoes_amostra,empresa_transporte,clinica_origem,responsavel_recebimento,responsavel_recebimento_data,responsavel_armazenamento,responsavel_armazenamento_data,NOvulos,NPailletes,Identificacao,Tambor,Cane,Cane2,Tecnica,Motivo,Observacoes,BiologoResponsavel,BiologoFIV,BiologoFIV2,status_financeiro,hash,extraction_timestamp
0,7122,PC_O28/22,7,516203,esposa,2022-01-10,1900-01-01 10:00:00,None,None,None,None,<NA>,NaT,<NA>,NaT,8,2,SLB16510,O2,Branca,OVOD 1511,BOSP,Recepção,None,<NA>,Camila Cruz de Moraes,Camila Cruz de Moraes,None,db8e64487da15b8ca024ba090e4523cb,2025-07-21 21:38:49

### 15. Descongelamentos Ovulos

In [53]:
print("=== DESCONGELAMENTOS OVULOS DATA ===")
descongelamentos_ovulos_data = results['descongelamentos_ovulos']
print(f"Records: {len(descongelamentos_ovulos_data)}")
if not descongelamentos_ovulos_data.empty:
    display(descongelamentos_ovulos_data)
else:
    print("No descongelamentos ovulos data found.")

=== DESCONGELAMENTOS OVULOS DATA ===
Records: 1

,id,CodDescongelamento,Unidade,prontuario,doadora,DataCongelamento,DataDescongelamento,Ciclo,Identificacao,CodCongelamento,Tambor,Cane,PailletesDescongeladas,Tecnica,Observacoes,BiologoFIV,BiologoFIV2,hash,extraction_timestamp
0,2029,PC_DO4/22,None,516203,0,2022-01-10,2022-02-16,-,SLB16510,PC_O28/22,O2,Branca,2,Desvitrificação,None,None,None,986fc3c45c338a1b1767663a22c338cb,2025-07-21 21:38:53

### 16. Ovulos Congelados

In [54]:
print("=== OVULOS CONGELADOS DATA ===")
ovulos_congelados_data = results['ovulos_congelados']
print(f"Records: {len(ovulos_congelados_data)}")
if not ovulos_congelados_data.empty:
    display(ovulos_congelados_data)
else:
    print("No ovulos congelados data found.")

=== OVULOS CONGELADOS DATA ===
Records: 8

,id,id_congelamento,id_descongelamento,prontuario,pailletes,cores,ovulo,celulas,qualidade,qualidade_recongelamento,comentarios,comentarios_descongelamento,rc,dia2,maturidade,dia2_2,dia2_3,clivou_d2,transferidos,pgd,resultado_pgd,tanque_amostra,caneca_amostra,rack_amostra,observacao,destino,hash,extraction_timestamp
0,35123,7122,2029,516203,P2,<NA>,8.0,<NA>,<NA>,<NA>,None,None,None,DEG,MII,None,None,<NA>,None,<NA>,<NA>,None,None,None,None,<NA>,945df8284c289cfe0d16b59ef2a5bfb7,2025-10-14 21:04:28
1,35122,7122,2029,516203,P2,<NA>,7.0,<NA>,<NA>,<NA>,None,None,None,DEG,MII,None,None,<NA>,None,<NA>,<NA>,None,None,None,None,<NA>,deb6bd0baf75fd85b5deec156c31f51b,2025-10-14 21:04:28
2,35121,7122,2029,516203,P2,<NA>,6.0,<NA>,<NA>,<NA>,None,None,None,MII,MII,None,None,<NA>,None,<NA>,<NA>,None,None,None,None,<NA>,e5004fab32235dfef61a9dc902ccc841,2025-10-14 21:04:28
3,35120,7122,2029,516203,P2,<NA>,5.0,<NA>,<NA>,<NA>,None,None,None,MII,MII,None,None,<NA>,None,<NA>,<NA>,None,None,None,None,<NA>,7e81390549ac8b9417e27abac0939d01,2025-10-14 21:04:28
4,35119,7122,2029,516203,P1,<NA>,4.0,<NA>,<NA>,<NA>,None,None,None,MII,MII,None,None,<NA>,None,<NA>,<NA>,None,None,None,None,<NA>,adaec67405e9cb0ddfa30b5f7f370c91,2025-10-14 21:04:28
5,35118,7122,2029,516203,P1,<NA>,3.0,<NA>,<NA>,<NA>,None,None,None,MII,MII,None,None,<NA>,None,<NA>,<NA>,None,None,None,None,<NA>,157266b1a1fac894e5bdaa43f5d4b162,2025-10-14 21:04:28
6,35117,7122,2029,516203,P1,<NA>,2.0,<NA>,<NA>,<NA>,None,None,None,MII,MII,None,None,<NA>,None,<NA>,<NA>,None,None,None,None,<NA>,690d87cc8cb2b338d3813b0d57f3f1dc,2025-10-14 21:04:28
7,35116,7122,2029,516203,P1,<NA>,1.0,<NA>,<NA>,<NA>,None,None,None,MII,MII,None,None,<NA>,None,<NA>,<NA>,None,None,None,None,<NA>,3c1b0214aca2159391d302b29981550f,2025-10-14 21:04:28

### 17. Redlara

In [55]:
print("=== Redlara Unified ===")
redlara_unified = results['redlara_unified']
print(f"Records: {len(redlara_unified)}")
if not redlara_unified.empty:
    display(redlara_unified)
else:
    print("No redlara unified data found.")

=== Redlara Unified ===
Records: 0
No redlara unified data found.

### 18. Redlara - planilha combined

In [56]:
print("=== Redlara planilha combined ===")
redlara_planilha_combined = results['redlara_planilha_combined']
print(f"Records: {len(redlara_planilha_combined)}")
if not redlara_planilha_combined.empty:
    display(redlara_planilha_combined)
else:
    print("No redlara_planilha_combined data found.")

=== Redlara planilha combined ===
Records: 0
No redlara_planilha_combined data found.